// Curated reference pools. Kept hand-written (rather than delegated to faker) so
// that geography stays internally consistent — country, city, postal code and
// dial code always agree — which the compliance narrative relies on.

export const FIRST = [
  'Emma',
  'Lucas',
  'Sofia',
  'Liam',
  'Mia',
  'Noah',
  'Olivia',
  'Hugo',
  'Léa',
  'Jonas',
  'Priya',
  'Mateo',
  'Ingrid',
  'Youssef',
  'Anna',
  'Marco',
  'Fatima',
  'Erik',
  'Chloé',
  'Viktor',
  'Aisha',
  'Daniel',
  'Elena',
  'Tomas',
  'Nadia',
  'Pablo',
  'Greta',
  'Kemal',
  'Sara',
  'Andrei',
  'Maja',
  'Stefan',
  'Camille',
  'Dimitri',
  'Zofia',
  'Omar',
  'Linnea',
  'Rafael',
  'Yara',
  'Janusz',
  'Beatriz',
  'Henrik',
  'Amara',
  'Niko',
  'Wei',
  'Ravi',
  'Sasha',
  'Lena',
];
export const LAST = [
  'Johansson',
  'Müller',
  'Rossi',
  'Dubois',
  'Nowak',
  'García',
  'Andersen',
  'Schneider',
  'Kowalski',
  'Ferretti',
  'Sharma',
  'Weber',
  'Lindqvist',
  'Haddad',
  'Novak',
  'Petrov',
  'Bianchi',
  'Mensah',
  'Costa',
  'Ahmadi',
  'Berg',
  'Romano',
  'Fischer',
  'Sørensen',
  'Marchetti',
  'Khan',
  'Olsen',
  'Demir',
  'Vargas',
  'Ivanov',
  'Lefebvre',
  'Kovač',
  'Jensen',
  'Moreau',
  'Santos',
  'Hassan',
  'Eriksson',
  'Lopez',
  'Popescu',
  'Wójcik',
];
export const COUNTRIES = [
  'DE',
  'FR',
  'SE',
  'IT',
  'ES',
  'NL',
  'PL',
  'BE',
  'DK',
  'NO',
  'FI',
  'PT',
  'AT',
  'IE',
  'CZ',
];
export const HIGH_RISK_COUNTRIES = ['RU', 'IR', 'SY', 'AF', 'MM', 'BY'];
export const CITIES: Record<string, [string, string][]> = {
  DE: [
    ['Berlin', '10117'],
    ['Munich', '80331'],
    ['Hamburg', '20095'],
  ],
  FR: [
    ['Paris', '75001'],
    ['Lyon', '69001'],
    ['Marseille', '13001'],
  ],
  SE: [
    ['Stockholm', '11129'],
    ['Gothenburg', '41103'],
  ],
  IT: [
    ['Milan', '20121'],
    ['Rome', '00184'],
  ],
  ES: [
    ['Madrid', '28013'],
    ['Barcelona', '08001'],
  ],
  NL: [['Amsterdam', '1011']],
  PL: [['Warsaw', '00-001']],
  BE: [['Brussels', '1000']],
  DK: [['Copenhagen', '1050']],
  NO: [['Oslo', '0150']],
  FI: [['Helsinki', '00100']],
  PT: [['Lisbon', '1100']],
  AT: [['Vienna', '1010']],
  IE: [['Dublin', 'D01']],
  CZ: [['Prague', '11000']],
  RU: [['Moscow', '101000']],
  IR: [['Tehran', '11369']],
  SY: [['Damascus', '00963']],
  AF: [['Kabul', '1001']],
  MM: [['Yangon', '11181']],
  BY: [['Minsk', '220000']],
};
export const DIAL: Record<string, string> = {
  DE: '49',
  FR: '33',
  SE: '46',
  IT: '39',
  ES: '34',
  NL: '31',
  PL: '48',
  BE: '32',
  DK: '45',
  NO: '47',
  FI: '358',
  PT: '351',
  AT: '43',
  IE: '353',
  CZ: '420',
  RU: '7',
  IR: '98',
  SY: '963',
  AF: '93',
  MM: '95',
  BY: '375',
};
export const STREETS = [
  'Hauptstraße',
  'Rue de la Paix',
  'Storgatan',
  'Via Roma',
  'Calle Mayor',
  'Damrak',
  'Marszałkowska',
  'Rue Royale',
  'Nørregade',
  'Karl Johans gate',
  'Mannerheimintie',
];
export const MERCHANTS: [string, string, string][] = [
  ['Amazon EU SARL', 'E-COMMERCE', '5942'],
  ['Spotify AB', 'STREAMING', '4899'],
  ['Steam (Valve)', 'DIGITAL_GOODS', '5816'],
  ['Wolt', 'FOOD_DELIVERY', '5814'],
  ['Uber BV', 'RIDESHARE', '4121'],
  ['Booking.com', 'TRAVEL', '4722'],
  ['Ryanair', 'AIRLINE', '3000'],
  ['MediaMarkt', 'ELECTRONICS', '5732'],
  ['Zalando SE', 'FASHION', '5651'],
  ['CryptoExchange XYZ', 'CRYPTO', '6051'],
  ['Netflix Intl', 'STREAMING', '4899'],
  ['Apple Distribution', 'DIGITAL_GOODS', '5816'],
  ['Carrefour', 'GROCERY', '5411'],
  ['Shell', 'FUEL', '5541'],
  ['IKEA', 'FURNITURE', '5712'],
  ['Glovo', 'FOOD_DELIVERY', '5814'],
  ['Binance', 'CRYPTO', '6051'],
  ['Decathlon', 'SPORTING', '5941'],
];
export const CB_REASONS: [string, string][] = [
  ['4853', 'Cardholder Dispute — Services Not Provided'],
  ['4831', 'Disputed Amount'],
  ['10.4', 'Fraud — Card-Not-Present'],
  ['10.5', 'Fraud — Card-Present Environment'],
  ['13.1', 'Merchandise Not Received'],
  ['12.6', 'Duplicate Processing'],
  ['4837', 'No Cardholder Authorization'],
];
export const CB_STATUS = [
  'INITIATED',
  'PRESENTED',
  'REPRESENTED',
  'WON',
  'LOST',
  'PRE_ARBITRATION',
  'ACCEPTED',
  'ARBITRATION',
];
export const ANALYSTS = [
  'a.kowalski@neobank.eu',
  's.bauer@neobank.eu',
  'm.rossi@neobank.eu',
  'compliance@neobank.eu',
];
export const DOC_TYPES = [
  'PASSPORT',
  'NATIONAL_ID',
  'DRIVERS_LICENSE',
  'PROOF_OF_ADDRESS',
  'SELFIE',
  'BANK_STATEMENT',
];
export const ATYPES = [
  'UNUSUAL_VOLUME',
  'SUSPICIOUS_PATTERN',
  'SANCTIONS_MATCH',
  'HIGH_RISK_COUNTRY',
  'RAPID_MOVEMENT',
  'STRUCTURING',
];
export const REFUND_REASONS = [
  'DUPLICATE_CHARGE',
  'SERVICE_NOT_RENDERED',
  'ITEM_NOT_RECEIVED',
  'UNAUTHORIZED',
  'CANCELLED_ORDER',
];
export const SOURCES = ['CUSTOMER_DISPUTE', 'INTERNAL_DETECTION', 'MERCHANT_ALERT'];

// Enum domains — the single source of truth for the values the seed emits, reused
// both by the builders (where they enumerate a full set) and by the enum re-typing
// in `src/index.ts`. Values only ever written by Smart Actions (e.g. `SAR_FILED`,
// `DISMISSED`) are added at the enum site, not here, since the seed never emits them.
export const ONBOARDING_STATUSES = ['STARTED', 'PENDING_REVIEW', 'APPROVED', 'REJECTED'];
export const RISK_RATINGS = ['LOW', 'MEDIUM', 'HIGH'];
export const CARD_TYPES = ['VIRTUAL', 'PHYSICAL'];
export const CARD_STATUSES = ['ACTIVE', 'BLOCKED', 'EXPIRED', 'PENDING', 'CANCELLED'];
export const AML_SEVERITIES = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'];
export const AML_STATUSES = ['OPEN', 'IN_REVIEW', 'CLEARED', 'ESCALATED'];
export const KYC_STATUSES = [
  'OPEN',
  'IN_REVIEW',
  'PENDING_APPROVAL',
  'APPROVED',
  'REJECTED',
  'ESCALATED',
];
export const NETWORKS = ['VISA', 'MASTERCARD'];
export const REFUND_STATUSES = ['PENDING', 'APPROVED', 'DECLINED', 'ESCALATED'];
export const SAR_STATUSES = ['DRAFT', 'SUBMITTED', 'FILED'];

const ACCENTS: Record<string, string> = {
  ø: 'o',
  č: 'c',
  š: 's',
  é: 'e',
  ü: 'u',
  ć: 'c',
  ä: 'a',
  ö: 'o',
  å: 'a',
};
export const deaccent = (s: string): string => s.replace(/[øčšéüćäöå]/g, c => ACCENTS[c] ?? c);
