// Override the types from sequelize to add properties from private fields and methods
// that we use in the datasource-sequelize package, but that are not exported by sequelize.

import {
  AbstractDataType,
  AbstractDataTypeConstructor,
  ArrayDataType,
  BelongsToMany,
  Model,
  ModelAttributeColumnOptions,
} from 'sequelize';

export interface BelongsToManyExt extends BelongsToMany {
  through: { model: typeof Model };
}

export interface ModelAttributeColumnOptionsExt extends ModelAttributeColumnOptions {
  _autoGenerated?: boolean;
}

export interface ArrayDataTypeExt<T extends AbstractDataTypeConstructor | AbstractDataType>
  extends ArrayDataType<T> {
  type: AbstractDataType;
}
