/* eslint-disable */
import {
  CollectionCustomizer,
  TAggregation,
  TConditionTree,
  TPaginatedFilter,
  TPartialRow,
  TSortClause
} from '@forestadmin/agent';

export type ActorCustomizer = CollectionCustomizer<Schema, 'actor'>;
export type ActorRecord = TPartialRow<Schema, 'actor'>;
export type ActorConditionTree = TConditionTree<Schema, 'actor'>;
export type ActorFilter = TPaginatedFilter<Schema, 'actor'>;
export type ActorSortClause = TSortClause<Schema, 'actor'>;
export type ActorAggregation = TAggregation<Schema, 'actor'>;

export type AddressCustomizer = CollectionCustomizer<Schema, 'address'>;
export type AddressRecord = TPartialRow<Schema, 'address'>;
export type AddressConditionTree = TConditionTree<Schema, 'address'>;
export type AddressFilter = TPaginatedFilter<Schema, 'address'>;
export type AddressSortClause = TSortClause<Schema, 'address'>;
export type AddressAggregation = TAggregation<Schema, 'address'>;

export type CategoryCustomizer = CollectionCustomizer<Schema, 'category'>;
export type CategoryRecord = TPartialRow<Schema, 'category'>;
export type CategoryConditionTree = TConditionTree<Schema, 'category'>;
export type CategoryFilter = TPaginatedFilter<Schema, 'category'>;
export type CategorySortClause = TSortClause<Schema, 'category'>;
export type CategoryAggregation = TAggregation<Schema, 'category'>;

export type CityCustomizer = CollectionCustomizer<Schema, 'city'>;
export type CityRecord = TPartialRow<Schema, 'city'>;
export type CityConditionTree = TConditionTree<Schema, 'city'>;
export type CityFilter = TPaginatedFilter<Schema, 'city'>;
export type CitySortClause = TSortClause<Schema, 'city'>;
export type CityAggregation = TAggregation<Schema, 'city'>;

export type CountryCustomizer = CollectionCustomizer<Schema, 'country'>;
export type CountryRecord = TPartialRow<Schema, 'country'>;
export type CountryConditionTree = TConditionTree<Schema, 'country'>;
export type CountryFilter = TPaginatedFilter<Schema, 'country'>;
export type CountrySortClause = TSortClause<Schema, 'country'>;
export type CountryAggregation = TAggregation<Schema, 'country'>;

export type CustomerCustomizer = CollectionCustomizer<Schema, 'customer'>;
export type CustomerRecord = TPartialRow<Schema, 'customer'>;
export type CustomerConditionTree = TConditionTree<Schema, 'customer'>;
export type CustomerFilter = TPaginatedFilter<Schema, 'customer'>;
export type CustomerSortClause = TSortClause<Schema, 'customer'>;
export type CustomerAggregation = TAggregation<Schema, 'customer'>;

export type DepartmentsCustomizer = CollectionCustomizer<Schema, 'departments'>;
export type DepartmentsRecord = TPartialRow<Schema, 'departments'>;
export type DepartmentsConditionTree = TConditionTree<Schema, 'departments'>;
export type DepartmentsFilter = TPaginatedFilter<Schema, 'departments'>;
export type DepartmentsSortClause = TSortClause<Schema, 'departments'>;
export type DepartmentsAggregation = TAggregation<Schema, 'departments'>;

export type FilmCustomizer = CollectionCustomizer<Schema, 'film'>;
export type FilmRecord = TPartialRow<Schema, 'film'>;
export type FilmConditionTree = TConditionTree<Schema, 'film'>;
export type FilmFilter = TPaginatedFilter<Schema, 'film'>;
export type FilmSortClause = TSortClause<Schema, 'film'>;
export type FilmAggregation = TAggregation<Schema, 'film'>;

export type FilmActorCustomizer = CollectionCustomizer<Schema, 'film_actor'>;
export type FilmActorRecord = TPartialRow<Schema, 'film_actor'>;
export type FilmActorConditionTree = TConditionTree<Schema, 'film_actor'>;
export type FilmActorFilter = TPaginatedFilter<Schema, 'film_actor'>;
export type FilmActorSortClause = TSortClause<Schema, 'film_actor'>;
export type FilmActorAggregation = TAggregation<Schema, 'film_actor'>;

export type FilmCategoryCustomizer = CollectionCustomizer<Schema, 'film_category'>;
export type FilmCategoryRecord = TPartialRow<Schema, 'film_category'>;
export type FilmCategoryConditionTree = TConditionTree<Schema, 'film_category'>;
export type FilmCategoryFilter = TPaginatedFilter<Schema, 'film_category'>;
export type FilmCategorySortClause = TSortClause<Schema, 'film_category'>;
export type FilmCategoryAggregation = TAggregation<Schema, 'film_category'>;

export type InventoryCustomizer = CollectionCustomizer<Schema, 'inventory'>;
export type InventoryRecord = TPartialRow<Schema, 'inventory'>;
export type InventoryConditionTree = TConditionTree<Schema, 'inventory'>;
export type InventoryFilter = TPaginatedFilter<Schema, 'inventory'>;
export type InventorySortClause = TSortClause<Schema, 'inventory'>;
export type InventoryAggregation = TAggregation<Schema, 'inventory'>;

export type LanguageCustomizer = CollectionCustomizer<Schema, 'language'>;
export type LanguageRecord = TPartialRow<Schema, 'language'>;
export type LanguageConditionTree = TConditionTree<Schema, 'language'>;
export type LanguageFilter = TPaginatedFilter<Schema, 'language'>;
export type LanguageSortClause = TSortClause<Schema, 'language'>;
export type LanguageAggregation = TAggregation<Schema, 'language'>;

export type PaymentCustomizer = CollectionCustomizer<Schema, 'payment'>;
export type PaymentRecord = TPartialRow<Schema, 'payment'>;
export type PaymentConditionTree = TConditionTree<Schema, 'payment'>;
export type PaymentFilter = TPaginatedFilter<Schema, 'payment'>;
export type PaymentSortClause = TSortClause<Schema, 'payment'>;
export type PaymentAggregation = TAggregation<Schema, 'payment'>;

export type RegionsCustomizer = CollectionCustomizer<Schema, 'regions'>;
export type RegionsRecord = TPartialRow<Schema, 'regions'>;
export type RegionsConditionTree = TConditionTree<Schema, 'regions'>;
export type RegionsFilter = TPaginatedFilter<Schema, 'regions'>;
export type RegionsSortClause = TSortClause<Schema, 'regions'>;
export type RegionsAggregation = TAggregation<Schema, 'regions'>;

export type RentalCustomizer = CollectionCustomizer<Schema, 'rental'>;
export type RentalRecord = TPartialRow<Schema, 'rental'>;
export type RentalConditionTree = TConditionTree<Schema, 'rental'>;
export type RentalFilter = TPaginatedFilter<Schema, 'rental'>;
export type RentalSortClause = TSortClause<Schema, 'rental'>;
export type RentalAggregation = TAggregation<Schema, 'rental'>;

export type StaffCustomizer = CollectionCustomizer<Schema, 'staff'>;
export type StaffRecord = TPartialRow<Schema, 'staff'>;
export type StaffConditionTree = TConditionTree<Schema, 'staff'>;
export type StaffFilter = TPaginatedFilter<Schema, 'staff'>;
export type StaffSortClause = TSortClause<Schema, 'staff'>;
export type StaffAggregation = TAggregation<Schema, 'staff'>;

export type StoreCustomizer = CollectionCustomizer<Schema, 'store'>;
export type StoreRecord = TPartialRow<Schema, 'store'>;
export type StoreConditionTree = TConditionTree<Schema, 'store'>;
export type StoreFilter = TPaginatedFilter<Schema, 'store'>;
export type StoreSortClause = TSortClause<Schema, 'store'>;
export type StoreAggregation = TAggregation<Schema, 'store'>;

export type TownsCustomizer = CollectionCustomizer<Schema, 'towns'>;
export type TownsRecord = TPartialRow<Schema, 'towns'>;
export type TownsConditionTree = TConditionTree<Schema, 'towns'>;
export type TownsFilter = TPaginatedFilter<Schema, 'towns'>;
export type TownsSortClause = TSortClause<Schema, 'towns'>;
export type TownsAggregation = TAggregation<Schema, 'towns'>;


export type Schema = {
  'actor': {
    plain: {
      'actor_id': number;
      'first_name': string;
      'last_name': string;
      'last_update': string;
    };
    nested: {};
    flat: {};
  };
  'address': {
    plain: {
      'address': string;
      'address_id': number;
      'address2': string;
      'city_id': number;
      'district': string;
      'last_update': string;
      'phone': string;
      'postal_code': string;
    };
    nested: {
      'city': Schema['city']['plain'] & Schema['city']['nested'];
    };
    flat: {
      'city:city': string;
      'city:city_id': number;
      'city:country_id': number;
      'city:last_update': string;
      'city:country:country': string;
      'city:country:country_id': number;
      'city:country:last_update': string;
    };
  };
  'category': {
    plain: {
      'category_id': number;
      'last_update': string;
      'name': string;
    };
    nested: {};
    flat: {};
  };
  'city': {
    plain: {
      'city': string;
      'city_id': number;
      'country_id': number;
      'last_update': string;
    };
    nested: {
      'country': Schema['country']['plain'] & Schema['country']['nested'];
    };
    flat: {
      'country:country': string;
      'country:country_id': number;
      'country:last_update': string;
    };
  };
  'country': {
    plain: {
      'country': string;
      'country_id': number;
      'last_update': string;
    };
    nested: {};
    flat: {};
  };
  'customer': {
    plain: {
      'active': number;
      'activebool': boolean;
      'address_id': number;
      'create_date': string;
      'customer_id': number;
      'email': string;
      'first_name': string;
      'last_name': string;
      'last_update': string;
      'store_id': number;
    };
    nested: {
      'address': Schema['address']['plain'] & Schema['address']['nested'];
      'store': Schema['store']['plain'] & Schema['store']['nested'];
    };
    flat: {
      'address:address': string;
      'address:address_id': number;
      'address:address2': string;
      'address:city_id': number;
      'address:district': string;
      'address:last_update': string;
      'address:phone': string;
      'address:postal_code': string;
      'store:address_id': number;
      'store:last_update': string;
      'store:manager_staff_id': number;
      'store:store_id': number;
      'address:city:city': string;
      'address:city:city_id': number;
      'address:city:country_id': number;
      'address:city:last_update': string;
      'store:address:address': string;
      'store:address:address_id': number;
      'store:address:address2': string;
      'store:address:city_id': number;
      'store:address:district': string;
      'store:address:last_update': string;
      'store:address:phone': string;
      'store:address:postal_code': string;
      'store:manager_staff:active': boolean;
      'store:manager_staff:address_id': number;
      'store:manager_staff:email': string;
      'store:manager_staff:first_name': string;
      'store:manager_staff:last_name': string;
      'store:manager_staff:last_update': string;
      'store:manager_staff:password': string;
      'store:manager_staff:picture': Buffer;
      'store:manager_staff:staff_id': number;
      'store:manager_staff:store_id': number;
      'store:manager_staff:username': string;
      'address:city:country:country': string;
      'address:city:country:country_id': number;
      'address:city:country:last_update': string;
      'store:address:city:city': string;
      'store:address:city:city_id': number;
      'store:address:city:country_id': number;
      'store:address:city:last_update': string;
      'store:manager_staff:address:address': string;
      'store:manager_staff:address:address_id': number;
      'store:manager_staff:address:address2': string;
      'store:manager_staff:address:city_id': number;
      'store:manager_staff:address:district': string;
      'store:manager_staff:address:last_update': string;
      'store:manager_staff:address:phone': string;
      'store:manager_staff:address:postal_code': string;
      'store:manager_staff:store_through_store_id:address_id': number;
      'store:manager_staff:store_through_store_id:last_update': string;
      'store:manager_staff:store_through_store_id:manager_staff_id': number;
      'store:manager_staff:store_through_store_id:store_id': number;
    };
  };
  'departments': {
    plain: {
      'capital': string;
      'code': string;
      'id': number;
      'name': string;
      'region': string;
    };
    nested: {
      'region_through_region': Schema['regions']['plain'] & Schema['regions']['nested'];
    };
    flat: {
      'region_through_region:capital': string;
      'region_through_region:code': string;
      'region_through_region:id': number;
      'region_through_region:name': string;
    };
  };
  'film': {
    plain: {
      'description': string;
      'film_id': number;
      'language_id': number;
      'last_update': string;
      'length': number;
      'original_language_id': number;
      'rating': 'G' | 'NC-17' | 'PG' | 'PG-13' | 'R';
      'release_year': number;
      'rental_duration': number;
      'rental_rate': number;
      'replacement_cost': number;
      'special_features': Array<string>;
      'title': string;
    };
    nested: {
      'language': Schema['language']['plain'] & Schema['language']['nested'];
      'original_language': Schema['language']['plain'] & Schema['language']['nested'];
    };
    flat: {
      'language:language_id': number;
      'language:last_update': string;
      'language:name': string;
      'original_language:language_id': number;
      'original_language:last_update': string;
      'original_language:name': string;
    };
  };
  'film_actor': {
    plain: {
      'actor_id': number;
      'film_id': number;
      'last_update': string;
    };
    nested: {
      'actor': Schema['actor']['plain'] & Schema['actor']['nested'];
      'film': Schema['film']['plain'] & Schema['film']['nested'];
    };
    flat: {
      'actor:actor_id': number;
      'actor:first_name': string;
      'actor:last_name': string;
      'actor:last_update': string;
      'film:description': string;
      'film:film_id': number;
      'film:language_id': number;
      'film:last_update': string;
      'film:length': number;
      'film:original_language_id': number;
      'film:rating': 'G' | 'NC-17' | 'PG' | 'PG-13' | 'R';
      'film:release_year': number;
      'film:rental_duration': number;
      'film:rental_rate': number;
      'film:replacement_cost': number;
      'film:special_features': Array<string>;
      'film:title': string;
      'film:language:language_id': number;
      'film:language:last_update': string;
      'film:language:name': string;
      'film:original_language:language_id': number;
      'film:original_language:last_update': string;
      'film:original_language:name': string;
    };
  };
  'film_category': {
    plain: {
      'category_id': number;
      'film_id': number;
      'last_update': string;
    };
    nested: {
      'category': Schema['category']['plain'] & Schema['category']['nested'];
      'film': Schema['film']['plain'] & Schema['film']['nested'];
    };
    flat: {
      'category:category_id': number;
      'category:last_update': string;
      'category:name': string;
      'film:description': string;
      'film:film_id': number;
      'film:language_id': number;
      'film:last_update': string;
      'film:length': number;
      'film:original_language_id': number;
      'film:rating': 'G' | 'NC-17' | 'PG' | 'PG-13' | 'R';
      'film:release_year': number;
      'film:rental_duration': number;
      'film:rental_rate': number;
      'film:replacement_cost': number;
      'film:special_features': Array<string>;
      'film:title': string;
      'film:language:language_id': number;
      'film:language:last_update': string;
      'film:language:name': string;
      'film:original_language:language_id': number;
      'film:original_language:last_update': string;
      'film:original_language:name': string;
    };
  };
  'inventory': {
    plain: {
      'film_id': number;
      'inventory_id': number;
      'last_update': string;
      'store_id': number;
    };
    nested: {
      'film': Schema['film']['plain'] & Schema['film']['nested'];
      'store': Schema['store']['plain'] & Schema['store']['nested'];
    };
    flat: {
      'film:description': string;
      'film:film_id': number;
      'film:language_id': number;
      'film:last_update': string;
      'film:length': number;
      'film:original_language_id': number;
      'film:rating': 'G' | 'NC-17' | 'PG' | 'PG-13' | 'R';
      'film:release_year': number;
      'film:rental_duration': number;
      'film:rental_rate': number;
      'film:replacement_cost': number;
      'film:special_features': Array<string>;
      'film:title': string;
      'store:address_id': number;
      'store:last_update': string;
      'store:manager_staff_id': number;
      'store:store_id': number;
      'film:language:language_id': number;
      'film:language:last_update': string;
      'film:language:name': string;
      'film:original_language:language_id': number;
      'film:original_language:last_update': string;
      'film:original_language:name': string;
      'store:address:address': string;
      'store:address:address_id': number;
      'store:address:address2': string;
      'store:address:city_id': number;
      'store:address:district': string;
      'store:address:last_update': string;
      'store:address:phone': string;
      'store:address:postal_code': string;
      'store:manager_staff:active': boolean;
      'store:manager_staff:address_id': number;
      'store:manager_staff:email': string;
      'store:manager_staff:first_name': string;
      'store:manager_staff:last_name': string;
      'store:manager_staff:last_update': string;
      'store:manager_staff:password': string;
      'store:manager_staff:picture': Buffer;
      'store:manager_staff:staff_id': number;
      'store:manager_staff:store_id': number;
      'store:manager_staff:username': string;
      'store:address:city:city': string;
      'store:address:city:city_id': number;
      'store:address:city:country_id': number;
      'store:address:city:last_update': string;
      'store:manager_staff:address:address': string;
      'store:manager_staff:address:address_id': number;
      'store:manager_staff:address:address2': string;
      'store:manager_staff:address:city_id': number;
      'store:manager_staff:address:district': string;
      'store:manager_staff:address:last_update': string;
      'store:manager_staff:address:phone': string;
      'store:manager_staff:address:postal_code': string;
      'store:manager_staff:store_through_store_id:address_id': number;
      'store:manager_staff:store_through_store_id:last_update': string;
      'store:manager_staff:store_through_store_id:manager_staff_id': number;
      'store:manager_staff:store_through_store_id:store_id': number;
    };
  };
  'language': {
    plain: {
      'language_id': number;
      'last_update': string;
      'name': string;
    };
    nested: {};
    flat: {};
  };
  'payment': {
    plain: {
      'amount': number;
      'customer_id': number;
      'payment_date': string;
      'payment_id': number;
      'rental_id': number;
      'staff_id': number;
    };
    nested: {
      'customer': Schema['customer']['plain'] & Schema['customer']['nested'];
      'rental': Schema['rental']['plain'] & Schema['rental']['nested'];
      'staff': Schema['staff']['plain'] & Schema['staff']['nested'];
    };
    flat: {
      'customer:active': number;
      'customer:activebool': boolean;
      'customer:address_id': number;
      'customer:create_date': string;
      'customer:customer_id': number;
      'customer:email': string;
      'customer:first_name': string;
      'customer:last_name': string;
      'customer:last_update': string;
      'customer:store_id': number;
      'rental:customer_id': number;
      'rental:inventory_id': number;
      'rental:last_update': string;
      'rental:rental_date': string;
      'rental:rental_id': number;
      'rental:return_date': string;
      'rental:staff_id': number;
      'staff:active': boolean;
      'staff:address_id': number;
      'staff:email': string;
      'staff:first_name': string;
      'staff:last_name': string;
      'staff:last_update': string;
      'staff:password': string;
      'staff:picture': Buffer;
      'staff:staff_id': number;
      'staff:store_id': number;
      'staff:username': string;
      'customer:address:address': string;
      'customer:address:address_id': number;
      'customer:address:address2': string;
      'customer:address:city_id': number;
      'customer:address:district': string;
      'customer:address:last_update': string;
      'customer:address:phone': string;
      'customer:address:postal_code': string;
      'customer:store:address_id': number;
      'customer:store:last_update': string;
      'customer:store:manager_staff_id': number;
      'customer:store:store_id': number;
      'rental:customer:active': number;
      'rental:customer:activebool': boolean;
      'rental:customer:address_id': number;
      'rental:customer:create_date': string;
      'rental:customer:customer_id': number;
      'rental:customer:email': string;
      'rental:customer:first_name': string;
      'rental:customer:last_name': string;
      'rental:customer:last_update': string;
      'rental:customer:store_id': number;
      'rental:inventory:film_id': number;
      'rental:inventory:inventory_id': number;
      'rental:inventory:last_update': string;
      'rental:inventory:store_id': number;
      'rental:staff:active': boolean;
      'rental:staff:address_id': number;
      'rental:staff:email': string;
      'rental:staff:first_name': string;
      'rental:staff:last_name': string;
      'rental:staff:last_update': string;
      'rental:staff:password': string;
      'rental:staff:picture': Buffer;
      'rental:staff:staff_id': number;
      'rental:staff:store_id': number;
      'rental:staff:username': string;
      'staff:address:address': string;
      'staff:address:address_id': number;
      'staff:address:address2': string;
      'staff:address:city_id': number;
      'staff:address:district': string;
      'staff:address:last_update': string;
      'staff:address:phone': string;
      'staff:address:postal_code': string;
      'staff:store_through_staff_manager_staff_id:address_id': number;
      'staff:store_through_staff_manager_staff_id:last_update': string;
      'staff:store_through_staff_manager_staff_id:manager_staff_id': number;
      'staff:store_through_staff_manager_staff_id:store_id': number;
      'staff:store_through_store_id:address_id': number;
      'staff:store_through_store_id:last_update': string;
      'staff:store_through_store_id:manager_staff_id': number;
      'staff:store_through_store_id:store_id': number;
      'customer:address:city:city': string;
      'customer:address:city:city_id': number;
      'customer:address:city:country_id': number;
      'customer:address:city:last_update': string;
      'customer:store:address:address': string;
      'customer:store:address:address_id': number;
      'customer:store:address:address2': string;
      'customer:store:address:city_id': number;
      'customer:store:address:district': string;
      'customer:store:address:last_update': string;
      'customer:store:address:phone': string;
      'customer:store:address:postal_code': string;
      'customer:store:manager_staff:active': boolean;
      'customer:store:manager_staff:address_id': number;
      'customer:store:manager_staff:email': string;
      'customer:store:manager_staff:first_name': string;
      'customer:store:manager_staff:last_name': string;
      'customer:store:manager_staff:last_update': string;
      'customer:store:manager_staff:password': string;
      'customer:store:manager_staff:picture': Buffer;
      'customer:store:manager_staff:staff_id': number;
      'customer:store:manager_staff:store_id': number;
      'customer:store:manager_staff:username': string;
      'rental:customer:address:address': string;
      'rental:customer:address:address_id': number;
      'rental:customer:address:address2': string;
      'rental:customer:address:city_id': number;
      'rental:customer:address:district': string;
      'rental:customer:address:last_update': string;
      'rental:customer:address:phone': string;
      'rental:customer:address:postal_code': string;
      'rental:customer:store:address_id': number;
      'rental:customer:store:last_update': string;
      'rental:customer:store:manager_staff_id': number;
      'rental:customer:store:store_id': number;
      'rental:inventory:film:description': string;
      'rental:inventory:film:film_id': number;
      'rental:inventory:film:language_id': number;
      'rental:inventory:film:last_update': string;
      'rental:inventory:film:length': number;
      'rental:inventory:film:original_language_id': number;
      'rental:inventory:film:rating': 'G' | 'NC-17' | 'PG' | 'PG-13' | 'R';
      'rental:inventory:film:release_year': number;
      'rental:inventory:film:rental_duration': number;
      'rental:inventory:film:rental_rate': number;
      'rental:inventory:film:replacement_cost': number;
      'rental:inventory:film:special_features': Array<string>;
      'rental:inventory:film:title': string;
      'rental:inventory:store:address_id': number;
      'rental:inventory:store:last_update': string;
      'rental:inventory:store:manager_staff_id': number;
      'rental:inventory:store:store_id': number;
      'rental:staff:address:address': string;
      'rental:staff:address:address_id': number;
      'rental:staff:address:address2': string;
      'rental:staff:address:city_id': number;
      'rental:staff:address:district': string;
      'rental:staff:address:last_update': string;
      'rental:staff:address:phone': string;
      'rental:staff:address:postal_code': string;
      'rental:staff:store_through_staff_manager_staff_id:address_id': number;
      'rental:staff:store_through_staff_manager_staff_id:last_update': string;
      'rental:staff:store_through_staff_manager_staff_id:manager_staff_id': number;
      'rental:staff:store_through_staff_manager_staff_id:store_id': number;
      'rental:staff:store_through_store_id:address_id': number;
      'rental:staff:store_through_store_id:last_update': string;
      'rental:staff:store_through_store_id:manager_staff_id': number;
      'rental:staff:store_through_store_id:store_id': number;
      'staff:address:city:city': string;
      'staff:address:city:city_id': number;
      'staff:address:city:country_id': number;
      'staff:address:city:last_update': string;
      'staff:store_through_staff_manager_staff_id:address:address': string;
      'staff:store_through_staff_manager_staff_id:address:address_id': number;
      'staff:store_through_staff_manager_staff_id:address:address2': string;
      'staff:store_through_staff_manager_staff_id:address:city_id': number;
      'staff:store_through_staff_manager_staff_id:address:district': string;
      'staff:store_through_staff_manager_staff_id:address:last_update': string;
      'staff:store_through_staff_manager_staff_id:address:phone': string;
      'staff:store_through_staff_manager_staff_id:address:postal_code': string;
      'staff:store_through_store_id:address:address': string;
      'staff:store_through_store_id:address:address_id': number;
      'staff:store_through_store_id:address:address2': string;
      'staff:store_through_store_id:address:city_id': number;
      'staff:store_through_store_id:address:district': string;
      'staff:store_through_store_id:address:last_update': string;
      'staff:store_through_store_id:address:phone': string;
      'staff:store_through_store_id:address:postal_code': string;
      'staff:store_through_store_id:manager_staff:active': boolean;
      'staff:store_through_store_id:manager_staff:address_id': number;
      'staff:store_through_store_id:manager_staff:email': string;
      'staff:store_through_store_id:manager_staff:first_name': string;
      'staff:store_through_store_id:manager_staff:last_name': string;
      'staff:store_through_store_id:manager_staff:last_update': string;
      'staff:store_through_store_id:manager_staff:password': string;
      'staff:store_through_store_id:manager_staff:picture': Buffer;
      'staff:store_through_store_id:manager_staff:staff_id': number;
      'staff:store_through_store_id:manager_staff:store_id': number;
      'staff:store_through_store_id:manager_staff:username': string;
    };
  };
  'regions': {
    plain: {
      'capital': string;
      'code': string;
      'id': number;
      'name': string;
    };
    nested: {};
    flat: {};
  };
  'rental': {
    plain: {
      'customer_id': number;
      'inventory_id': number;
      'last_update': string;
      'rental_date': string;
      'rental_id': number;
      'return_date': string;
      'staff_id': number;
    };
    nested: {
      'customer': Schema['customer']['plain'] & Schema['customer']['nested'];
      'inventory': Schema['inventory']['plain'] & Schema['inventory']['nested'];
      'staff': Schema['staff']['plain'] & Schema['staff']['nested'];
    };
    flat: {
      'customer:active': number;
      'customer:activebool': boolean;
      'customer:address_id': number;
      'customer:create_date': string;
      'customer:customer_id': number;
      'customer:email': string;
      'customer:first_name': string;
      'customer:last_name': string;
      'customer:last_update': string;
      'customer:store_id': number;
      'inventory:film_id': number;
      'inventory:inventory_id': number;
      'inventory:last_update': string;
      'inventory:store_id': number;
      'staff:active': boolean;
      'staff:address_id': number;
      'staff:email': string;
      'staff:first_name': string;
      'staff:last_name': string;
      'staff:last_update': string;
      'staff:password': string;
      'staff:picture': Buffer;
      'staff:staff_id': number;
      'staff:store_id': number;
      'staff:username': string;
      'customer:address:address': string;
      'customer:address:address_id': number;
      'customer:address:address2': string;
      'customer:address:city_id': number;
      'customer:address:district': string;
      'customer:address:last_update': string;
      'customer:address:phone': string;
      'customer:address:postal_code': string;
      'customer:store:address_id': number;
      'customer:store:last_update': string;
      'customer:store:manager_staff_id': number;
      'customer:store:store_id': number;
      'inventory:film:description': string;
      'inventory:film:film_id': number;
      'inventory:film:language_id': number;
      'inventory:film:last_update': string;
      'inventory:film:length': number;
      'inventory:film:original_language_id': number;
      'inventory:film:rating': 'G' | 'NC-17' | 'PG' | 'PG-13' | 'R';
      'inventory:film:release_year': number;
      'inventory:film:rental_duration': number;
      'inventory:film:rental_rate': number;
      'inventory:film:replacement_cost': number;
      'inventory:film:special_features': Array<string>;
      'inventory:film:title': string;
      'inventory:store:address_id': number;
      'inventory:store:last_update': string;
      'inventory:store:manager_staff_id': number;
      'inventory:store:store_id': number;
      'staff:address:address': string;
      'staff:address:address_id': number;
      'staff:address:address2': string;
      'staff:address:city_id': number;
      'staff:address:district': string;
      'staff:address:last_update': string;
      'staff:address:phone': string;
      'staff:address:postal_code': string;
      'staff:store_through_staff_manager_staff_id:address_id': number;
      'staff:store_through_staff_manager_staff_id:last_update': string;
      'staff:store_through_staff_manager_staff_id:manager_staff_id': number;
      'staff:store_through_staff_manager_staff_id:store_id': number;
      'staff:store_through_store_id:address_id': number;
      'staff:store_through_store_id:last_update': string;
      'staff:store_through_store_id:manager_staff_id': number;
      'staff:store_through_store_id:store_id': number;
      'customer:address:city:city': string;
      'customer:address:city:city_id': number;
      'customer:address:city:country_id': number;
      'customer:address:city:last_update': string;
      'customer:store:address:address': string;
      'customer:store:address:address_id': number;
      'customer:store:address:address2': string;
      'customer:store:address:city_id': number;
      'customer:store:address:district': string;
      'customer:store:address:last_update': string;
      'customer:store:address:phone': string;
      'customer:store:address:postal_code': string;
      'customer:store:manager_staff:active': boolean;
      'customer:store:manager_staff:address_id': number;
      'customer:store:manager_staff:email': string;
      'customer:store:manager_staff:first_name': string;
      'customer:store:manager_staff:last_name': string;
      'customer:store:manager_staff:last_update': string;
      'customer:store:manager_staff:password': string;
      'customer:store:manager_staff:picture': Buffer;
      'customer:store:manager_staff:staff_id': number;
      'customer:store:manager_staff:store_id': number;
      'customer:store:manager_staff:username': string;
      'inventory:film:language:language_id': number;
      'inventory:film:language:last_update': string;
      'inventory:film:language:name': string;
      'inventory:film:original_language:language_id': number;
      'inventory:film:original_language:last_update': string;
      'inventory:film:original_language:name': string;
      'inventory:store:address:address': string;
      'inventory:store:address:address_id': number;
      'inventory:store:address:address2': string;
      'inventory:store:address:city_id': number;
      'inventory:store:address:district': string;
      'inventory:store:address:last_update': string;
      'inventory:store:address:phone': string;
      'inventory:store:address:postal_code': string;
      'inventory:store:manager_staff:active': boolean;
      'inventory:store:manager_staff:address_id': number;
      'inventory:store:manager_staff:email': string;
      'inventory:store:manager_staff:first_name': string;
      'inventory:store:manager_staff:last_name': string;
      'inventory:store:manager_staff:last_update': string;
      'inventory:store:manager_staff:password': string;
      'inventory:store:manager_staff:picture': Buffer;
      'inventory:store:manager_staff:staff_id': number;
      'inventory:store:manager_staff:store_id': number;
      'inventory:store:manager_staff:username': string;
      'staff:address:city:city': string;
      'staff:address:city:city_id': number;
      'staff:address:city:country_id': number;
      'staff:address:city:last_update': string;
      'staff:store_through_staff_manager_staff_id:address:address': string;
      'staff:store_through_staff_manager_staff_id:address:address_id': number;
      'staff:store_through_staff_manager_staff_id:address:address2': string;
      'staff:store_through_staff_manager_staff_id:address:city_id': number;
      'staff:store_through_staff_manager_staff_id:address:district': string;
      'staff:store_through_staff_manager_staff_id:address:last_update': string;
      'staff:store_through_staff_manager_staff_id:address:phone': string;
      'staff:store_through_staff_manager_staff_id:address:postal_code': string;
      'staff:store_through_store_id:address:address': string;
      'staff:store_through_store_id:address:address_id': number;
      'staff:store_through_store_id:address:address2': string;
      'staff:store_through_store_id:address:city_id': number;
      'staff:store_through_store_id:address:district': string;
      'staff:store_through_store_id:address:last_update': string;
      'staff:store_through_store_id:address:phone': string;
      'staff:store_through_store_id:address:postal_code': string;
      'staff:store_through_store_id:manager_staff:active': boolean;
      'staff:store_through_store_id:manager_staff:address_id': number;
      'staff:store_through_store_id:manager_staff:email': string;
      'staff:store_through_store_id:manager_staff:first_name': string;
      'staff:store_through_store_id:manager_staff:last_name': string;
      'staff:store_through_store_id:manager_staff:last_update': string;
      'staff:store_through_store_id:manager_staff:password': string;
      'staff:store_through_store_id:manager_staff:picture': Buffer;
      'staff:store_through_store_id:manager_staff:staff_id': number;
      'staff:store_through_store_id:manager_staff:store_id': number;
      'staff:store_through_store_id:manager_staff:username': string;
    };
  };
  'staff': {
    plain: {
      'active': boolean;
      'address_id': number;
      'email': string;
      'first_name': string;
      'last_name': string;
      'last_update': string;
      'password': string;
      'picture': Buffer;
      'staff_id': number;
      'store_id': number;
      'username': string;
    };
    nested: {
      'address': Schema['address']['plain'] & Schema['address']['nested'];
      'store_through_staff_manager_staff_id': Schema['store']['plain'] & Schema['store']['nested'];
      'store_through_store_id': Schema['store']['plain'] & Schema['store']['nested'];
    };
    flat: {
      'address:address': string;
      'address:address_id': number;
      'address:address2': string;
      'address:city_id': number;
      'address:district': string;
      'address:last_update': string;
      'address:phone': string;
      'address:postal_code': string;
      'store_through_staff_manager_staff_id:address_id': number;
      'store_through_staff_manager_staff_id:last_update': string;
      'store_through_staff_manager_staff_id:manager_staff_id': number;
      'store_through_staff_manager_staff_id:store_id': number;
      'store_through_store_id:address_id': number;
      'store_through_store_id:last_update': string;
      'store_through_store_id:manager_staff_id': number;
      'store_through_store_id:store_id': number;
      'address:city:city': string;
      'address:city:city_id': number;
      'address:city:country_id': number;
      'address:city:last_update': string;
      'store_through_staff_manager_staff_id:address:address': string;
      'store_through_staff_manager_staff_id:address:address_id': number;
      'store_through_staff_manager_staff_id:address:address2': string;
      'store_through_staff_manager_staff_id:address:city_id': number;
      'store_through_staff_manager_staff_id:address:district': string;
      'store_through_staff_manager_staff_id:address:last_update': string;
      'store_through_staff_manager_staff_id:address:phone': string;
      'store_through_staff_manager_staff_id:address:postal_code': string;
      'store_through_store_id:address:address': string;
      'store_through_store_id:address:address_id': number;
      'store_through_store_id:address:address2': string;
      'store_through_store_id:address:city_id': number;
      'store_through_store_id:address:district': string;
      'store_through_store_id:address:last_update': string;
      'store_through_store_id:address:phone': string;
      'store_through_store_id:address:postal_code': string;
      'store_through_store_id:manager_staff:active': boolean;
      'store_through_store_id:manager_staff:address_id': number;
      'store_through_store_id:manager_staff:email': string;
      'store_through_store_id:manager_staff:first_name': string;
      'store_through_store_id:manager_staff:last_name': string;
      'store_through_store_id:manager_staff:last_update': string;
      'store_through_store_id:manager_staff:password': string;
      'store_through_store_id:manager_staff:picture': Buffer;
      'store_through_store_id:manager_staff:staff_id': number;
      'store_through_store_id:manager_staff:store_id': number;
      'store_through_store_id:manager_staff:username': string;
      'address:city:country:country': string;
      'address:city:country:country_id': number;
      'address:city:country:last_update': string;
      'store_through_staff_manager_staff_id:address:city:city': string;
      'store_through_staff_manager_staff_id:address:city:city_id': number;
      'store_through_staff_manager_staff_id:address:city:country_id': number;
      'store_through_staff_manager_staff_id:address:city:last_update': string;
      'store_through_store_id:address:city:city': string;
      'store_through_store_id:address:city:city_id': number;
      'store_through_store_id:address:city:country_id': number;
      'store_through_store_id:address:city:last_update': string;
      'store_through_store_id:manager_staff:address:address': string;
      'store_through_store_id:manager_staff:address:address_id': number;
      'store_through_store_id:manager_staff:address:address2': string;
      'store_through_store_id:manager_staff:address:city_id': number;
      'store_through_store_id:manager_staff:address:district': string;
      'store_through_store_id:manager_staff:address:last_update': string;
      'store_through_store_id:manager_staff:address:phone': string;
      'store_through_store_id:manager_staff:address:postal_code': string;
      'store_through_store_id:manager_staff:store_through_store_id:address_id': number;
      'store_through_store_id:manager_staff:store_through_store_id:last_update': string;
      'store_through_store_id:manager_staff:store_through_store_id:manager_staff_id': number;
      'store_through_store_id:manager_staff:store_through_store_id:store_id': number;
    };
  };
  'store': {
    plain: {
      'address_id': number;
      'last_update': string;
      'manager_staff_id': number;
      'store_id': number;
    };
    nested: {
      'address': Schema['address']['plain'] & Schema['address']['nested'];
      'manager_staff': Schema['staff']['plain'] & Schema['staff']['nested'];
    };
    flat: {
      'address:address': string;
      'address:address_id': number;
      'address:address2': string;
      'address:city_id': number;
      'address:district': string;
      'address:last_update': string;
      'address:phone': string;
      'address:postal_code': string;
      'manager_staff:active': boolean;
      'manager_staff:address_id': number;
      'manager_staff:email': string;
      'manager_staff:first_name': string;
      'manager_staff:last_name': string;
      'manager_staff:last_update': string;
      'manager_staff:password': string;
      'manager_staff:picture': Buffer;
      'manager_staff:staff_id': number;
      'manager_staff:store_id': number;
      'manager_staff:username': string;
      'address:city:city': string;
      'address:city:city_id': number;
      'address:city:country_id': number;
      'address:city:last_update': string;
      'manager_staff:address:address': string;
      'manager_staff:address:address_id': number;
      'manager_staff:address:address2': string;
      'manager_staff:address:city_id': number;
      'manager_staff:address:district': string;
      'manager_staff:address:last_update': string;
      'manager_staff:address:phone': string;
      'manager_staff:address:postal_code': string;
      'manager_staff:store_through_store_id:address_id': number;
      'manager_staff:store_through_store_id:last_update': string;
      'manager_staff:store_through_store_id:manager_staff_id': number;
      'manager_staff:store_through_store_id:store_id': number;
      'address:city:country:country': string;
      'address:city:country:country_id': number;
      'address:city:country:last_update': string;
      'manager_staff:address:city:city': string;
      'manager_staff:address:city:city_id': number;
      'manager_staff:address:city:country_id': number;
      'manager_staff:address:city:last_update': string;
      'manager_staff:store_through_store_id:address:address': string;
      'manager_staff:store_through_store_id:address:address_id': number;
      'manager_staff:store_through_store_id:address:address2': string;
      'manager_staff:store_through_store_id:address:city_id': number;
      'manager_staff:store_through_store_id:address:district': string;
      'manager_staff:store_through_store_id:address:last_update': string;
      'manager_staff:store_through_store_id:address:phone': string;
      'manager_staff:store_through_store_id:address:postal_code': string;
      'manager_staff:store_through_store_id:manager_staff:active': boolean;
      'manager_staff:store_through_store_id:manager_staff:address_id': number;
      'manager_staff:store_through_store_id:manager_staff:email': string;
      'manager_staff:store_through_store_id:manager_staff:first_name': string;
      'manager_staff:store_through_store_id:manager_staff:last_name': string;
      'manager_staff:store_through_store_id:manager_staff:last_update': string;
      'manager_staff:store_through_store_id:manager_staff:password': string;
      'manager_staff:store_through_store_id:manager_staff:picture': Buffer;
      'manager_staff:store_through_store_id:manager_staff:staff_id': number;
      'manager_staff:store_through_store_id:manager_staff:store_id': number;
      'manager_staff:store_through_store_id:manager_staff:username': string;
    };
  };
  'towns': {
    plain: {
      'article': string;
      'code': string;
      'department': string;
      'id': number;
      'name': string;
    };
    nested: {
      'department_through_department': Schema['departments']['plain'] & Schema['departments']['nested'];
    };
    flat: {
      'department_through_department:capital': string;
      'department_through_department:code': string;
      'department_through_department:id': number;
      'department_through_department:name': string;
      'department_through_department:region': string;
      'department_through_department:region_through_region:capital': string;
      'department_through_department:region_through_region:code': string;
      'department_through_department:region_through_region:id': number;
      'department_through_department:region_through_region:name': string;
    };
  };
};
