import { Model } from 'sequelize/types/model';
import { ModelStatic, Sequelize } from 'sequelize';

import { ForeignKeyReference } from './types';

export default class RelationFactory {
  static build(
    tableName: string,
    foreignReferences: Partial<ForeignKeyReference>[],
    uniqueFields: string[],
    sequelize: Sequelize,
  ): void {
    const model = sequelize.model(tableName);

    if (RelationFactory.isJunctionTable(model)) {
      RelationFactory.buildForJunctionTable(
        foreignReferences as [Partial<ForeignKeyReference>, Partial<ForeignKeyReference>],
        model,
        sequelize,
      );
    } else {
      RelationFactory.buildOtherRelations(foreignReferences, model, uniqueFields, sequelize);
    }
  }

  private static buildOtherRelations(
    foreignReferences: Partial<ForeignKeyReference>[],
    model: ModelStatic<Model>,
    uniqueFields: string[],
    sequelize: Sequelize,
  ): void {
    foreignReferences.forEach(({ columnName, referencedTableName, referencedColumnName }) => {
      const referencedModel = sequelize.model(referencedTableName);

      model.belongsTo(referencedModel, {
        foreignKey: columnName,
        targetKey: referencedColumnName,
      });

      if (uniqueFields.includes(columnName)) {
        referencedModel.hasOne(model, {
          foreignKey: columnName,
          sourceKey: referencedColumnName,
        });
      } else {
        referencedModel.hasMany(model, {
          foreignKey: columnName,
          sourceKey: referencedColumnName,
        });
      }
    });
  }

  private static buildForJunctionTable(
    foreignReferences: [Partial<ForeignKeyReference>, Partial<ForeignKeyReference>],
    model: ModelStatic<Model>,
    sequelize: Sequelize,
  ): void {
    const [
      { referencedTableName: tableA, columnName: columnA, referencedColumnName: referencedColumnA },
      { referencedTableName: tableB, columnName: columnB, referencedColumnName: referencedColumnB },
    ] = foreignReferences;

    const modelA = sequelize.model(tableA);
    const modelB = sequelize.model(tableB);

    modelA.belongsToMany(modelB, {
      through: model.name,
      foreignKey: columnA,
      otherKey: columnB,
    });
    modelB.belongsToMany(modelA, {
      through: model.name,
      foreignKey: columnB,
      otherKey: columnA,
    });
    model.belongsTo(modelA, { foreignKey: columnA, targetKey: referencedColumnA });
    model.belongsTo(modelB, { foreignKey: columnB, targetKey: referencedColumnB });
  }

  private static isJunctionTable(model: ModelStatic<Model>): boolean {
    const modelAttributes = model.getAttributes();
    // remove autogenerated field to keep the belongsToMany behavior
    const modelAttributesDefinition = Object.values(modelAttributes).filter(
      ({ _autoGenerated }) => !_autoGenerated,
    );
    if (modelAttributesDefinition.length !== 2) return false;

    return !modelAttributesDefinition.some(({ primaryKey }) => !primaryKey);
  }
}
