import type { DataSource, FieldSchema, RecordData } from '@forestadmin/datasource-toolkit';

import BaseFintechCollection from './base';
import { daysAgo } from '../dates';

export default class AmlAlertsCollection extends BaseFintechCollection {
  private static schema: Record<string, FieldSchema> = {
    id: {
      type: 'Column',
      columnType: 'Number',
      isPrimaryKey: true,
    },
    customer_id: {
      type: 'Column',
      columnType: 'Number',
    },
    alert_type: {
      type: 'Column',
      columnType: 'Enum',
      enumValues: [
        'UNUSUAL_VOLUME',
        'SUSPICIOUS_PATTERN',
        'SANCTIONS_MATCH',
        'HIGH_RISK_COUNTRY',
        'RAPID_MOVEMENT',
        'STRUCTURING',
      ],
    },
    severity: {
      type: 'Column',
      columnType: 'String',
    },
    status: {
      type: 'Column',
      columnType: 'String',
    },
    triggered_at: {
      type: 'Column',
      columnType: 'Date',
    },
    resolution_notes: {
      type: 'Column',
      columnType: 'String',
    },
    sar_reference: {
      type: 'Column',
      columnType: 'String',
    },
    resolved_at: {
      type: 'Column',
      columnType: 'Date',
    },
  };

  protected override records: RecordData[] = [
    {
      id: 1,
      customer_id: 83,
      alert_type: 'RAPID_MOVEMENT',
      severity: 'MEDIUM',
      status: 'IN_REVIEW',
      triggered_at: daysAgo(7),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 2,
      customer_id: 146,
      alert_type: 'RAPID_MOVEMENT',
      severity: 'CRITICAL',
      status: 'ESCALATED',
      triggered_at: daysAgo(21),
      resolution_notes: 'Escalated to MLRO.',
      sar_reference: 'SAR-2026-00001',
      resolved_at: daysAgo(17),
    },
    {
      id: 3,
      customer_id: 26,
      alert_type: 'SANCTIONS_MATCH',
      severity: 'CRITICAL',
      status: 'OPEN',
      triggered_at: daysAgo(120),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 4,
      customer_id: 19,
      alert_type: 'UNUSUAL_VOLUME',
      severity: 'LOW',
      status: 'CLEARED',
      triggered_at: daysAgo(93),
      resolution_notes: 'Cleared after review.',
      sar_reference: null,
      resolved_at: daysAgo(77),
    },
    {
      id: 5,
      customer_id: 1,
      alert_type: 'SANCTIONS_MATCH',
      severity: 'CRITICAL',
      status: 'OPEN',
      triggered_at: daysAgo(121),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 6,
      customer_id: 126,
      alert_type: 'SUSPICIOUS_PATTERN',
      severity: 'MEDIUM',
      status: 'CLEARED',
      triggered_at: daysAgo(112),
      resolution_notes: 'False positive — name overlap.',
      sar_reference: null,
      resolved_at: daysAgo(38),
    },
    {
      id: 7,
      customer_id: 136,
      alert_type: 'SANCTIONS_MATCH',
      severity: 'CRITICAL',
      status: 'CLEARED',
      triggered_at: daysAgo(16),
      resolution_notes: 'Cleared after review.',
      sar_reference: null,
      resolved_at: daysAgo(8),
    },
    {
      id: 8,
      customer_id: 65,
      alert_type: 'UNUSUAL_VOLUME',
      severity: 'HIGH',
      status: 'ESCALATED',
      triggered_at: daysAgo(10),
      resolution_notes: 'Under enhanced due diligence.',
      sar_reference: null,
      resolved_at: daysAgo(3),
    },
    {
      id: 9,
      customer_id: 95,
      alert_type: 'RAPID_MOVEMENT',
      severity: 'CRITICAL',
      status: 'OPEN',
      triggered_at: daysAgo(70),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 10,
      customer_id: 65,
      alert_type: 'UNUSUAL_VOLUME',
      severity: 'LOW',
      status: 'OPEN',
      triggered_at: daysAgo(119),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 11,
      customer_id: 95,
      alert_type: 'STRUCTURING',
      severity: 'MEDIUM',
      status: 'ESCALATED',
      triggered_at: daysAgo(104),
      resolution_notes: 'Under enhanced due diligence.',
      sar_reference: 'SAR-2026-00002',
      resolved_at: daysAgo(27),
    },
    {
      id: 12,
      customer_id: 136,
      alert_type: 'SANCTIONS_MATCH',
      severity: 'CRITICAL',
      status: 'IN_REVIEW',
      triggered_at: daysAgo(71),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 13,
      customer_id: 7,
      alert_type: 'HIGH_RISK_COUNTRY',
      severity: 'HIGH',
      status: 'OPEN',
      triggered_at: daysAgo(40),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 14,
      customer_id: 85,
      alert_type: 'RAPID_MOVEMENT',
      severity: 'MEDIUM',
      status: 'ESCALATED',
      triggered_at: daysAgo(88),
      resolution_notes: 'Escalated to MLRO.',
      sar_reference: 'SAR-2026-00003',
      resolved_at: daysAgo(82),
    },
    {
      id: 15,
      customer_id: 75,
      alert_type: 'STRUCTURING',
      severity: 'MEDIUM',
      status: 'OPEN',
      triggered_at: daysAgo(85),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 16,
      customer_id: 95,
      alert_type: 'UNUSUAL_VOLUME',
      severity: 'HIGH',
      status: 'OPEN',
      triggered_at: daysAgo(42),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 17,
      customer_id: 34,
      alert_type: 'RAPID_MOVEMENT',
      severity: 'LOW',
      status: 'OPEN',
      triggered_at: daysAgo(47),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 18,
      customer_id: 7,
      alert_type: 'SUSPICIOUS_PATTERN',
      severity: 'CRITICAL',
      status: 'OPEN',
      triggered_at: daysAgo(49),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 19,
      customer_id: 90,
      alert_type: 'HIGH_RISK_COUNTRY',
      severity: 'HIGH',
      status: 'CLEARED',
      triggered_at: daysAgo(61),
      resolution_notes: 'False positive — name overlap.',
      sar_reference: null,
      resolved_at: daysAgo(24),
    },
    {
      id: 20,
      customer_id: 5,
      alert_type: 'STRUCTURING',
      severity: 'MEDIUM',
      status: 'CLEARED',
      triggered_at: daysAgo(37),
      resolution_notes: 'Cleared after review.',
      sar_reference: null,
      resolved_at: daysAgo(34),
    },
    {
      id: 21,
      customer_id: 124,
      alert_type: 'UNUSUAL_VOLUME',
      severity: 'HIGH',
      status: 'OPEN',
      triggered_at: daysAgo(53),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 22,
      customer_id: 95,
      alert_type: 'HIGH_RISK_COUNTRY',
      severity: 'CRITICAL',
      status: 'OPEN',
      triggered_at: daysAgo(94),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 23,
      customer_id: 132,
      alert_type: 'SANCTIONS_MATCH',
      severity: 'CRITICAL',
      status: 'SAR_FILED',
      triggered_at: daysAgo(70),
      resolution_notes: 'SAR SAR-2026-00004 filed with the FIU.',
      sar_reference: 'SAR-2026-00004',
      resolved_at: daysAgo(7),
    },
    {
      id: 24,
      customer_id: 150,
      alert_type: 'SANCTIONS_MATCH',
      severity: 'CRITICAL',
      status: 'IN_REVIEW',
      triggered_at: daysAgo(48),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 25,
      customer_id: 102,
      alert_type: 'HIGH_RISK_COUNTRY',
      severity: 'HIGH',
      status: 'SAR_FILED',
      triggered_at: daysAgo(11),
      resolution_notes: 'SAR SAR-2026-00005 filed with the FIU.',
      sar_reference: 'SAR-2026-00005',
      resolved_at: daysAgo(2),
    },
    {
      id: 26,
      customer_id: 75,
      alert_type: 'SANCTIONS_MATCH',
      severity: 'CRITICAL',
      status: 'IN_REVIEW',
      triggered_at: daysAgo(60),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 27,
      customer_id: 113,
      alert_type: 'RAPID_MOVEMENT',
      severity: 'CRITICAL',
      status: 'OPEN',
      triggered_at: daysAgo(39),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 28,
      customer_id: 125,
      alert_type: 'SANCTIONS_MATCH',
      severity: 'CRITICAL',
      status: 'ESCALATED',
      triggered_at: daysAgo(72),
      resolution_notes: 'Escalated to MLRO.',
      sar_reference: 'SAR-2026-00006',
      resolved_at: daysAgo(17),
    },
    {
      id: 29,
      customer_id: 136,
      alert_type: 'SANCTIONS_MATCH',
      severity: 'HIGH',
      status: 'OPEN',
      triggered_at: daysAgo(116),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 30,
      customer_id: 63,
      alert_type: 'UNUSUAL_VOLUME',
      severity: 'HIGH',
      status: 'OPEN',
      triggered_at: daysAgo(105),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 31,
      customer_id: 106,
      alert_type: 'RAPID_MOVEMENT',
      severity: 'MEDIUM',
      status: 'CLEARED',
      triggered_at: daysAgo(14),
      resolution_notes: 'Cleared after review.',
      sar_reference: null,
      resolved_at: daysAgo(4),
    },
    {
      id: 32,
      customer_id: 106,
      alert_type: 'STRUCTURING',
      severity: 'MEDIUM',
      status: 'CLEARED',
      triggered_at: daysAgo(12),
      resolution_notes: 'Cleared after review.',
      sar_reference: null,
      resolved_at: daysAgo(6),
    },
    {
      id: 33,
      customer_id: 133,
      alert_type: 'HIGH_RISK_COUNTRY',
      severity: 'LOW',
      status: 'OPEN',
      triggered_at: daysAgo(52),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 34,
      customer_id: 75,
      alert_type: 'RAPID_MOVEMENT',
      severity: 'HIGH',
      status: 'IN_REVIEW',
      triggered_at: daysAgo(126),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 35,
      customer_id: 79,
      alert_type: 'HIGH_RISK_COUNTRY',
      severity: 'HIGH',
      status: 'CLEARED',
      triggered_at: daysAgo(62),
      resolution_notes: 'False positive — name overlap.',
      sar_reference: null,
      resolved_at: daysAgo(47),
    },
    {
      id: 36,
      customer_id: 36,
      alert_type: 'SUSPICIOUS_PATTERN',
      severity: 'CRITICAL',
      status: 'OPEN',
      triggered_at: daysAgo(31),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 37,
      customer_id: 1,
      alert_type: 'SUSPICIOUS_PATTERN',
      severity: 'HIGH',
      status: 'CLEARED',
      triggered_at: daysAgo(3),
      resolution_notes: 'Cleared after review.',
      sar_reference: null,
      resolved_at: daysAgo(1),
    },
    {
      id: 38,
      customer_id: 125,
      alert_type: 'SANCTIONS_MATCH',
      severity: 'CRITICAL',
      status: 'IN_REVIEW',
      triggered_at: daysAgo(87),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 39,
      customer_id: 40,
      alert_type: 'RAPID_MOVEMENT',
      severity: 'HIGH',
      status: 'CLEARED',
      triggered_at: daysAgo(31),
      resolution_notes: 'Cleared after review.',
      sar_reference: null,
      resolved_at: daysAgo(29),
    },
    {
      id: 40,
      customer_id: 120,
      alert_type: 'SANCTIONS_MATCH',
      severity: 'CRITICAL',
      status: 'SAR_FILED',
      triggered_at: daysAgo(5),
      resolution_notes: 'SAR SAR-2026-00007 filed with the FIU.',
      sar_reference: 'SAR-2026-00007',
      resolved_at: daysAgo(4),
    },
    {
      id: 41,
      customer_id: 40,
      alert_type: 'HIGH_RISK_COUNTRY',
      severity: 'HIGH',
      status: 'OPEN',
      triggered_at: daysAgo(115),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 42,
      customer_id: 126,
      alert_type: 'HIGH_RISK_COUNTRY',
      severity: 'MEDIUM',
      status: 'CLEARED',
      triggered_at: daysAgo(33),
      resolution_notes: 'False positive — name overlap.',
      sar_reference: null,
      resolved_at: daysAgo(23),
    },
    {
      id: 43,
      customer_id: 40,
      alert_type: 'SANCTIONS_MATCH',
      severity: 'CRITICAL',
      status: 'SAR_FILED',
      triggered_at: daysAgo(87),
      resolution_notes: 'SAR SAR-2026-00008 filed with the FIU.',
      sar_reference: 'SAR-2026-00008',
      resolved_at: daysAgo(74),
    },
    {
      id: 44,
      customer_id: 149,
      alert_type: 'STRUCTURING',
      severity: 'MEDIUM',
      status: 'ESCALATED',
      triggered_at: daysAgo(58),
      resolution_notes: 'Escalated to MLRO.',
      sar_reference: null,
      resolved_at: daysAgo(19),
    },
    {
      id: 45,
      customer_id: 146,
      alert_type: 'SANCTIONS_MATCH',
      severity: 'CRITICAL',
      status: 'IN_REVIEW',
      triggered_at: daysAgo(2),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 46,
      customer_id: 89,
      alert_type: 'SUSPICIOUS_PATTERN',
      severity: 'HIGH',
      status: 'SAR_FILED',
      triggered_at: daysAgo(122),
      resolution_notes: 'SAR SAR-2026-00009 filed with the FIU.',
      sar_reference: 'SAR-2026-00009',
      resolved_at: daysAgo(76),
    },
    {
      id: 47,
      customer_id: 150,
      alert_type: 'STRUCTURING',
      severity: 'LOW',
      status: 'CLEARED',
      triggered_at: daysAgo(38),
      resolution_notes: 'Cleared after review.',
      sar_reference: null,
      resolved_at: daysAgo(30),
    },
    {
      id: 48,
      customer_id: 11,
      alert_type: 'RAPID_MOVEMENT',
      severity: 'CRITICAL',
      status: 'OPEN',
      triggered_at: daysAgo(123),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 49,
      customer_id: 31,
      alert_type: 'RAPID_MOVEMENT',
      severity: 'HIGH',
      status: 'IN_REVIEW',
      triggered_at: daysAgo(32),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 50,
      customer_id: 51,
      alert_type: 'SUSPICIOUS_PATTERN',
      severity: 'HIGH',
      status: 'IN_REVIEW',
      triggered_at: daysAgo(122),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 51,
      customer_id: 132,
      alert_type: 'HIGH_RISK_COUNTRY',
      severity: 'CRITICAL',
      status: 'IN_REVIEW',
      triggered_at: daysAgo(63),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 52,
      customer_id: 136,
      alert_type: 'SANCTIONS_MATCH',
      severity: 'CRITICAL',
      status: 'IN_REVIEW',
      triggered_at: daysAgo(35),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 53,
      customer_id: 120,
      alert_type: 'STRUCTURING',
      severity: 'HIGH',
      status: 'ESCALATED',
      triggered_at: daysAgo(118),
      resolution_notes: 'Escalated to MLRO.',
      sar_reference: 'SAR-2026-00010',
      resolved_at: daysAgo(107),
    },
    {
      id: 54,
      customer_id: 79,
      alert_type: 'RAPID_MOVEMENT',
      severity: 'CRITICAL',
      status: 'OPEN',
      triggered_at: daysAgo(60),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 55,
      customer_id: 132,
      alert_type: 'SANCTIONS_MATCH',
      severity: 'HIGH',
      status: 'SAR_FILED',
      triggered_at: daysAgo(94),
      resolution_notes: 'SAR SAR-2026-00011 filed with the FIU.',
      sar_reference: 'SAR-2026-00011',
      resolved_at: daysAgo(67),
    },
    {
      id: 56,
      customer_id: 51,
      alert_type: 'SANCTIONS_MATCH',
      severity: 'CRITICAL',
      status: 'OPEN',
      triggered_at: daysAgo(102),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 57,
      customer_id: 144,
      alert_type: 'UNUSUAL_VOLUME',
      severity: 'HIGH',
      status: 'CLEARED',
      triggered_at: daysAgo(126),
      resolution_notes: 'False positive — name overlap.',
      sar_reference: null,
      resolved_at: daysAgo(22),
    },
    {
      id: 58,
      customer_id: 90,
      alert_type: 'HIGH_RISK_COUNTRY',
      severity: 'CRITICAL',
      status: 'OPEN',
      triggered_at: daysAgo(83),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 59,
      customer_id: 23,
      alert_type: 'HIGH_RISK_COUNTRY',
      severity: 'HIGH',
      status: 'OPEN',
      triggered_at: daysAgo(56),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 60,
      customer_id: 79,
      alert_type: 'STRUCTURING',
      severity: 'HIGH',
      status: 'IN_REVIEW',
      triggered_at: daysAgo(108),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 61,
      customer_id: 120,
      alert_type: 'SANCTIONS_MATCH',
      severity: 'HIGH',
      status: 'OPEN',
      triggered_at: daysAgo(130),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 62,
      customer_id: 146,
      alert_type: 'SANCTIONS_MATCH',
      severity: 'CRITICAL',
      status: 'SAR_FILED',
      triggered_at: daysAgo(20),
      resolution_notes: 'SAR SAR-2026-00012 filed with the FIU.',
      sar_reference: 'SAR-2026-00012',
      resolved_at: daysAgo(6),
    },
    {
      id: 63,
      customer_id: 145,
      alert_type: 'HIGH_RISK_COUNTRY',
      severity: 'MEDIUM',
      status: 'IN_REVIEW',
      triggered_at: daysAgo(67),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 64,
      customer_id: 35,
      alert_type: 'SUSPICIOUS_PATTERN',
      severity: 'HIGH',
      status: 'CLEARED',
      triggered_at: daysAgo(19),
      resolution_notes: 'Cleared after review.',
      sar_reference: null,
      resolved_at: daysAgo(15),
    },
    {
      id: 65,
      customer_id: 83,
      alert_type: 'UNUSUAL_VOLUME',
      severity: 'MEDIUM',
      status: 'OPEN',
      triggered_at: daysAgo(8),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 66,
      customer_id: 16,
      alert_type: 'UNUSUAL_VOLUME',
      severity: 'MEDIUM',
      status: 'IN_REVIEW',
      triggered_at: daysAgo(20),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 67,
      customer_id: 79,
      alert_type: 'STRUCTURING',
      severity: 'HIGH',
      status: 'IN_REVIEW',
      triggered_at: daysAgo(19),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 68,
      customer_id: 146,
      alert_type: 'SANCTIONS_MATCH',
      severity: 'HIGH',
      status: 'OPEN',
      triggered_at: daysAgo(63),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 69,
      customer_id: 25,
      alert_type: 'HIGH_RISK_COUNTRY',
      severity: 'MEDIUM',
      status: 'OPEN',
      triggered_at: daysAgo(74),
      resolution_notes: null,
      sar_reference: null,
      resolved_at: null,
    },
    {
      id: 70,
      customer_id: 5,
      alert_type: 'UNUSUAL_VOLUME',
      severity: 'HIGH',
      status: 'CLEARED',
      triggered_at: daysAgo(87),
      resolution_notes: 'Cleared after review.',
      sar_reference: null,
      resolved_at: daysAgo(1),
    },
  ];

  constructor(datasource: DataSource) {
    super(datasource, 'aml_alerts', AmlAlertsCollection.schema);
  }
}
