import type { DataSource, FieldSchema, RecordData } from '@forestadmin/datasource-toolkit';

import BaseFintechCollection from './base';
import { dayOnlyAgo, daysAgo } from '../dates';

export default class CardsCollection extends BaseFintechCollection {
  private static schema: Record<string, FieldSchema> = {
    id: {
      type: 'Column',
      columnType: 'Number',
      isPrimaryKey: true,
    },
    customer_id: {
      type: 'Column',
      columnType: 'Number',
    },
    card_type: {
      type: 'Column',
      columnType: 'Enum',
      enumValues: ['VIRTUAL', 'PHYSICAL'],
    },
    status: {
      type: 'Column',
      columnType: 'Enum',
      enumValues: ['ACTIVE', 'BLOCKED', 'CANCELLED', 'PENDING', 'EXPIRED'],
    },
    last_four_digits: {
      type: 'Column',
      columnType: 'String',
    },
    issued_at: {
      type: 'Column',
      columnType: 'Date',
    },
    expires_at: {
      type: 'Column',
      columnType: 'Dateonly',
    },
    blocked_reason: {
      type: 'Column',
      columnType: 'String',
    },
    blocked_at: {
      type: 'Column',
      columnType: 'Date',
    },
  };

  protected override records: RecordData[] = [
    {
      id: 1,
      customer_id: 1,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '0686',
      issued_at: daysAgo(31),
      expires_at: dayOnlyAgo(-1068),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 2,
      customer_id: 1,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '7182',
      issued_at: daysAgo(138),
      expires_at: dayOnlyAgo(-961),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 3,
      customer_id: 1,
      card_type: 'PHYSICAL',
      status: 'BLOCKED',
      last_four_digits: '9775',
      issued_at: daysAgo(181),
      expires_at: dayOnlyAgo(-772),
      blocked_reason: 'Customer request',
      blocked_at: daysAgo(98),
    },
    {
      id: 4,
      customer_id: 2,
      card_type: 'VIRTUAL',
      status: 'BLOCKED',
      last_four_digits: '8764',
      issued_at: daysAgo(249),
      expires_at: dayOnlyAgo(-691),
      blocked_reason: 'Compliance hold',
      blocked_at: daysAgo(228),
    },
    {
      id: 5,
      customer_id: 2,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '9777',
      issued_at: daysAgo(211),
      expires_at: dayOnlyAgo(-731),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 6,
      customer_id: 3,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '8373',
      issued_at: daysAgo(203),
      expires_at: dayOnlyAgo(-1156),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 7,
      customer_id: 4,
      card_type: 'PHYSICAL',
      status: 'PENDING',
      last_four_digits: '6031',
      issued_at: daysAgo(242),
      expires_at: dayOnlyAgo(-964),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 8,
      customer_id: 5,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '6783',
      issued_at: daysAgo(111),
      expires_at: dayOnlyAgo(-725),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 9,
      customer_id: 6,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '8590',
      issued_at: daysAgo(101),
      expires_at: dayOnlyAgo(-1338),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 10,
      customer_id: 6,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '3566',
      issued_at: daysAgo(109),
      expires_at: dayOnlyAgo(-1114),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 11,
      customer_id: 6,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '4417',
      issued_at: daysAgo(373),
      expires_at: dayOnlyAgo(-1046),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 12,
      customer_id: 7,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '8287',
      issued_at: daysAgo(199),
      expires_at: dayOnlyAgo(-366),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 13,
      customer_id: 7,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '6034',
      issued_at: daysAgo(244),
      expires_at: dayOnlyAgo(-722),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 14,
      customer_id: 7,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '2004',
      issued_at: daysAgo(291),
      expires_at: dayOnlyAgo(-742),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 15,
      customer_id: 8,
      card_type: 'PHYSICAL',
      status: 'EXPIRED',
      last_four_digits: '3011',
      issued_at: daysAgo(20),
      expires_at: dayOnlyAgo(-639),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 16,
      customer_id: 8,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '8127',
      issued_at: daysAgo(232),
      expires_at: dayOnlyAgo(-376),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 17,
      customer_id: 9,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '7717',
      issued_at: daysAgo(45),
      expires_at: dayOnlyAgo(-642),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 18,
      customer_id: 9,
      card_type: 'VIRTUAL',
      status: 'EXPIRED',
      last_four_digits: '8955',
      issued_at: daysAgo(106),
      expires_at: dayOnlyAgo(-1055),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 19,
      customer_id: 9,
      card_type: 'VIRTUAL',
      status: 'PENDING',
      last_four_digits: '8177',
      issued_at: daysAgo(185),
      expires_at: dayOnlyAgo(-1026),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 20,
      customer_id: 10,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '5151',
      issued_at: daysAgo(67),
      expires_at: dayOnlyAgo(-1182),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 21,
      customer_id: 10,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '0299',
      issued_at: daysAgo(365),
      expires_at: dayOnlyAgo(-1031),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 22,
      customer_id: 10,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '0705',
      issued_at: daysAgo(129),
      expires_at: dayOnlyAgo(-940),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 23,
      customer_id: 11,
      card_type: 'VIRTUAL',
      status: 'EXPIRED',
      last_four_digits: '3481',
      issued_at: daysAgo(239),
      expires_at: dayOnlyAgo(-1395),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 24,
      customer_id: 11,
      card_type: 'PHYSICAL',
      status: 'EXPIRED',
      last_four_digits: '7375',
      issued_at: daysAgo(306),
      expires_at: dayOnlyAgo(-1101),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 25,
      customer_id: 12,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '4886',
      issued_at: daysAgo(308),
      expires_at: dayOnlyAgo(-1196),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 26,
      customer_id: 12,
      card_type: 'PHYSICAL',
      status: 'BLOCKED',
      last_four_digits: '6312',
      issued_at: daysAgo(224),
      expires_at: dayOnlyAgo(-870),
      blocked_reason: 'Reported lost',
      blocked_at: daysAgo(58),
    },
    {
      id: 27,
      customer_id: 13,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '7266',
      issued_at: daysAgo(241),
      expires_at: dayOnlyAgo(-737),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 28,
      customer_id: 13,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '4311',
      issued_at: daysAgo(158),
      expires_at: dayOnlyAgo(-827),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 29,
      customer_id: 13,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '5250',
      issued_at: daysAgo(73),
      expires_at: dayOnlyAgo(-886),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 30,
      customer_id: 14,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '8518',
      issued_at: daysAgo(298),
      expires_at: dayOnlyAgo(-1118),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 31,
      customer_id: 14,
      card_type: 'PHYSICAL',
      status: 'PENDING',
      last_four_digits: '6639',
      issued_at: daysAgo(246),
      expires_at: dayOnlyAgo(-639),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 32,
      customer_id: 14,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '4665',
      issued_at: daysAgo(134),
      expires_at: dayOnlyAgo(-899),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 33,
      customer_id: 15,
      card_type: 'VIRTUAL',
      status: 'PENDING',
      last_four_digits: '3890',
      issued_at: daysAgo(40),
      expires_at: dayOnlyAgo(-1268),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 34,
      customer_id: 15,
      card_type: 'PHYSICAL',
      status: 'BLOCKED',
      last_four_digits: '5246',
      issued_at: daysAgo(24),
      expires_at: dayOnlyAgo(-1113),
      blocked_reason: 'Reported lost',
      blocked_at: daysAgo(18),
    },
    {
      id: 35,
      customer_id: 15,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '6598',
      issued_at: daysAgo(368),
      expires_at: dayOnlyAgo(-874),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 36,
      customer_id: 16,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '7626',
      issued_at: daysAgo(198),
      expires_at: dayOnlyAgo(-573),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 37,
      customer_id: 16,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '1839',
      issued_at: daysAgo(306),
      expires_at: dayOnlyAgo(-1050),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 38,
      customer_id: 17,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '0710',
      issued_at: daysAgo(164),
      expires_at: dayOnlyAgo(-412),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 39,
      customer_id: 18,
      card_type: 'VIRTUAL',
      status: 'BLOCKED',
      last_four_digits: '5817',
      issued_at: daysAgo(369),
      expires_at: dayOnlyAgo(-1360),
      blocked_reason: 'Customer request',
      blocked_at: daysAgo(191),
    },
    {
      id: 40,
      customer_id: 18,
      card_type: 'PHYSICAL',
      status: 'PENDING',
      last_four_digits: '4774',
      issued_at: daysAgo(328),
      expires_at: dayOnlyAgo(-1329),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 41,
      customer_id: 18,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '3390',
      issued_at: daysAgo(228),
      expires_at: dayOnlyAgo(-1459),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 42,
      customer_id: 19,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '9118',
      issued_at: daysAgo(123),
      expires_at: dayOnlyAgo(-1297),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 43,
      customer_id: 19,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '1271',
      issued_at: daysAgo(186),
      expires_at: dayOnlyAgo(-1177),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 44,
      customer_id: 19,
      card_type: 'VIRTUAL',
      status: 'CANCELLED',
      last_four_digits: '7635',
      issued_at: daysAgo(195),
      expires_at: dayOnlyAgo(-666),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 45,
      customer_id: 20,
      card_type: 'VIRTUAL',
      status: 'CANCELLED',
      last_four_digits: '3937',
      issued_at: daysAgo(264),
      expires_at: dayOnlyAgo(-772),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 46,
      customer_id: 20,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '5838',
      issued_at: daysAgo(241),
      expires_at: dayOnlyAgo(-768),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 47,
      customer_id: 20,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '5265',
      issued_at: daysAgo(98),
      expires_at: dayOnlyAgo(-1394),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 48,
      customer_id: 21,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '1341',
      issued_at: daysAgo(310),
      expires_at: dayOnlyAgo(-633),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 49,
      customer_id: 21,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '5442',
      issued_at: daysAgo(302),
      expires_at: dayOnlyAgo(-708),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 50,
      customer_id: 22,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '9522',
      issued_at: daysAgo(135),
      expires_at: dayOnlyAgo(-504),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 51,
      customer_id: 22,
      card_type: 'VIRTUAL',
      status: 'BLOCKED',
      last_four_digits: '6052',
      issued_at: daysAgo(196),
      expires_at: dayOnlyAgo(-1034),
      blocked_reason: 'Suspected fraud',
      blocked_at: daysAgo(52),
    },
    {
      id: 52,
      customer_id: 23,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '4231',
      issued_at: daysAgo(353),
      expires_at: dayOnlyAgo(-861),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 53,
      customer_id: 23,
      card_type: 'PHYSICAL',
      status: 'BLOCKED',
      last_four_digits: '4155',
      issued_at: daysAgo(375),
      expires_at: dayOnlyAgo(-741),
      blocked_reason: 'Reported lost',
      blocked_at: daysAgo(157),
    },
    {
      id: 54,
      customer_id: 23,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '4082',
      issued_at: daysAgo(222),
      expires_at: dayOnlyAgo(-678),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 55,
      customer_id: 24,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '2099',
      issued_at: daysAgo(129),
      expires_at: dayOnlyAgo(-427),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 56,
      customer_id: 24,
      card_type: 'PHYSICAL',
      status: 'PENDING',
      last_four_digits: '9865',
      issued_at: daysAgo(108),
      expires_at: dayOnlyAgo(-1156),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 57,
      customer_id: 24,
      card_type: 'VIRTUAL',
      status: 'PENDING',
      last_four_digits: '4009',
      issued_at: daysAgo(136),
      expires_at: dayOnlyAgo(-455),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 58,
      customer_id: 25,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '1600',
      issued_at: daysAgo(315),
      expires_at: dayOnlyAgo(-897),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 59,
      customer_id: 25,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '6430',
      issued_at: daysAgo(258),
      expires_at: dayOnlyAgo(-909),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 60,
      customer_id: 25,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '1681',
      issued_at: daysAgo(133),
      expires_at: dayOnlyAgo(-879),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 61,
      customer_id: 26,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '4429',
      issued_at: daysAgo(352),
      expires_at: dayOnlyAgo(-1428),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 62,
      customer_id: 27,
      card_type: 'VIRTUAL',
      status: 'BLOCKED',
      last_four_digits: '6503',
      issued_at: daysAgo(332),
      expires_at: dayOnlyAgo(-1458),
      blocked_reason: 'Suspected fraud',
      blocked_at: daysAgo(215),
    },
    {
      id: 63,
      customer_id: 28,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '3736',
      issued_at: daysAgo(329),
      expires_at: dayOnlyAgo(-865),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 64,
      customer_id: 28,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '0231',
      issued_at: daysAgo(115),
      expires_at: dayOnlyAgo(-1366),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 65,
      customer_id: 28,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '7676',
      issued_at: daysAgo(157),
      expires_at: dayOnlyAgo(-694),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 66,
      customer_id: 29,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '5333',
      issued_at: daysAgo(171),
      expires_at: dayOnlyAgo(-592),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 67,
      customer_id: 29,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '1269',
      issued_at: daysAgo(72),
      expires_at: dayOnlyAgo(-478),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 68,
      customer_id: 29,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '6188',
      issued_at: daysAgo(283),
      expires_at: dayOnlyAgo(-819),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 69,
      customer_id: 30,
      card_type: 'VIRTUAL',
      status: 'BLOCKED',
      last_four_digits: '2556',
      issued_at: daysAgo(81),
      expires_at: dayOnlyAgo(-498),
      blocked_reason: 'Reported lost',
      blocked_at: daysAgo(47),
    },
    {
      id: 70,
      customer_id: 30,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '5962',
      issued_at: daysAgo(276),
      expires_at: dayOnlyAgo(-637),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 71,
      customer_id: 30,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '2369',
      issued_at: daysAgo(347),
      expires_at: dayOnlyAgo(-1239),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 72,
      customer_id: 31,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '4171',
      issued_at: daysAgo(340),
      expires_at: dayOnlyAgo(-1112),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 73,
      customer_id: 31,
      card_type: 'VIRTUAL',
      status: 'BLOCKED',
      last_four_digits: '7558',
      issued_at: daysAgo(147),
      expires_at: dayOnlyAgo(-670),
      blocked_reason: 'Reported lost',
      blocked_at: daysAgo(88),
    },
    {
      id: 74,
      customer_id: 32,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '6045',
      issued_at: daysAgo(154),
      expires_at: dayOnlyAgo(-723),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 75,
      customer_id: 32,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '5138',
      issued_at: daysAgo(179),
      expires_at: dayOnlyAgo(-892),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 76,
      customer_id: 32,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '0253',
      issued_at: daysAgo(279),
      expires_at: dayOnlyAgo(-1154),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 77,
      customer_id: 33,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '0689',
      issued_at: daysAgo(26),
      expires_at: dayOnlyAgo(-451),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 78,
      customer_id: 33,
      card_type: 'VIRTUAL',
      status: 'PENDING',
      last_four_digits: '9132',
      issued_at: daysAgo(358),
      expires_at: dayOnlyAgo(-674),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 79,
      customer_id: 33,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '3912',
      issued_at: daysAgo(83),
      expires_at: dayOnlyAgo(-954),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 80,
      customer_id: 34,
      card_type: 'VIRTUAL',
      status: 'BLOCKED',
      last_four_digits: '9471',
      issued_at: daysAgo(140),
      expires_at: dayOnlyAgo(-847),
      blocked_reason: 'Suspected fraud',
      blocked_at: daysAgo(131),
    },
    {
      id: 81,
      customer_id: 34,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '8463',
      issued_at: daysAgo(29),
      expires_at: dayOnlyAgo(-1037),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 82,
      customer_id: 34,
      card_type: 'PHYSICAL',
      status: 'PENDING',
      last_four_digits: '6327',
      issued_at: daysAgo(318),
      expires_at: dayOnlyAgo(-800),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 83,
      customer_id: 35,
      card_type: 'PHYSICAL',
      status: 'EXPIRED',
      last_four_digits: '0998',
      issued_at: daysAgo(174),
      expires_at: dayOnlyAgo(-1047),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 84,
      customer_id: 36,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '5411',
      issued_at: daysAgo(231),
      expires_at: dayOnlyAgo(-1229),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 85,
      customer_id: 37,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '7447',
      issued_at: daysAgo(377),
      expires_at: dayOnlyAgo(-1093),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 86,
      customer_id: 37,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '6950',
      issued_at: daysAgo(57),
      expires_at: dayOnlyAgo(-1334),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 87,
      customer_id: 38,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '8366',
      issued_at: daysAgo(316),
      expires_at: dayOnlyAgo(-1167),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 88,
      customer_id: 39,
      card_type: 'VIRTUAL',
      status: 'BLOCKED',
      last_four_digits: '4201',
      issued_at: daysAgo(46),
      expires_at: dayOnlyAgo(-605),
      blocked_reason: 'Customer request',
      blocked_at: daysAgo(8),
    },
    {
      id: 89,
      customer_id: 39,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '5880',
      issued_at: daysAgo(352),
      expires_at: dayOnlyAgo(-1087),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 90,
      customer_id: 39,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '9652',
      issued_at: daysAgo(54),
      expires_at: dayOnlyAgo(-878),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 91,
      customer_id: 40,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '7960',
      issued_at: daysAgo(169),
      expires_at: dayOnlyAgo(-948),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 92,
      customer_id: 41,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '8935',
      issued_at: daysAgo(117),
      expires_at: dayOnlyAgo(-529),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 93,
      customer_id: 41,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '3456',
      issued_at: daysAgo(201),
      expires_at: dayOnlyAgo(-679),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 94,
      customer_id: 42,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '5421',
      issued_at: daysAgo(217),
      expires_at: dayOnlyAgo(-973),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 95,
      customer_id: 43,
      card_type: 'VIRTUAL',
      status: 'CANCELLED',
      last_four_digits: '3412',
      issued_at: daysAgo(88),
      expires_at: dayOnlyAgo(-1405),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 96,
      customer_id: 44,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '6298',
      issued_at: daysAgo(193),
      expires_at: dayOnlyAgo(-801),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 97,
      customer_id: 44,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '2414',
      issued_at: daysAgo(308),
      expires_at: dayOnlyAgo(-564),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 98,
      customer_id: 44,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '5032',
      issued_at: daysAgo(274),
      expires_at: dayOnlyAgo(-798),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 99,
      customer_id: 45,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '0420',
      issued_at: daysAgo(201),
      expires_at: dayOnlyAgo(-696),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 100,
      customer_id: 45,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '4777',
      issued_at: daysAgo(176),
      expires_at: dayOnlyAgo(-1108),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 101,
      customer_id: 46,
      card_type: 'VIRTUAL',
      status: 'BLOCKED',
      last_four_digits: '0269',
      issued_at: daysAgo(48),
      expires_at: dayOnlyAgo(-1353),
      blocked_reason: 'Reported lost',
      blocked_at: daysAgo(41),
    },
    {
      id: 102,
      customer_id: 46,
      card_type: 'PHYSICAL',
      status: 'PENDING',
      last_four_digits: '8850',
      issued_at: daysAgo(157),
      expires_at: dayOnlyAgo(-1050),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 103,
      customer_id: 47,
      card_type: 'VIRTUAL',
      status: 'PENDING',
      last_four_digits: '7519',
      issued_at: daysAgo(236),
      expires_at: dayOnlyAgo(-823),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 104,
      customer_id: 48,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '0136',
      issued_at: daysAgo(141),
      expires_at: dayOnlyAgo(-804),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 105,
      customer_id: 48,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '4512',
      issued_at: daysAgo(321),
      expires_at: dayOnlyAgo(-375),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 106,
      customer_id: 48,
      card_type: 'PHYSICAL',
      status: 'BLOCKED',
      last_four_digits: '2466',
      issued_at: daysAgo(338),
      expires_at: dayOnlyAgo(-1290),
      blocked_reason: 'Compliance hold',
      blocked_at: daysAgo(325),
    },
    {
      id: 107,
      customer_id: 49,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '2998',
      issued_at: daysAgo(131),
      expires_at: dayOnlyAgo(-387),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 108,
      customer_id: 49,
      card_type: 'VIRTUAL',
      status: 'BLOCKED',
      last_four_digits: '8144',
      issued_at: daysAgo(137),
      expires_at: dayOnlyAgo(-1407),
      blocked_reason: 'Reported lost',
      blocked_at: daysAgo(106),
    },
    {
      id: 109,
      customer_id: 49,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '5036',
      issued_at: daysAgo(141),
      expires_at: dayOnlyAgo(-417),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 110,
      customer_id: 50,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '0927',
      issued_at: daysAgo(348),
      expires_at: dayOnlyAgo(-992),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 111,
      customer_id: 50,
      card_type: 'PHYSICAL',
      status: 'EXPIRED',
      last_four_digits: '4817',
      issued_at: daysAgo(163),
      expires_at: dayOnlyAgo(-623),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 112,
      customer_id: 51,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '2028',
      issued_at: daysAgo(261),
      expires_at: dayOnlyAgo(-591),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 113,
      customer_id: 52,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '3000',
      issued_at: daysAgo(324),
      expires_at: dayOnlyAgo(-785),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 114,
      customer_id: 52,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '2967',
      issued_at: daysAgo(145),
      expires_at: dayOnlyAgo(-631),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 115,
      customer_id: 52,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '2480',
      issued_at: daysAgo(343),
      expires_at: dayOnlyAgo(-408),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 116,
      customer_id: 53,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '6574',
      issued_at: daysAgo(235),
      expires_at: dayOnlyAgo(-1355),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 117,
      customer_id: 53,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '5547',
      issued_at: daysAgo(316),
      expires_at: dayOnlyAgo(-1200),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 118,
      customer_id: 53,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '2410',
      issued_at: daysAgo(220),
      expires_at: dayOnlyAgo(-886),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 119,
      customer_id: 54,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '5015',
      issued_at: daysAgo(188),
      expires_at: dayOnlyAgo(-675),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 120,
      customer_id: 55,
      card_type: 'VIRTUAL',
      status: 'PENDING',
      last_four_digits: '9089',
      issued_at: daysAgo(259),
      expires_at: dayOnlyAgo(-763),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 121,
      customer_id: 56,
      card_type: 'PHYSICAL',
      status: 'BLOCKED',
      last_four_digits: '9639',
      issued_at: daysAgo(210),
      expires_at: dayOnlyAgo(-984),
      blocked_reason: 'Suspected fraud',
      blocked_at: daysAgo(74),
    },
    {
      id: 122,
      customer_id: 56,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '0574',
      issued_at: daysAgo(268),
      expires_at: dayOnlyAgo(-1288),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 123,
      customer_id: 56,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '3419',
      issued_at: daysAgo(45),
      expires_at: dayOnlyAgo(-1130),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 124,
      customer_id: 57,
      card_type: 'PHYSICAL',
      status: 'PENDING',
      last_four_digits: '8227',
      issued_at: daysAgo(378),
      expires_at: dayOnlyAgo(-590),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 125,
      customer_id: 58,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '7536',
      issued_at: daysAgo(253),
      expires_at: dayOnlyAgo(-521),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 126,
      customer_id: 59,
      card_type: 'VIRTUAL',
      status: 'PENDING',
      last_four_digits: '4472',
      issued_at: daysAgo(20),
      expires_at: dayOnlyAgo(-949),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 127,
      customer_id: 59,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '4965',
      issued_at: daysAgo(180),
      expires_at: dayOnlyAgo(-1191),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 128,
      customer_id: 59,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '0342',
      issued_at: daysAgo(140),
      expires_at: dayOnlyAgo(-463),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 129,
      customer_id: 60,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '6643',
      issued_at: daysAgo(93),
      expires_at: dayOnlyAgo(-1385),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 130,
      customer_id: 60,
      card_type: 'VIRTUAL',
      status: 'PENDING',
      last_four_digits: '7090',
      issued_at: daysAgo(334),
      expires_at: dayOnlyAgo(-706),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 131,
      customer_id: 61,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '5713',
      issued_at: daysAgo(229),
      expires_at: dayOnlyAgo(-1335),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 132,
      customer_id: 61,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '7695',
      issued_at: daysAgo(335),
      expires_at: dayOnlyAgo(-1390),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 133,
      customer_id: 61,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '7151',
      issued_at: daysAgo(40),
      expires_at: dayOnlyAgo(-1045),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 134,
      customer_id: 62,
      card_type: 'VIRTUAL',
      status: 'EXPIRED',
      last_four_digits: '6320',
      issued_at: daysAgo(24),
      expires_at: dayOnlyAgo(-1023),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 135,
      customer_id: 62,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '3372',
      issued_at: daysAgo(97),
      expires_at: dayOnlyAgo(-1120),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 136,
      customer_id: 63,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '8822',
      issued_at: daysAgo(215),
      expires_at: dayOnlyAgo(-1161),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 137,
      customer_id: 63,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '1913',
      issued_at: daysAgo(77),
      expires_at: dayOnlyAgo(-480),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 138,
      customer_id: 63,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '3588',
      issued_at: daysAgo(114),
      expires_at: dayOnlyAgo(-1413),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 139,
      customer_id: 64,
      card_type: 'VIRTUAL',
      status: 'PENDING',
      last_four_digits: '5102',
      issued_at: daysAgo(265),
      expires_at: dayOnlyAgo(-1393),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 140,
      customer_id: 64,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '9151',
      issued_at: daysAgo(184),
      expires_at: dayOnlyAgo(-1156),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 141,
      customer_id: 64,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '1488',
      issued_at: daysAgo(192),
      expires_at: dayOnlyAgo(-1226),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 142,
      customer_id: 65,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '9198',
      issued_at: daysAgo(94),
      expires_at: dayOnlyAgo(-464),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 143,
      customer_id: 65,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '6023',
      issued_at: daysAgo(251),
      expires_at: dayOnlyAgo(-1140),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 144,
      customer_id: 66,
      card_type: 'VIRTUAL',
      status: 'PENDING',
      last_four_digits: '9031',
      issued_at: daysAgo(247),
      expires_at: dayOnlyAgo(-1414),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 145,
      customer_id: 66,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '5815',
      issued_at: daysAgo(132),
      expires_at: dayOnlyAgo(-684),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 146,
      customer_id: 67,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '9374',
      issued_at: daysAgo(108),
      expires_at: dayOnlyAgo(-684),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 147,
      customer_id: 67,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '7732',
      issued_at: daysAgo(78),
      expires_at: dayOnlyAgo(-461),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 148,
      customer_id: 67,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '8124',
      issued_at: daysAgo(37),
      expires_at: dayOnlyAgo(-585),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 149,
      customer_id: 68,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '3531',
      issued_at: daysAgo(248),
      expires_at: dayOnlyAgo(-723),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 150,
      customer_id: 68,
      card_type: 'VIRTUAL',
      status: 'EXPIRED',
      last_four_digits: '6764',
      issued_at: daysAgo(119),
      expires_at: dayOnlyAgo(-1033),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 151,
      customer_id: 68,
      card_type: 'VIRTUAL',
      status: 'EXPIRED',
      last_four_digits: '2780',
      issued_at: daysAgo(339),
      expires_at: dayOnlyAgo(-469),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 152,
      customer_id: 69,
      card_type: 'VIRTUAL',
      status: 'EXPIRED',
      last_four_digits: '5694',
      issued_at: daysAgo(319),
      expires_at: dayOnlyAgo(-1316),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 153,
      customer_id: 69,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '3895',
      issued_at: daysAgo(370),
      expires_at: dayOnlyAgo(-752),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 154,
      customer_id: 69,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '2891',
      issued_at: daysAgo(229),
      expires_at: dayOnlyAgo(-385),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 155,
      customer_id: 70,
      card_type: 'PHYSICAL',
      status: 'BLOCKED',
      last_four_digits: '3126',
      issued_at: daysAgo(150),
      expires_at: dayOnlyAgo(-482),
      blocked_reason: 'Suspected fraud',
      blocked_at: daysAgo(83),
    },
    {
      id: 156,
      customer_id: 71,
      card_type: 'PHYSICAL',
      status: 'BLOCKED',
      last_four_digits: '7912',
      issued_at: daysAgo(362),
      expires_at: dayOnlyAgo(-548),
      blocked_reason: 'Reported lost',
      blocked_at: daysAgo(169),
    },
    {
      id: 157,
      customer_id: 72,
      card_type: 'PHYSICAL',
      status: 'EXPIRED',
      last_four_digits: '3368',
      issued_at: daysAgo(224),
      expires_at: dayOnlyAgo(-1188),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 158,
      customer_id: 73,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '6812',
      issued_at: daysAgo(347),
      expires_at: dayOnlyAgo(-523),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 159,
      customer_id: 73,
      card_type: 'VIRTUAL',
      status: 'BLOCKED',
      last_four_digits: '1447',
      issued_at: daysAgo(308),
      expires_at: dayOnlyAgo(-913),
      blocked_reason: 'Compliance hold',
      blocked_at: daysAgo(272),
    },
    {
      id: 160,
      customer_id: 73,
      card_type: 'PHYSICAL',
      status: 'PENDING',
      last_four_digits: '2810',
      issued_at: daysAgo(339),
      expires_at: dayOnlyAgo(-1039),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 161,
      customer_id: 74,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '9095',
      issued_at: daysAgo(379),
      expires_at: dayOnlyAgo(-860),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 162,
      customer_id: 74,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '1907',
      issued_at: daysAgo(122),
      expires_at: dayOnlyAgo(-1255),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 163,
      customer_id: 75,
      card_type: 'VIRTUAL',
      status: 'CANCELLED',
      last_four_digits: '7485',
      issued_at: daysAgo(202),
      expires_at: dayOnlyAgo(-1340),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 164,
      customer_id: 75,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '6682',
      issued_at: daysAgo(45),
      expires_at: dayOnlyAgo(-1125),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 165,
      customer_id: 76,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '9719',
      issued_at: daysAgo(256),
      expires_at: dayOnlyAgo(-1287),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 166,
      customer_id: 77,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '6125',
      issued_at: daysAgo(77),
      expires_at: dayOnlyAgo(-791),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 167,
      customer_id: 78,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '0965',
      issued_at: daysAgo(191),
      expires_at: dayOnlyAgo(-774),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 168,
      customer_id: 78,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '9064',
      issued_at: daysAgo(241),
      expires_at: dayOnlyAgo(-786),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 169,
      customer_id: 79,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '4926',
      issued_at: daysAgo(195),
      expires_at: dayOnlyAgo(-1005),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 170,
      customer_id: 79,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '4690',
      issued_at: daysAgo(354),
      expires_at: dayOnlyAgo(-1415),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 171,
      customer_id: 79,
      card_type: 'PHYSICAL',
      status: 'BLOCKED',
      last_four_digits: '7495',
      issued_at: daysAgo(212),
      expires_at: dayOnlyAgo(-597),
      blocked_reason: 'Suspected fraud',
      blocked_at: daysAgo(41),
    },
    {
      id: 172,
      customer_id: 80,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '7067',
      issued_at: daysAgo(196),
      expires_at: dayOnlyAgo(-888),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 173,
      customer_id: 80,
      card_type: 'VIRTUAL',
      status: 'BLOCKED',
      last_four_digits: '6488',
      issued_at: daysAgo(315),
      expires_at: dayOnlyAgo(-465),
      blocked_reason: 'Compliance hold',
      blocked_at: daysAgo(276),
    },
    {
      id: 174,
      customer_id: 81,
      card_type: 'PHYSICAL',
      status: 'BLOCKED',
      last_four_digits: '7511',
      issued_at: daysAgo(376),
      expires_at: dayOnlyAgo(-1105),
      blocked_reason: 'Suspected fraud',
      blocked_at: daysAgo(201),
    },
    {
      id: 175,
      customer_id: 82,
      card_type: 'PHYSICAL',
      status: 'BLOCKED',
      last_four_digits: '4177',
      issued_at: daysAgo(356),
      expires_at: dayOnlyAgo(-885),
      blocked_reason: 'Customer request',
      blocked_at: daysAgo(112),
    },
    {
      id: 176,
      customer_id: 83,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '1862',
      issued_at: daysAgo(228),
      expires_at: dayOnlyAgo(-648),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 177,
      customer_id: 84,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '5727',
      issued_at: daysAgo(160),
      expires_at: dayOnlyAgo(-571),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 178,
      customer_id: 85,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '9758',
      issued_at: daysAgo(205),
      expires_at: dayOnlyAgo(-1334),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 179,
      customer_id: 85,
      card_type: 'VIRTUAL',
      status: 'PENDING',
      last_four_digits: '5360',
      issued_at: daysAgo(49),
      expires_at: dayOnlyAgo(-1009),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 180,
      customer_id: 86,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '1673',
      issued_at: daysAgo(229),
      expires_at: dayOnlyAgo(-1337),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 181,
      customer_id: 86,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '8652',
      issued_at: daysAgo(213),
      expires_at: dayOnlyAgo(-566),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 182,
      customer_id: 87,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '2515',
      issued_at: daysAgo(375),
      expires_at: dayOnlyAgo(-1234),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 183,
      customer_id: 87,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '5778',
      issued_at: daysAgo(198),
      expires_at: dayOnlyAgo(-863),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 184,
      customer_id: 88,
      card_type: 'PHYSICAL',
      status: 'PENDING',
      last_four_digits: '0834',
      issued_at: daysAgo(380),
      expires_at: dayOnlyAgo(-1156),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 185,
      customer_id: 89,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '2912',
      issued_at: daysAgo(332),
      expires_at: dayOnlyAgo(-1378),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 186,
      customer_id: 89,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '3534',
      issued_at: daysAgo(126),
      expires_at: dayOnlyAgo(-1051),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 187,
      customer_id: 89,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '3105',
      issued_at: daysAgo(375),
      expires_at: dayOnlyAgo(-1441),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 188,
      customer_id: 90,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '4319',
      issued_at: daysAgo(90),
      expires_at: dayOnlyAgo(-1174),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 189,
      customer_id: 90,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '8850',
      issued_at: daysAgo(234),
      expires_at: dayOnlyAgo(-884),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 190,
      customer_id: 91,
      card_type: 'PHYSICAL',
      status: 'BLOCKED',
      last_four_digits: '2517',
      issued_at: daysAgo(281),
      expires_at: dayOnlyAgo(-1131),
      blocked_reason: 'Customer request',
      blocked_at: daysAgo(125),
    },
    {
      id: 191,
      customer_id: 91,
      card_type: 'PHYSICAL',
      status: 'PENDING',
      last_four_digits: '3923',
      issued_at: daysAgo(214),
      expires_at: dayOnlyAgo(-564),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 192,
      customer_id: 92,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '6279',
      issued_at: daysAgo(40),
      expires_at: dayOnlyAgo(-589),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 193,
      customer_id: 92,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '4288',
      issued_at: daysAgo(268),
      expires_at: dayOnlyAgo(-499),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 194,
      customer_id: 92,
      card_type: 'VIRTUAL',
      status: 'PENDING',
      last_four_digits: '6028',
      issued_at: daysAgo(324),
      expires_at: dayOnlyAgo(-670),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 195,
      customer_id: 93,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '1876',
      issued_at: daysAgo(259),
      expires_at: dayOnlyAgo(-894),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 196,
      customer_id: 94,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '1513',
      issued_at: daysAgo(236),
      expires_at: dayOnlyAgo(-694),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 197,
      customer_id: 94,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '4070',
      issued_at: daysAgo(163),
      expires_at: dayOnlyAgo(-603),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 198,
      customer_id: 95,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '4962',
      issued_at: daysAgo(160),
      expires_at: dayOnlyAgo(-471),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 199,
      customer_id: 95,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '6383',
      issued_at: daysAgo(302),
      expires_at: dayOnlyAgo(-443),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 200,
      customer_id: 96,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '6108',
      issued_at: daysAgo(319),
      expires_at: dayOnlyAgo(-1372),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 201,
      customer_id: 96,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '0442',
      issued_at: daysAgo(134),
      expires_at: dayOnlyAgo(-481),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 202,
      customer_id: 96,
      card_type: 'VIRTUAL',
      status: 'CANCELLED',
      last_four_digits: '3091',
      issued_at: daysAgo(323),
      expires_at: dayOnlyAgo(-1063),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 203,
      customer_id: 97,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '4717',
      issued_at: daysAgo(108),
      expires_at: dayOnlyAgo(-905),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 204,
      customer_id: 98,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '3805',
      issued_at: daysAgo(200),
      expires_at: dayOnlyAgo(-788),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 205,
      customer_id: 98,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '5587',
      issued_at: daysAgo(231),
      expires_at: dayOnlyAgo(-1433),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 206,
      customer_id: 99,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '2402',
      issued_at: daysAgo(196),
      expires_at: dayOnlyAgo(-401),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 207,
      customer_id: 99,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '0310',
      issued_at: daysAgo(357),
      expires_at: dayOnlyAgo(-454),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 208,
      customer_id: 100,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '2755',
      issued_at: daysAgo(336),
      expires_at: dayOnlyAgo(-474),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 209,
      customer_id: 100,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '1524',
      issued_at: daysAgo(256),
      expires_at: dayOnlyAgo(-707),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 210,
      customer_id: 101,
      card_type: 'VIRTUAL',
      status: 'CANCELLED',
      last_four_digits: '6894',
      issued_at: daysAgo(64),
      expires_at: dayOnlyAgo(-1022),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 211,
      customer_id: 101,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '6627',
      issued_at: daysAgo(107),
      expires_at: dayOnlyAgo(-837),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 212,
      customer_id: 101,
      card_type: 'VIRTUAL',
      status: 'BLOCKED',
      last_four_digits: '3645',
      issued_at: daysAgo(251),
      expires_at: dayOnlyAgo(-1356),
      blocked_reason: 'Reported lost',
      blocked_at: daysAgo(16),
    },
    {
      id: 213,
      customer_id: 102,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '5052',
      issued_at: daysAgo(174),
      expires_at: dayOnlyAgo(-538),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 214,
      customer_id: 102,
      card_type: 'PHYSICAL',
      status: 'BLOCKED',
      last_four_digits: '8133',
      issued_at: daysAgo(318),
      expires_at: dayOnlyAgo(-747),
      blocked_reason: 'Reported lost',
      blocked_at: daysAgo(138),
    },
    {
      id: 215,
      customer_id: 103,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '9247',
      issued_at: daysAgo(41),
      expires_at: dayOnlyAgo(-561),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 216,
      customer_id: 103,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '8417',
      issued_at: daysAgo(290),
      expires_at: dayOnlyAgo(-1146),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 217,
      customer_id: 103,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '3840',
      issued_at: daysAgo(53),
      expires_at: dayOnlyAgo(-1150),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 218,
      customer_id: 104,
      card_type: 'VIRTUAL',
      status: 'PENDING',
      last_four_digits: '7589',
      issued_at: daysAgo(268),
      expires_at: dayOnlyAgo(-703),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 219,
      customer_id: 104,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '6579',
      issued_at: daysAgo(193),
      expires_at: dayOnlyAgo(-723),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 220,
      customer_id: 104,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '6274',
      issued_at: daysAgo(235),
      expires_at: dayOnlyAgo(-1117),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 221,
      customer_id: 105,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '2496',
      issued_at: daysAgo(51),
      expires_at: dayOnlyAgo(-1198),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 222,
      customer_id: 105,
      card_type: 'VIRTUAL',
      status: 'EXPIRED',
      last_four_digits: '5391',
      issued_at: daysAgo(220),
      expires_at: dayOnlyAgo(-1362),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 223,
      customer_id: 106,
      card_type: 'PHYSICAL',
      status: 'EXPIRED',
      last_four_digits: '6091',
      issued_at: daysAgo(101),
      expires_at: dayOnlyAgo(-1443),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 224,
      customer_id: 106,
      card_type: 'VIRTUAL',
      status: 'EXPIRED',
      last_four_digits: '2158',
      issued_at: daysAgo(231),
      expires_at: dayOnlyAgo(-1448),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 225,
      customer_id: 107,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '5088',
      issued_at: daysAgo(166),
      expires_at: dayOnlyAgo(-1059),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 226,
      customer_id: 107,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '0121',
      issued_at: daysAgo(89),
      expires_at: dayOnlyAgo(-485),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 227,
      customer_id: 108,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '5827',
      issued_at: daysAgo(329),
      expires_at: dayOnlyAgo(-977),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 228,
      customer_id: 108,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '3954',
      issued_at: daysAgo(127),
      expires_at: dayOnlyAgo(-534),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 229,
      customer_id: 109,
      card_type: 'VIRTUAL',
      status: 'BLOCKED',
      last_four_digits: '0242',
      issued_at: daysAgo(204),
      expires_at: dayOnlyAgo(-640),
      blocked_reason: 'Suspected fraud',
      blocked_at: daysAgo(21),
    },
    {
      id: 230,
      customer_id: 109,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '0245',
      issued_at: daysAgo(312),
      expires_at: dayOnlyAgo(-516),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 231,
      customer_id: 109,
      card_type: 'VIRTUAL',
      status: 'BLOCKED',
      last_four_digits: '1126',
      issued_at: daysAgo(81),
      expires_at: dayOnlyAgo(-432),
      blocked_reason: 'Compliance hold',
      blocked_at: daysAgo(64),
    },
    {
      id: 232,
      customer_id: 110,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '6290',
      issued_at: daysAgo(298),
      expires_at: dayOnlyAgo(-438),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 233,
      customer_id: 110,
      card_type: 'PHYSICAL',
      status: 'BLOCKED',
      last_four_digits: '6557',
      issued_at: daysAgo(295),
      expires_at: dayOnlyAgo(-1308),
      blocked_reason: 'Reported lost',
      blocked_at: daysAgo(58),
    },
    {
      id: 234,
      customer_id: 111,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '4496',
      issued_at: daysAgo(196),
      expires_at: dayOnlyAgo(-398),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 235,
      customer_id: 111,
      card_type: 'PHYSICAL',
      status: 'CANCELLED',
      last_four_digits: '5804',
      issued_at: daysAgo(266),
      expires_at: dayOnlyAgo(-1296),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 236,
      customer_id: 111,
      card_type: 'VIRTUAL',
      status: 'CANCELLED',
      last_four_digits: '9717',
      issued_at: daysAgo(51),
      expires_at: dayOnlyAgo(-680),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 237,
      customer_id: 112,
      card_type: 'PHYSICAL',
      status: 'PENDING',
      last_four_digits: '5170',
      issued_at: daysAgo(274),
      expires_at: dayOnlyAgo(-705),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 238,
      customer_id: 112,
      card_type: 'VIRTUAL',
      status: 'EXPIRED',
      last_four_digits: '7121',
      issued_at: daysAgo(194),
      expires_at: dayOnlyAgo(-914),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 239,
      customer_id: 113,
      card_type: 'PHYSICAL',
      status: 'PENDING',
      last_four_digits: '2203',
      issued_at: daysAgo(95),
      expires_at: dayOnlyAgo(-485),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 240,
      customer_id: 114,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '8453',
      issued_at: daysAgo(272),
      expires_at: dayOnlyAgo(-1272),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 241,
      customer_id: 115,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '5844',
      issued_at: daysAgo(215),
      expires_at: dayOnlyAgo(-681),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 242,
      customer_id: 115,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '1119',
      issued_at: daysAgo(147),
      expires_at: dayOnlyAgo(-596),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 243,
      customer_id: 116,
      card_type: 'VIRTUAL',
      status: 'PENDING',
      last_four_digits: '2584',
      issued_at: daysAgo(310),
      expires_at: dayOnlyAgo(-1257),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 244,
      customer_id: 116,
      card_type: 'VIRTUAL',
      status: 'BLOCKED',
      last_four_digits: '4922',
      issued_at: daysAgo(289),
      expires_at: dayOnlyAgo(-1178),
      blocked_reason: 'Customer request',
      blocked_at: daysAgo(177),
    },
    {
      id: 245,
      customer_id: 117,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '8147',
      issued_at: daysAgo(48),
      expires_at: dayOnlyAgo(-723),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 246,
      customer_id: 117,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '4982',
      issued_at: daysAgo(359),
      expires_at: dayOnlyAgo(-1375),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 247,
      customer_id: 118,
      card_type: 'VIRTUAL',
      status: 'PENDING',
      last_four_digits: '4824',
      issued_at: daysAgo(38),
      expires_at: dayOnlyAgo(-1246),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 248,
      customer_id: 119,
      card_type: 'VIRTUAL',
      status: 'PENDING',
      last_four_digits: '9489',
      issued_at: daysAgo(254),
      expires_at: dayOnlyAgo(-1046),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 249,
      customer_id: 120,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '7013',
      issued_at: daysAgo(169),
      expires_at: dayOnlyAgo(-542),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 250,
      customer_id: 120,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '5016',
      issued_at: daysAgo(37),
      expires_at: dayOnlyAgo(-811),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 251,
      customer_id: 121,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '8883',
      issued_at: daysAgo(199),
      expires_at: dayOnlyAgo(-493),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 252,
      customer_id: 122,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '9490',
      issued_at: daysAgo(373),
      expires_at: dayOnlyAgo(-461),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 253,
      customer_id: 122,
      card_type: 'VIRTUAL',
      status: 'BLOCKED',
      last_four_digits: '2653',
      issued_at: daysAgo(171),
      expires_at: dayOnlyAgo(-406),
      blocked_reason: 'Customer request',
      blocked_at: daysAgo(126),
    },
    {
      id: 254,
      customer_id: 122,
      card_type: 'VIRTUAL',
      status: 'PENDING',
      last_four_digits: '6179',
      issued_at: daysAgo(201),
      expires_at: dayOnlyAgo(-499),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 255,
      customer_id: 123,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '9506',
      issued_at: daysAgo(34),
      expires_at: dayOnlyAgo(-427),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 256,
      customer_id: 124,
      card_type: 'VIRTUAL',
      status: 'PENDING',
      last_four_digits: '3962',
      issued_at: daysAgo(89),
      expires_at: dayOnlyAgo(-1017),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 257,
      customer_id: 125,
      card_type: 'VIRTUAL',
      status: 'EXPIRED',
      last_four_digits: '8549',
      issued_at: daysAgo(217),
      expires_at: dayOnlyAgo(-1340),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 258,
      customer_id: 125,
      card_type: 'VIRTUAL',
      status: 'CANCELLED',
      last_four_digits: '6457',
      issued_at: daysAgo(212),
      expires_at: dayOnlyAgo(-1430),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 259,
      customer_id: 125,
      card_type: 'PHYSICAL',
      status: 'PENDING',
      last_four_digits: '9322',
      issued_at: daysAgo(166),
      expires_at: dayOnlyAgo(-661),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 260,
      customer_id: 126,
      card_type: 'VIRTUAL',
      status: 'CANCELLED',
      last_four_digits: '7961',
      issued_at: daysAgo(240),
      expires_at: dayOnlyAgo(-385),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 261,
      customer_id: 127,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '8031',
      issued_at: daysAgo(73),
      expires_at: dayOnlyAgo(-568),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 262,
      customer_id: 128,
      card_type: 'VIRTUAL',
      status: 'BLOCKED',
      last_four_digits: '5002',
      issued_at: daysAgo(237),
      expires_at: dayOnlyAgo(-1225),
      blocked_reason: 'Customer request',
      blocked_at: daysAgo(148),
    },
    {
      id: 263,
      customer_id: 128,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '3424',
      issued_at: daysAgo(133),
      expires_at: dayOnlyAgo(-553),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 264,
      customer_id: 128,
      card_type: 'VIRTUAL',
      status: 'BLOCKED',
      last_four_digits: '9905',
      issued_at: daysAgo(128),
      expires_at: dayOnlyAgo(-987),
      blocked_reason: 'Customer request',
      blocked_at: daysAgo(98),
    },
    {
      id: 265,
      customer_id: 129,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '6942',
      issued_at: daysAgo(34),
      expires_at: dayOnlyAgo(-1312),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 266,
      customer_id: 129,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '3017',
      issued_at: daysAgo(31),
      expires_at: dayOnlyAgo(-734),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 267,
      customer_id: 129,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '5878',
      issued_at: daysAgo(268),
      expires_at: dayOnlyAgo(-1096),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 268,
      customer_id: 130,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '0140',
      issued_at: daysAgo(114),
      expires_at: dayOnlyAgo(-493),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 269,
      customer_id: 130,
      card_type: 'VIRTUAL',
      status: 'BLOCKED',
      last_four_digits: '7549',
      issued_at: daysAgo(152),
      expires_at: dayOnlyAgo(-1264),
      blocked_reason: 'Reported lost',
      blocked_at: daysAgo(91),
    },
    {
      id: 270,
      customer_id: 130,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '9747',
      issued_at: daysAgo(110),
      expires_at: dayOnlyAgo(-387),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 271,
      customer_id: 131,
      card_type: 'VIRTUAL',
      status: 'CANCELLED',
      last_four_digits: '2211',
      issued_at: daysAgo(107),
      expires_at: dayOnlyAgo(-1171),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 272,
      customer_id: 132,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '9698',
      issued_at: daysAgo(99),
      expires_at: dayOnlyAgo(-990),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 273,
      customer_id: 133,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '8302',
      issued_at: daysAgo(167),
      expires_at: dayOnlyAgo(-577),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 274,
      customer_id: 133,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '4605',
      issued_at: daysAgo(275),
      expires_at: dayOnlyAgo(-717),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 275,
      customer_id: 133,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '7043',
      issued_at: daysAgo(211),
      expires_at: dayOnlyAgo(-861),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 276,
      customer_id: 134,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '3873',
      issued_at: daysAgo(119),
      expires_at: dayOnlyAgo(-1302),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 277,
      customer_id: 134,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '8459',
      issued_at: daysAgo(101),
      expires_at: dayOnlyAgo(-1283),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 278,
      customer_id: 135,
      card_type: 'PHYSICAL',
      status: 'BLOCKED',
      last_four_digits: '1410',
      issued_at: daysAgo(152),
      expires_at: dayOnlyAgo(-754),
      blocked_reason: 'Compliance hold',
      blocked_at: daysAgo(39),
    },
    {
      id: 279,
      customer_id: 135,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '8451',
      issued_at: daysAgo(314),
      expires_at: dayOnlyAgo(-908),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 280,
      customer_id: 135,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '8094',
      issued_at: daysAgo(312),
      expires_at: dayOnlyAgo(-1066),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 281,
      customer_id: 136,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '4402',
      issued_at: daysAgo(170),
      expires_at: dayOnlyAgo(-677),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 282,
      customer_id: 136,
      card_type: 'VIRTUAL',
      status: 'BLOCKED',
      last_four_digits: '9855',
      issued_at: daysAgo(371),
      expires_at: dayOnlyAgo(-1409),
      blocked_reason: 'Suspected fraud',
      blocked_at: daysAgo(163),
    },
    {
      id: 283,
      customer_id: 137,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '5163',
      issued_at: daysAgo(334),
      expires_at: dayOnlyAgo(-470),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 284,
      customer_id: 137,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '9440',
      issued_at: daysAgo(371),
      expires_at: dayOnlyAgo(-1129),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 285,
      customer_id: 138,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '4656',
      issued_at: daysAgo(112),
      expires_at: dayOnlyAgo(-414),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 286,
      customer_id: 139,
      card_type: 'VIRTUAL',
      status: 'PENDING',
      last_four_digits: '9611',
      issued_at: daysAgo(308),
      expires_at: dayOnlyAgo(-1437),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 287,
      customer_id: 140,
      card_type: 'PHYSICAL',
      status: 'BLOCKED',
      last_four_digits: '3309',
      issued_at: daysAgo(269),
      expires_at: dayOnlyAgo(-639),
      blocked_reason: 'Compliance hold',
      blocked_at: daysAgo(78),
    },
    {
      id: 288,
      customer_id: 141,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '5155',
      issued_at: daysAgo(67),
      expires_at: dayOnlyAgo(-901),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 289,
      customer_id: 141,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '5972',
      issued_at: daysAgo(289),
      expires_at: dayOnlyAgo(-773),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 290,
      customer_id: 142,
      card_type: 'VIRTUAL',
      status: 'EXPIRED',
      last_four_digits: '9630',
      issued_at: daysAgo(345),
      expires_at: dayOnlyAgo(-739),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 291,
      customer_id: 142,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '8542',
      issued_at: daysAgo(199),
      expires_at: dayOnlyAgo(-991),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 292,
      customer_id: 142,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '6173',
      issued_at: daysAgo(141),
      expires_at: dayOnlyAgo(-730),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 293,
      customer_id: 143,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '2089',
      issued_at: daysAgo(84),
      expires_at: dayOnlyAgo(-856),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 294,
      customer_id: 143,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '7069',
      issued_at: daysAgo(157),
      expires_at: dayOnlyAgo(-629),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 295,
      customer_id: 143,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '4110',
      issued_at: daysAgo(203),
      expires_at: dayOnlyAgo(-1316),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 296,
      customer_id: 144,
      card_type: 'VIRTUAL',
      status: 'BLOCKED',
      last_four_digits: '6939',
      issued_at: daysAgo(199),
      expires_at: dayOnlyAgo(-493),
      blocked_reason: 'Compliance hold',
      blocked_at: daysAgo(95),
    },
    {
      id: 297,
      customer_id: 145,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '7268',
      issued_at: daysAgo(124),
      expires_at: dayOnlyAgo(-755),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 298,
      customer_id: 146,
      card_type: 'PHYSICAL',
      status: 'BLOCKED',
      last_four_digits: '0839',
      issued_at: daysAgo(240),
      expires_at: dayOnlyAgo(-397),
      blocked_reason: 'Customer request',
      blocked_at: daysAgo(215),
    },
    {
      id: 299,
      customer_id: 147,
      card_type: 'VIRTUAL',
      status: 'BLOCKED',
      last_four_digits: '7762',
      issued_at: daysAgo(260),
      expires_at: dayOnlyAgo(-434),
      blocked_reason: 'Reported lost',
      blocked_at: daysAgo(212),
    },
    {
      id: 300,
      customer_id: 147,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '8658',
      issued_at: daysAgo(54),
      expires_at: dayOnlyAgo(-857),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 301,
      customer_id: 147,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '7899',
      issued_at: daysAgo(36),
      expires_at: dayOnlyAgo(-672),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 302,
      customer_id: 148,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '9609',
      issued_at: daysAgo(102),
      expires_at: dayOnlyAgo(-399),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 303,
      customer_id: 148,
      card_type: 'VIRTUAL',
      status: 'EXPIRED',
      last_four_digits: '8875',
      issued_at: daysAgo(187),
      expires_at: dayOnlyAgo(-719),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 304,
      customer_id: 148,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '6782',
      issued_at: daysAgo(329),
      expires_at: dayOnlyAgo(-1187),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 305,
      customer_id: 149,
      card_type: 'VIRTUAL',
      status: 'ACTIVE',
      last_four_digits: '0771',
      issued_at: daysAgo(21),
      expires_at: dayOnlyAgo(-1198),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 306,
      customer_id: 149,
      card_type: 'PHYSICAL',
      status: 'ACTIVE',
      last_four_digits: '5885',
      issued_at: daysAgo(279),
      expires_at: dayOnlyAgo(-962),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 307,
      customer_id: 149,
      card_type: 'PHYSICAL',
      status: 'EXPIRED',
      last_four_digits: '9604',
      issued_at: daysAgo(148),
      expires_at: dayOnlyAgo(-909),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 308,
      customer_id: 150,
      card_type: 'VIRTUAL',
      status: 'EXPIRED',
      last_four_digits: '3157',
      issued_at: daysAgo(338),
      expires_at: dayOnlyAgo(-451),
      blocked_reason: null,
      blocked_at: null,
    },
    {
      id: 309,
      customer_id: 150,
      card_type: 'PHYSICAL',
      status: 'BLOCKED',
      last_four_digits: '9721',
      issued_at: daysAgo(112),
      expires_at: dayOnlyAgo(-908),
      blocked_reason: 'Reported lost',
      blocked_at: daysAgo(54),
    },
  ];

  constructor(datasource: DataSource) {
    super(datasource, 'cards', CardsCollection.schema);
  }
}
