import type { DataSource, FieldSchema, RecordData } from '@forestadmin/datasource-toolkit';

import BaseFintechCollection from './base';
import { daysAgo } from '../dates';

export default class CustomersCollection extends BaseFintechCollection {
  private static schema: Record<string, FieldSchema> = {
    id: {
      type: 'Column',
      columnType: 'Number',
      isPrimaryKey: true,
    },
    first_name: {
      type: 'Column',
      columnType: 'String',
    },
    last_name: {
      type: 'Column',
      columnType: 'String',
    },
    email: {
      type: 'Column',
      columnType: 'String',
    },
    phone: {
      type: 'Column',
      columnType: 'String',
    },
    date_of_birth: {
      type: 'Column',
      columnType: 'Dateonly',
    },
    nationality: {
      type: 'Column',
      columnType: 'String',
    },
    country_of_residence: {
      type: 'Column',
      columnType: 'String',
    },
    address_line1: {
      type: 'Column',
      columnType: 'String',
    },
    address_line2: {
      type: 'Column',
      columnType: 'String',
    },
    city: {
      type: 'Column',
      columnType: 'String',
    },
    postal_code: {
      type: 'Column',
      columnType: 'String',
    },
    country: {
      type: 'Column',
      columnType: 'String',
    },
    onboarding_status: {
      type: 'Column',
      columnType: 'Enum',
      enumValues: ['STARTED', 'PENDING_REVIEW', 'APPROVED', 'REJECTED'],
    },
    risk_rating: {
      type: 'Column',
      columnType: 'Enum',
      enumValues: ['LOW', 'MEDIUM', 'HIGH'],
    },
    is_pep: {
      type: 'Column',
      columnType: 'Boolean',
    },
    is_sanctioned: {
      type: 'Column',
      columnType: 'Boolean',
    },
    referral_code: {
      type: 'Column',
      columnType: 'String',
    },
    created_at: {
      type: 'Column',
      columnType: 'Date',
    },
    updated_at: {
      type: 'Column',
      columnType: 'Date',
    },
  };

  protected override records: RecordData[] = [
    {
      id: 1,
      first_name: 'Emma',
      last_name: 'Schneider',
      email: 'emma.schneider@example.com',
      phone: '+33 645 732488',
      date_of_birth: '1985-02-28',
      nationality: 'PT',
      country_of_residence: 'FR',
      address_line1: 'Rue Royale 144',
      address_line2: null,
      city: 'Paris',
      postal_code: '75001',
      country: 'FR',
      onboarding_status: 'REJECTED',
      risk_rating: 'HIGH',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF5743',
      created_at: daysAgo(119),
      updated_at: daysAgo(20),
    },
    {
      id: 2,
      first_name: 'Lucas',
      last_name: 'Novak',
      email: 'lucas.novak@example.com',
      phone: '+33 734 701528',
      date_of_birth: '1985-12-01',
      nationality: 'NL',
      country_of_residence: 'FR',
      address_line1: 'Via Roma 52',
      address_line2: 'Apt 22',
      city: 'Paris',
      postal_code: '75001',
      country: 'FR',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(102),
      updated_at: daysAgo(87),
    },
    {
      id: 3,
      first_name: 'Sofia',
      last_name: 'Romano',
      email: 'sofia.romano@example.com',
      phone: '+420 787 716482',
      date_of_birth: '1985-10-09',
      nationality: 'BE',
      country_of_residence: 'CZ',
      address_line1: 'Nørregade 99',
      address_line2: null,
      city: 'Prague',
      postal_code: '11000',
      country: 'CZ',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(198),
      updated_at: daysAgo(103),
    },
    {
      id: 4,
      first_name: 'Liam',
      last_name: 'Vargas',
      email: 'liam.vargas@example.com',
      phone: '+420 726 701127',
      date_of_birth: '1998-05-25',
      nationality: 'ES',
      country_of_residence: 'CZ',
      address_line1: 'Karl Johans gate 75',
      address_line2: null,
      city: 'Prague',
      postal_code: '11000',
      country: 'CZ',
      onboarding_status: 'PENDING_REVIEW',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(109),
      updated_at: daysAgo(83),
    },
    {
      id: 5,
      first_name: 'Mia',
      last_name: 'Hassan',
      email: 'mia.hassan@example.com',
      phone: '+353 792 537980',
      date_of_birth: '1973-08-22',
      nationality: 'PT',
      country_of_residence: 'IE',
      address_line1: 'Rue Royale 34',
      address_line2: 'Apt 37',
      city: 'Dublin',
      postal_code: 'D01',
      country: 'IE',
      onboarding_status: 'REJECTED',
      risk_rating: 'HIGH',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(106),
      updated_at: daysAgo(46),
    },
    {
      id: 6,
      first_name: 'Noah',
      last_name: 'Rossi',
      email: 'noah.rossi@example.com',
      phone: '+33 684 498504',
      date_of_birth: '1987-09-15',
      nationality: 'DE',
      country_of_residence: 'FR',
      address_line1: 'Rue de la Paix 18',
      address_line2: null,
      city: 'Marseille',
      postal_code: '13001',
      country: 'FR',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(168),
      updated_at: daysAgo(131),
    },
    {
      id: 7,
      first_name: 'Olivia',
      last_name: 'Ferretti',
      email: 'olivia.ferretti@example.com',
      phone: '+358 740 342705',
      date_of_birth: '1997-08-26',
      nationality: 'IE',
      country_of_residence: 'FI',
      address_line1: 'Via Roma 18',
      address_line2: null,
      city: 'Helsinki',
      postal_code: '00100',
      country: 'FI',
      onboarding_status: 'APPROVED',
      risk_rating: 'HIGH',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(103),
      updated_at: daysAgo(45),
    },
    {
      id: 8,
      first_name: 'Hugo',
      last_name: 'Bianchi',
      email: 'hugo.bianchi@example.com',
      phone: '+98 718 198170',
      date_of_birth: '1994-09-26',
      nationality: 'FR',
      country_of_residence: 'IR',
      address_line1: 'Hauptstraße 6',
      address_line2: null,
      city: 'Tehran',
      postal_code: '11369',
      country: 'IR',
      onboarding_status: 'REJECTED',
      risk_rating: 'HIGH',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(138),
      updated_at: daysAgo(30),
    },
    {
      id: 9,
      first_name: 'Léa',
      last_name: 'Sørensen',
      email: 'lea.sorensen@example.com',
      phone: '+420 729 128873',
      date_of_birth: '1992-10-11',
      nationality: 'IT',
      country_of_residence: 'CZ',
      address_line1: 'Nørregade 91',
      address_line2: null,
      city: 'Prague',
      postal_code: '11000',
      country: 'CZ',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(115),
      updated_at: daysAgo(82),
    },
    {
      id: 10,
      first_name: 'Jonas',
      last_name: 'Lefebvre',
      email: 'jonas.lefebvre@example.com',
      phone: '+48 790 257875',
      date_of_birth: '1968-07-19',
      nationality: 'IT',
      country_of_residence: 'PL',
      address_line1: 'Nørregade 44',
      address_line2: null,
      city: 'Warsaw',
      postal_code: '00-001',
      country: 'PL',
      onboarding_status: 'STARTED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(139),
      updated_at: daysAgo(78),
    },
    {
      id: 11,
      first_name: 'Priya',
      last_name: 'Lopez',
      email: 'priya.lopez@example.com',
      phone: '+39 609 961768',
      date_of_birth: '1986-04-02',
      nationality: 'ES',
      country_of_residence: 'IT',
      address_line1: 'Rue Royale 137',
      address_line2: null,
      city: 'Rome',
      postal_code: '00184',
      country: 'IT',
      onboarding_status: 'REJECTED',
      risk_rating: 'HIGH',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF5102',
      created_at: daysAgo(179),
      updated_at: daysAgo(31),
    },
    {
      id: 12,
      first_name: 'Mateo',
      last_name: 'Nowak',
      email: 'mateo.nowak@example.com',
      phone: '+47 617 222712',
      date_of_birth: '2003-03-14',
      nationality: 'BE',
      country_of_residence: 'NO',
      address_line1: 'Marszałkowska 88',
      address_line2: null,
      city: 'Oslo',
      postal_code: '0150',
      country: 'NO',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(197),
      updated_at: daysAgo(184),
    },
    {
      id: 13,
      first_name: 'Ingrid',
      last_name: 'Weber',
      email: 'ingrid.weber@example.com',
      phone: '+43 752 501368',
      date_of_birth: '1982-04-14',
      nationality: 'DE',
      country_of_residence: 'AT',
      address_line1: 'Karl Johans gate 66',
      address_line2: null,
      city: 'Vienna',
      postal_code: '1010',
      country: 'AT',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(143),
      updated_at: daysAgo(68),
    },
    {
      id: 14,
      first_name: 'Youssef',
      last_name: 'Costa',
      email: 'youssef.costa@example.com',
      phone: '+49 752 692127',
      date_of_birth: '1996-01-17',
      nationality: 'DK',
      country_of_residence: 'DE',
      address_line1: 'Damrak 93',
      address_line2: null,
      city: 'Berlin',
      postal_code: '10117',
      country: 'DE',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(205),
      updated_at: daysAgo(113),
    },
    {
      id: 15,
      first_name: 'Anna',
      last_name: 'Khan',
      email: 'anna.khan@example.com',
      phone: '+49 636 432099',
      date_of_birth: '1992-12-08',
      nationality: 'NO',
      country_of_residence: 'DE',
      address_line1: 'Karl Johans gate 84',
      address_line2: null,
      city: 'Berlin',
      postal_code: '10117',
      country: 'DE',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(171),
      updated_at: daysAgo(80),
    },
    {
      id: 16,
      first_name: 'Marco',
      last_name: 'Jensen',
      email: 'marco.jensen@example.com',
      phone: '+48 742 635564',
      date_of_birth: '2001-10-14',
      nationality: 'DE',
      country_of_residence: 'PL',
      address_line1: 'Mannerheimintie 12',
      address_line2: null,
      city: 'Warsaw',
      postal_code: '00-001',
      country: 'PL',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(79),
      updated_at: daysAgo(48),
    },
    {
      id: 17,
      first_name: 'Fatima',
      last_name: 'Wójcik',
      email: 'fatima.wójcik@example.com',
      phone: '+45 796 981522',
      date_of_birth: '2002-10-27',
      nationality: 'AT',
      country_of_residence: 'DK',
      address_line1: 'Rue de la Paix 17',
      address_line2: 'Apt 2',
      city: 'Copenhagen',
      postal_code: '1050',
      country: 'DK',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(166),
      updated_at: daysAgo(137),
    },
    {
      id: 18,
      first_name: 'Erik',
      last_name: 'Andersen',
      email: 'erik.andersen@example.com',
      phone: '+358 690 930789',
      date_of_birth: '1989-04-05',
      nationality: 'NL',
      country_of_residence: 'FI',
      address_line1: 'Rue Royale 10',
      address_line2: null,
      city: 'Helsinki',
      postal_code: '00100',
      country: 'FI',
      onboarding_status: 'PENDING_REVIEW',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(195),
      updated_at: daysAgo(115),
    },
    {
      id: 19,
      first_name: 'Chloé',
      last_name: 'Haddad',
      email: 'chloe.haddad@example.com',
      phone: '+31 758 765530',
      date_of_birth: '1962-09-25',
      nationality: 'IT',
      country_of_residence: 'NL',
      address_line1: 'Marszałkowska 162',
      address_line2: null,
      city: 'Amsterdam',
      postal_code: '1011',
      country: 'NL',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(125),
      updated_at: daysAgo(97),
    },
    {
      id: 20,
      first_name: 'Viktor',
      last_name: 'Berg',
      email: 'viktor.berg@example.com',
      phone: '+47 799 255412',
      date_of_birth: '1986-01-19',
      nationality: 'PT',
      country_of_residence: 'NO',
      address_line1: 'Calle Mayor 108',
      address_line2: 'Apt 16',
      city: 'Oslo',
      postal_code: '0150',
      country: 'NO',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(145),
      updated_at: daysAgo(23),
    },
    {
      id: 21,
      first_name: 'Aisha',
      last_name: 'Demir',
      email: 'aisha.demir@example.com',
      phone: '+420 713 591932',
      date_of_birth: '1988-11-22',
      nationality: 'DE',
      country_of_residence: 'CZ',
      address_line1: 'Hauptstraße 18',
      address_line2: 'Apt 1',
      city: 'Prague',
      postal_code: '11000',
      country: 'CZ',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(174),
      updated_at: daysAgo(86),
    },
    {
      id: 22,
      first_name: 'Daniel',
      last_name: 'Santos',
      email: 'daniel.santos@example.com',
      phone: '+49 681 843397',
      date_of_birth: '1976-03-21',
      nationality: 'NO',
      country_of_residence: 'DE',
      address_line1: 'Hauptstraße 113',
      address_line2: null,
      city: 'Munich',
      postal_code: '80331',
      country: 'DE',
      onboarding_status: 'PENDING_REVIEW',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF6220',
      created_at: daysAgo(60),
      updated_at: daysAgo(21),
    },
    {
      id: 23,
      first_name: 'Elena',
      last_name: 'Müller',
      email: 'elena.muller@example.com',
      phone: '+45 627 736570',
      date_of_birth: '1992-04-26',
      nationality: 'CZ',
      country_of_residence: 'DK',
      address_line1: 'Calle Mayor 108',
      address_line2: null,
      city: 'Copenhagen',
      postal_code: '1050',
      country: 'DK',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(91),
      updated_at: daysAgo(80),
    },
    {
      id: 24,
      first_name: 'Tomas',
      last_name: 'Kowalski',
      email: 'tomas.kowalski@example.com',
      phone: '+353 701 925734',
      date_of_birth: '1971-02-09',
      nationality: 'CZ',
      country_of_residence: 'IE',
      address_line1: 'Damrak 176',
      address_line2: null,
      city: 'Dublin',
      postal_code: 'D01',
      country: 'IE',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(206),
      updated_at: daysAgo(119),
    },
    {
      id: 25,
      first_name: 'Nadia',
      last_name: 'Petrov',
      email: 'nadia.petrov@example.com',
      phone: '+420 789 375639',
      date_of_birth: '1983-05-07',
      nationality: 'ES',
      country_of_residence: 'CZ',
      address_line1: 'Mannerheimintie 113',
      address_line2: null,
      city: 'Prague',
      postal_code: '11000',
      country: 'CZ',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(96),
      updated_at: daysAgo(32),
    },
    {
      id: 26,
      first_name: 'Pablo',
      last_name: 'Fischer',
      email: 'pablo.fischer@example.com',
      phone: '+48 731 586479',
      date_of_birth: '1999-08-24',
      nationality: 'PL',
      country_of_residence: 'PL',
      address_line1: 'Marszałkowska 82',
      address_line2: null,
      city: 'Warsaw',
      postal_code: '00-001',
      country: 'PL',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(204),
      updated_at: daysAgo(122),
    },
    {
      id: 27,
      first_name: 'Greta',
      last_name: 'Ivanov',
      email: 'greta.ivanov@example.com',
      phone: '+48 676 393913',
      date_of_birth: '1962-02-19',
      nationality: 'ES',
      country_of_residence: 'PL',
      address_line1: 'Hauptstraße 83',
      address_line2: null,
      city: 'Warsaw',
      postal_code: '00-001',
      country: 'PL',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(174),
      updated_at: daysAgo(117),
    },
    {
      id: 28,
      first_name: 'Kemal',
      last_name: 'Eriksson',
      email: 'kemal.eriksson@example.com',
      phone: '+39 669 654337',
      date_of_birth: '1981-10-03',
      nationality: 'SE',
      country_of_residence: 'IT',
      address_line1: 'Via Roma 160',
      address_line2: 'Apt 39',
      city: 'Rome',
      postal_code: '00184',
      country: 'IT',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(114),
      updated_at: daysAgo(19),
    },
    {
      id: 29,
      first_name: 'Sara',
      last_name: 'Dubois',
      email: 'sara.dubois@example.com',
      phone: '+47 681 438472',
      date_of_birth: '1968-11-17',
      nationality: 'SE',
      country_of_residence: 'NO',
      address_line1: 'Hauptstraße 155',
      address_line2: null,
      city: 'Oslo',
      postal_code: '0150',
      country: 'NO',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(211),
      updated_at: daysAgo(106),
    },
    {
      id: 30,
      first_name: 'Andrei',
      last_name: 'Sharma',
      email: 'andrei.sharma@example.com',
      phone: '+45 704 910713',
      date_of_birth: '1999-02-07',
      nationality: 'IE',
      country_of_residence: 'DK',
      address_line1: 'Calle Mayor 127',
      address_line2: null,
      city: 'Copenhagen',
      postal_code: '1050',
      country: 'DK',
      onboarding_status: 'STARTED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(168),
      updated_at: daysAgo(52),
    },
    {
      id: 31,
      first_name: 'Maja',
      last_name: 'Mensah',
      email: 'maja.mensah@example.com',
      phone: '+31 776 314492',
      date_of_birth: '1986-06-15',
      nationality: 'FI',
      country_of_residence: 'NL',
      address_line1: 'Marszałkowska 74',
      address_line2: 'Apt 9',
      city: 'Amsterdam',
      postal_code: '1011',
      country: 'NL',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: true,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(200),
      updated_at: daysAgo(9),
    },
    {
      id: 32,
      first_name: 'Stefan',
      last_name: 'Marchetti',
      email: 'stefan.marchetti@example.com',
      phone: '+46 753 574299',
      date_of_birth: '1980-05-28',
      nationality: 'FI',
      country_of_residence: 'SE',
      address_line1: 'Calle Mayor 63',
      address_line2: null,
      city: 'Stockholm',
      postal_code: '11129',
      country: 'SE',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(114),
      updated_at: daysAgo(61),
    },
    {
      id: 33,
      first_name: 'Camille',
      last_name: 'Kovač',
      email: 'camille.kovac@example.com',
      phone: '+39 623 953465',
      date_of_birth: '1963-10-17',
      nationality: 'DE',
      country_of_residence: 'IT',
      address_line1: 'Marszałkowska 158',
      address_line2: null,
      city: 'Rome',
      postal_code: '00184',
      country: 'IT',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF2976',
      created_at: daysAgo(120),
      updated_at: daysAgo(107),
    },
    {
      id: 34,
      first_name: 'Dimitri',
      last_name: 'Popescu',
      email: 'dimitri.popescu@example.com',
      phone: '+48 610 444539',
      date_of_birth: '1982-05-01',
      nationality: 'CZ',
      country_of_residence: 'PL',
      address_line1: 'Nørregade 42',
      address_line2: null,
      city: 'Warsaw',
      postal_code: '00-001',
      country: 'PL',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: true,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(123),
      updated_at: daysAgo(78),
    },
    {
      id: 35,
      first_name: 'Zofia',
      last_name: 'García',
      email: 'zofia.garcía@example.com',
      phone: '+420 741 558133',
      date_of_birth: '1996-03-01',
      nationality: 'AT',
      country_of_residence: 'CZ',
      address_line1: 'Karl Johans gate 168',
      address_line2: null,
      city: 'Prague',
      postal_code: '11000',
      country: 'CZ',
      onboarding_status: 'REJECTED',
      risk_rating: 'HIGH',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(99),
      updated_at: daysAgo(1),
    },
    {
      id: 36,
      first_name: 'Omar',
      last_name: 'Lindqvist',
      email: 'omar.lindqvist@example.com',
      phone: '+358 737 814280',
      date_of_birth: '1962-11-07',
      nationality: 'BE',
      country_of_residence: 'FI',
      address_line1: 'Calle Mayor 14',
      address_line2: null,
      city: 'Helsinki',
      postal_code: '00100',
      country: 'FI',
      onboarding_status: 'PENDING_REVIEW',
      risk_rating: 'HIGH',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF9926',
      created_at: daysAgo(162),
      updated_at: daysAgo(85),
    },
    {
      id: 37,
      first_name: 'Linnea',
      last_name: 'Ahmadi',
      email: 'linnea.ahmadi@example.com',
      phone: '+39 785 403387',
      date_of_birth: '2002-12-22',
      nationality: 'SE',
      country_of_residence: 'IT',
      address_line1: 'Via Roma 51',
      address_line2: null,
      city: 'Rome',
      postal_code: '00184',
      country: 'IT',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(66),
      updated_at: daysAgo(31),
    },
    {
      id: 38,
      first_name: 'Rafael',
      last_name: 'Olsen',
      email: 'rafael.olsen@example.com',
      phone: '+47 776 716170',
      date_of_birth: '1988-06-23',
      nationality: 'IT',
      country_of_residence: 'NO',
      address_line1: 'Calle Mayor 19',
      address_line2: 'Apt 8',
      city: 'Oslo',
      postal_code: '0150',
      country: 'NO',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(70),
      updated_at: daysAgo(37),
    },
    {
      id: 39,
      first_name: 'Yara',
      last_name: 'Moreau',
      email: 'yara.moreau@example.com',
      phone: '+47 670 486128',
      date_of_birth: '1992-01-18',
      nationality: 'NO',
      country_of_residence: 'NO',
      address_line1: 'Rue Royale 159',
      address_line2: 'Apt 20',
      city: 'Oslo',
      postal_code: '0150',
      country: 'NO',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF2321',
      created_at: daysAgo(125),
      updated_at: daysAgo(53),
    },
    {
      id: 40,
      first_name: 'Janusz',
      last_name: 'Johansson',
      email: 'janusz.johansson@example.com',
      phone: '+48 686 931552',
      date_of_birth: '2000-02-14',
      nationality: 'AT',
      country_of_residence: 'PL',
      address_line1: 'Storgatan 89',
      address_line2: null,
      city: 'Warsaw',
      postal_code: '00-001',
      country: 'PL',
      onboarding_status: 'APPROVED',
      risk_rating: 'HIGH',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(208),
      updated_at: daysAgo(144),
    },
    {
      id: 41,
      first_name: 'Beatriz',
      last_name: 'Schneider',
      email: 'beatriz.schneider@example.com',
      phone: '+31 748 513930',
      date_of_birth: '1974-04-11',
      nationality: 'ES',
      country_of_residence: 'NL',
      address_line1: 'Storgatan 6',
      address_line2: null,
      city: 'Amsterdam',
      postal_code: '1011',
      country: 'NL',
      onboarding_status: 'STARTED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(212),
      updated_at: daysAgo(52),
    },
    {
      id: 42,
      first_name: 'Henrik',
      last_name: 'Novak',
      email: 'henrik.novak@example.com',
      phone: '+49 709 507696',
      date_of_birth: '1976-08-17',
      nationality: 'ES',
      country_of_residence: 'DE',
      address_line1: 'Nørregade 158',
      address_line2: null,
      city: 'Berlin',
      postal_code: '10117',
      country: 'DE',
      onboarding_status: 'PENDING_REVIEW',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(178),
      updated_at: daysAgo(81),
    },
    {
      id: 43,
      first_name: 'Amara',
      last_name: 'Romano',
      email: 'amara.romano@example.com',
      phone: '+31 682 470041',
      date_of_birth: '1974-09-10',
      nationality: 'SE',
      country_of_residence: 'NL',
      address_line1: 'Rue Royale 143',
      address_line2: null,
      city: 'Amsterdam',
      postal_code: '1011',
      country: 'NL',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: true,
      is_sanctioned: false,
      referral_code: 'REF8832',
      created_at: daysAgo(108),
      updated_at: daysAgo(89),
    },
    {
      id: 44,
      first_name: 'Niko',
      last_name: 'Vargas',
      email: 'niko.vargas@example.com',
      phone: '+45 650 154436',
      date_of_birth: '1987-01-04',
      nationality: 'FI',
      country_of_residence: 'DK',
      address_line1: 'Rue de la Paix 43',
      address_line2: null,
      city: 'Copenhagen',
      postal_code: '1050',
      country: 'DK',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(197),
      updated_at: daysAgo(182),
    },
    {
      id: 45,
      first_name: 'Wei',
      last_name: 'Hassan',
      email: 'wei.hassan@example.com',
      phone: '+32 653 842173',
      date_of_birth: '1977-04-02',
      nationality: 'FI',
      country_of_residence: 'BE',
      address_line1: 'Nørregade 161',
      address_line2: null,
      city: 'Brussels',
      postal_code: '1000',
      country: 'BE',
      onboarding_status: 'PENDING_REVIEW',
      risk_rating: 'MEDIUM',
      is_pep: true,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(190),
      updated_at: daysAgo(111),
    },
    {
      id: 46,
      first_name: 'Ravi',
      last_name: 'Rossi',
      email: 'ravi.rossi@example.com',
      phone: '+47 725 663544',
      date_of_birth: '1983-11-12',
      nationality: 'CZ',
      country_of_residence: 'NO',
      address_line1: 'Karl Johans gate 16',
      address_line2: 'Apt 29',
      city: 'Oslo',
      postal_code: '0150',
      country: 'NO',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF3185',
      created_at: daysAgo(188),
      updated_at: daysAgo(22),
    },
    {
      id: 47,
      first_name: 'Sasha',
      last_name: 'Ferretti',
      email: 'sasha.ferretti@example.com',
      phone: '+43 681 430134',
      date_of_birth: '1984-01-09',
      nationality: 'CZ',
      country_of_residence: 'AT',
      address_line1: 'Mannerheimintie 103',
      address_line2: null,
      city: 'Vienna',
      postal_code: '1010',
      country: 'AT',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(199),
      updated_at: daysAgo(17),
    },
    {
      id: 48,
      first_name: 'Lena',
      last_name: 'Bianchi',
      email: 'lena.bianchi@example.com',
      phone: '+353 732 322298',
      date_of_birth: '1974-03-07',
      nationality: 'IE',
      country_of_residence: 'IE',
      address_line1: 'Mannerheimintie 116',
      address_line2: null,
      city: 'Dublin',
      postal_code: 'D01',
      country: 'IE',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF2576',
      created_at: daysAgo(220),
      updated_at: daysAgo(122),
    },
    {
      id: 49,
      first_name: 'Emma',
      last_name: 'Sørensen',
      email: 'emma.sorensen@example.com',
      phone: '+48 695 540846',
      date_of_birth: '1989-03-20',
      nationality: 'AT',
      country_of_residence: 'PL',
      address_line1: 'Marszałkowska 25',
      address_line2: null,
      city: 'Warsaw',
      postal_code: '00-001',
      country: 'PL',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(138),
      updated_at: daysAgo(112),
    },
    {
      id: 50,
      first_name: 'Lucas',
      last_name: 'Lefebvre',
      email: 'lucas.lefebvre@example.com',
      phone: '+33 605 549050',
      date_of_birth: '1964-10-14',
      nationality: 'IT',
      country_of_residence: 'FR',
      address_line1: 'Marszałkowska 101',
      address_line2: null,
      city: 'Marseille',
      postal_code: '13001',
      country: 'FR',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF9810',
      created_at: daysAgo(104),
      updated_at: daysAgo(17),
    },
    {
      id: 51,
      first_name: 'Sofia',
      last_name: 'Lopez',
      email: 'sofia.lopez@example.com',
      phone: '+95 654 313607',
      date_of_birth: '1995-06-04',
      nationality: 'ES',
      country_of_residence: 'MM',
      address_line1: 'Marszałkowska 132',
      address_line2: null,
      city: 'Yangon',
      postal_code: '11181',
      country: 'MM',
      onboarding_status: 'REJECTED',
      risk_rating: 'HIGH',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF5442',
      created_at: daysAgo(73),
      updated_at: daysAgo(55),
    },
    {
      id: 52,
      first_name: 'Liam',
      last_name: 'Nowak',
      email: 'liam.nowak@example.com',
      phone: '+353 639 153714',
      date_of_birth: '1983-08-08',
      nationality: 'CZ',
      country_of_residence: 'IE',
      address_line1: 'Mannerheimintie 131',
      address_line2: 'Apt 10',
      city: 'Dublin',
      postal_code: 'D01',
      country: 'IE',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF1630',
      created_at: daysAgo(118),
      updated_at: daysAgo(33),
    },
    {
      id: 53,
      first_name: 'Mia',
      last_name: 'Weber',
      email: 'mia.weber@example.com',
      phone: '+32 749 830756',
      date_of_birth: '2003-10-25',
      nationality: 'NO',
      country_of_residence: 'BE',
      address_line1: 'Karl Johans gate 68',
      address_line2: null,
      city: 'Brussels',
      postal_code: '1000',
      country: 'BE',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(182),
      updated_at: daysAgo(64),
    },
    {
      id: 54,
      first_name: 'Noah',
      last_name: 'Costa',
      email: 'noah.costa@example.com',
      phone: '+39 644 801095',
      date_of_birth: '1974-01-05',
      nationality: 'SE',
      country_of_residence: 'IT',
      address_line1: 'Mannerheimintie 175',
      address_line2: null,
      city: 'Milan',
      postal_code: '20121',
      country: 'IT',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(168),
      updated_at: daysAgo(142),
    },
    {
      id: 55,
      first_name: 'Olivia',
      last_name: 'Khan',
      email: 'olivia.khan@example.com',
      phone: '+351 716 908632',
      date_of_birth: '1991-10-24',
      nationality: 'FI',
      country_of_residence: 'PT',
      address_line1: 'Rue Royale 45',
      address_line2: null,
      city: 'Lisbon',
      postal_code: '1100',
      country: 'PT',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(87),
      updated_at: daysAgo(18),
    },
    {
      id: 56,
      first_name: 'Hugo',
      last_name: 'Jensen',
      email: 'hugo.jensen@example.com',
      phone: '+420 667 916880',
      date_of_birth: '2001-09-06',
      nationality: 'SE',
      country_of_residence: 'CZ',
      address_line1: 'Damrak 160',
      address_line2: null,
      city: 'Prague',
      postal_code: '11000',
      country: 'CZ',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF1573',
      created_at: daysAgo(192),
      updated_at: daysAgo(8),
    },
    {
      id: 57,
      first_name: 'Léa',
      last_name: 'Wójcik',
      email: 'lea.wójcik@example.com',
      phone: '+47 774 280182',
      date_of_birth: '1965-01-06',
      nationality: 'IT',
      country_of_residence: 'NO',
      address_line1: 'Mannerheimintie 162',
      address_line2: null,
      city: 'Oslo',
      postal_code: '0150',
      country: 'NO',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(161),
      updated_at: daysAgo(51),
    },
    {
      id: 58,
      first_name: 'Jonas',
      last_name: 'Andersen',
      email: 'jonas.andersen@example.com',
      phone: '+39 696 976717',
      date_of_birth: '1984-01-26',
      nationality: 'BE',
      country_of_residence: 'IT',
      address_line1: 'Rue Royale 22',
      address_line2: null,
      city: 'Rome',
      postal_code: '00184',
      country: 'IT',
      onboarding_status: 'APPROVED',
      risk_rating: 'HIGH',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(136),
      updated_at: daysAgo(124),
    },
    {
      id: 59,
      first_name: 'Priya',
      last_name: 'Haddad',
      email: 'priya.haddad@example.com',
      phone: '+34 680 405795',
      date_of_birth: '1983-06-02',
      nationality: 'BE',
      country_of_residence: 'ES',
      address_line1: 'Nørregade 24',
      address_line2: null,
      city: 'Madrid',
      postal_code: '28013',
      country: 'ES',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(137),
      updated_at: daysAgo(29),
    },
    {
      id: 60,
      first_name: 'Mateo',
      last_name: 'Berg',
      email: 'mateo.berg@example.com',
      phone: '+48 683 670520',
      date_of_birth: '1971-12-06',
      nationality: 'FI',
      country_of_residence: 'PL',
      address_line1: 'Karl Johans gate 93',
      address_line2: null,
      city: 'Warsaw',
      postal_code: '00-001',
      country: 'PL',
      onboarding_status: 'STARTED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(161),
      updated_at: daysAgo(100),
    },
    {
      id: 61,
      first_name: 'Ingrid',
      last_name: 'Demir',
      email: 'ingrid.demir@example.com',
      phone: '+45 674 514481',
      date_of_birth: '1967-06-10',
      nationality: 'IT',
      country_of_residence: 'DK',
      address_line1: 'Calle Mayor 58',
      address_line2: null,
      city: 'Copenhagen',
      postal_code: '1050',
      country: 'DK',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF1389',
      created_at: daysAgo(96),
      updated_at: daysAgo(38),
    },
    {
      id: 62,
      first_name: 'Youssef',
      last_name: 'Santos',
      email: 'youssef.santos@example.com',
      phone: '+43 712 213797',
      date_of_birth: '1969-10-07',
      nationality: 'DK',
      country_of_residence: 'AT',
      address_line1: 'Calle Mayor 139',
      address_line2: null,
      city: 'Vienna',
      postal_code: '1010',
      country: 'AT',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(74),
      updated_at: daysAgo(53),
    },
    {
      id: 63,
      first_name: 'Anna',
      last_name: 'Müller',
      email: 'anna.muller@example.com',
      phone: '+47 785 940438',
      date_of_birth: '1994-10-18',
      nationality: 'SE',
      country_of_residence: 'NO',
      address_line1: 'Storgatan 22',
      address_line2: 'Apt 29',
      city: 'Oslo',
      postal_code: '0150',
      country: 'NO',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: true,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(170),
      updated_at: daysAgo(88),
    },
    {
      id: 64,
      first_name: 'Marco',
      last_name: 'Kowalski',
      email: 'marco.kowalski@example.com',
      phone: '+34 683 995240',
      date_of_birth: '1998-09-01',
      nationality: 'BE',
      country_of_residence: 'ES',
      address_line1: 'Mannerheimintie 43',
      address_line2: null,
      city: 'Barcelona',
      postal_code: '08001',
      country: 'ES',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(110),
      updated_at: daysAgo(43),
    },
    {
      id: 65,
      first_name: 'Fatima',
      last_name: 'Petrov',
      email: 'fatima.petrov@example.com',
      phone: '+34 611 940611',
      date_of_birth: '1976-08-10',
      nationality: 'BE',
      country_of_residence: 'ES',
      address_line1: 'Nørregade 132',
      address_line2: 'Apt 13',
      city: 'Barcelona',
      postal_code: '08001',
      country: 'ES',
      onboarding_status: 'STARTED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(157),
      updated_at: daysAgo(16),
    },
    {
      id: 66,
      first_name: 'Erik',
      last_name: 'Fischer',
      email: 'erik.fischer@example.com',
      phone: '+98 785 670189',
      date_of_birth: '1993-04-05',
      nationality: 'DE',
      country_of_residence: 'IR',
      address_line1: 'Hauptstraße 140',
      address_line2: null,
      city: 'Tehran',
      postal_code: '11369',
      country: 'IR',
      onboarding_status: 'REJECTED',
      risk_rating: 'HIGH',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(156),
      updated_at: daysAgo(12),
    },
    {
      id: 67,
      first_name: 'Chloé',
      last_name: 'Ivanov',
      email: 'chloe.ivanov@example.com',
      phone: '+34 747 966579',
      date_of_birth: '1982-06-11',
      nationality: 'FR',
      country_of_residence: 'ES',
      address_line1: 'Mannerheimintie 104',
      address_line2: null,
      city: 'Madrid',
      postal_code: '28013',
      country: 'ES',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(75),
      updated_at: daysAgo(6),
    },
    {
      id: 68,
      first_name: 'Viktor',
      last_name: 'Eriksson',
      email: 'viktor.eriksson@example.com',
      phone: '+49 676 289078',
      date_of_birth: '1979-10-04',
      nationality: 'SE',
      country_of_residence: 'DE',
      address_line1: 'Calle Mayor 171',
      address_line2: null,
      city: 'Hamburg',
      postal_code: '20095',
      country: 'DE',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(175),
      updated_at: daysAgo(17),
    },
    {
      id: 69,
      first_name: 'Aisha',
      last_name: 'Dubois',
      email: 'aisha.dubois@example.com',
      phone: '+420 684 472291',
      date_of_birth: '1966-10-19',
      nationality: 'SE',
      country_of_residence: 'CZ',
      address_line1: 'Mannerheimintie 169',
      address_line2: null,
      city: 'Prague',
      postal_code: '11000',
      country: 'CZ',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(134),
      updated_at: daysAgo(35),
    },
    {
      id: 70,
      first_name: 'Daniel',
      last_name: 'Sharma',
      email: 'daniel.sharma@example.com',
      phone: '+358 785 442006',
      date_of_birth: '2001-03-26',
      nationality: 'NL',
      country_of_residence: 'FI',
      address_line1: 'Calle Mayor 72',
      address_line2: null,
      city: 'Helsinki',
      postal_code: '00100',
      country: 'FI',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(166),
      updated_at: daysAgo(152),
    },
    {
      id: 71,
      first_name: 'Elena',
      last_name: 'Mensah',
      email: 'elena.mensah@example.com',
      phone: '+351 618 820216',
      date_of_birth: '1983-01-22',
      nationality: 'PT',
      country_of_residence: 'PT',
      address_line1: 'Nørregade 85',
      address_line2: null,
      city: 'Lisbon',
      postal_code: '1100',
      country: 'PT',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF8929',
      created_at: daysAgo(84),
      updated_at: daysAgo(13),
    },
    {
      id: 72,
      first_name: 'Tomas',
      last_name: 'Marchetti',
      email: 'tomas.marchetti@example.com',
      phone: '+351 756 606674',
      date_of_birth: '1969-06-05',
      nationality: 'IE',
      country_of_residence: 'PT',
      address_line1: 'Mannerheimintie 103',
      address_line2: 'Apt 11',
      city: 'Lisbon',
      postal_code: '1100',
      country: 'PT',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(215),
      updated_at: daysAgo(149),
    },
    {
      id: 73,
      first_name: 'Nadia',
      last_name: 'Kovač',
      email: 'nadia.kovac@example.com',
      phone: '+45 629 995722',
      date_of_birth: '2002-07-09',
      nationality: 'PL',
      country_of_residence: 'DK',
      address_line1: 'Calle Mayor 46',
      address_line2: null,
      city: 'Copenhagen',
      postal_code: '1050',
      country: 'DK',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(146),
      updated_at: daysAgo(15),
    },
    {
      id: 74,
      first_name: 'Pablo',
      last_name: 'Popescu',
      email: 'pablo.popescu@example.com',
      phone: '+420 633 933923',
      date_of_birth: '1979-07-19',
      nationality: 'CZ',
      country_of_residence: 'CZ',
      address_line1: 'Calle Mayor 134',
      address_line2: null,
      city: 'Prague',
      postal_code: '11000',
      country: 'CZ',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(71),
      updated_at: daysAgo(4),
    },
    {
      id: 75,
      first_name: 'Greta',
      last_name: 'García',
      email: 'greta.garcía@example.com',
      phone: '+34 752 556995',
      date_of_birth: '1973-04-17',
      nationality: 'PT',
      country_of_residence: 'ES',
      address_line1: 'Storgatan 170',
      address_line2: 'Apt 2',
      city: 'Barcelona',
      postal_code: '08001',
      country: 'ES',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: true,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(185),
      updated_at: daysAgo(154),
    },
    {
      id: 76,
      first_name: 'Kemal',
      last_name: 'Lindqvist',
      email: 'kemal.lindqvist@example.com',
      phone: '+45 790 784659',
      date_of_birth: '1969-04-09',
      nationality: 'IT',
      country_of_residence: 'DK',
      address_line1: 'Storgatan 179',
      address_line2: null,
      city: 'Copenhagen',
      postal_code: '1050',
      country: 'DK',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(190),
      updated_at: daysAgo(24),
    },
    {
      id: 77,
      first_name: 'Sara',
      last_name: 'Ahmadi',
      email: 'sara.ahmadi@example.com',
      phone: '+46 651 388655',
      date_of_birth: '1992-03-25',
      nationality: 'BE',
      country_of_residence: 'SE',
      address_line1: 'Rue Royale 24',
      address_line2: 'Apt 21',
      city: 'Stockholm',
      postal_code: '11129',
      country: 'SE',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(215),
      updated_at: daysAgo(163),
    },
    {
      id: 78,
      first_name: 'Andrei',
      last_name: 'Olsen',
      email: 'andrei.olsen@example.com',
      phone: '+47 798 724656',
      date_of_birth: '1977-09-05',
      nationality: 'ES',
      country_of_residence: 'NO',
      address_line1: 'Rue de la Paix 151',
      address_line2: null,
      city: 'Oslo',
      postal_code: '0150',
      country: 'NO',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(74),
      updated_at: daysAgo(45),
    },
    {
      id: 79,
      first_name: 'Maja',
      last_name: 'Moreau',
      email: 'maja.moreau@example.com',
      phone: '+963 742 740642',
      date_of_birth: '1962-04-14',
      nationality: 'FI',
      country_of_residence: 'SY',
      address_line1: 'Rue de la Paix 158',
      address_line2: null,
      city: 'Damascus',
      postal_code: '00963',
      country: 'SY',
      onboarding_status: 'APPROVED',
      risk_rating: 'HIGH',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF6358',
      created_at: daysAgo(156),
      updated_at: daysAgo(79),
    },
    {
      id: 80,
      first_name: 'Stefan',
      last_name: 'Johansson',
      email: 'stefan.johansson@example.com',
      phone: '+420 622 988819',
      date_of_birth: '1998-07-01',
      nationality: 'IE',
      country_of_residence: 'CZ',
      address_line1: 'Karl Johans gate 37',
      address_line2: null,
      city: 'Prague',
      postal_code: '11000',
      country: 'CZ',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF4726',
      created_at: daysAgo(177),
      updated_at: daysAgo(26),
    },
    {
      id: 81,
      first_name: 'Camille',
      last_name: 'Schneider',
      email: 'camille.schneider@example.com',
      phone: '+47 783 907239',
      date_of_birth: '1963-11-10',
      nationality: 'ES',
      country_of_residence: 'NO',
      address_line1: 'Nørregade 169',
      address_line2: null,
      city: 'Oslo',
      postal_code: '0150',
      country: 'NO',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF2580',
      created_at: daysAgo(89),
      updated_at: daysAgo(67),
    },
    {
      id: 82,
      first_name: 'Dimitri',
      last_name: 'Novak',
      email: 'dimitri.novak@example.com',
      phone: '+420 778 554357',
      date_of_birth: '1985-04-03',
      nationality: 'AT',
      country_of_residence: 'CZ',
      address_line1: 'Mannerheimintie 6',
      address_line2: null,
      city: 'Prague',
      postal_code: '11000',
      country: 'CZ',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(190),
      updated_at: daysAgo(93),
    },
    {
      id: 83,
      first_name: 'Zofia',
      last_name: 'Romano',
      email: 'zofia.romano@example.com',
      phone: '+358 727 252789',
      date_of_birth: '1966-02-13',
      nationality: 'SE',
      country_of_residence: 'FI',
      address_line1: 'Via Roma 146',
      address_line2: null,
      city: 'Helsinki',
      postal_code: '00100',
      country: 'FI',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(118),
      updated_at: daysAgo(4),
    },
    {
      id: 84,
      first_name: 'Omar',
      last_name: 'Vargas',
      email: 'omar.vargas@example.com',
      phone: '+33 648 325718',
      date_of_birth: '1972-07-16',
      nationality: 'CZ',
      country_of_residence: 'FR',
      address_line1: 'Rue Royale 124',
      address_line2: null,
      city: 'Paris',
      postal_code: '75001',
      country: 'FR',
      onboarding_status: 'STARTED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(186),
      updated_at: daysAgo(83),
    },
    {
      id: 85,
      first_name: 'Linnea',
      last_name: 'Hassan',
      email: 'linnea.hassan@example.com',
      phone: '+33 609 927474',
      date_of_birth: '1995-03-02',
      nationality: 'DK',
      country_of_residence: 'FR',
      address_line1: 'Rue Royale 88',
      address_line2: null,
      city: 'Marseille',
      postal_code: '13001',
      country: 'FR',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(87),
      updated_at: daysAgo(65),
    },
    {
      id: 86,
      first_name: 'Rafael',
      last_name: 'Rossi',
      email: 'rafael.rossi@example.com',
      phone: '+48 736 745874',
      date_of_birth: '1988-06-01',
      nationality: 'ES',
      country_of_residence: 'PL',
      address_line1: 'Nørregade 44',
      address_line2: null,
      city: 'Warsaw',
      postal_code: '00-001',
      country: 'PL',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF6978',
      created_at: daysAgo(219),
      updated_at: daysAgo(35),
    },
    {
      id: 87,
      first_name: 'Yara',
      last_name: 'Ferretti',
      email: 'yara.ferretti@example.com',
      phone: '+353 648 883949',
      date_of_birth: '1986-01-06',
      nationality: 'NO',
      country_of_residence: 'IE',
      address_line1: 'Karl Johans gate 49',
      address_line2: null,
      city: 'Dublin',
      postal_code: 'D01',
      country: 'IE',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(182),
      updated_at: daysAgo(108),
    },
    {
      id: 88,
      first_name: 'Janusz',
      last_name: 'Bianchi',
      email: 'janusz.bianchi@example.com',
      phone: '+33 625 271013',
      date_of_birth: '1996-02-05',
      nationality: 'PT',
      country_of_residence: 'FR',
      address_line1: 'Calle Mayor 58',
      address_line2: null,
      city: 'Lyon',
      postal_code: '69001',
      country: 'FR',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(75),
      updated_at: daysAgo(44),
    },
    {
      id: 89,
      first_name: 'Beatriz',
      last_name: 'Sørensen',
      email: 'beatriz.sorensen@example.com',
      phone: '+46 758 141922',
      date_of_birth: '1979-05-17',
      nationality: 'ES',
      country_of_residence: 'SE',
      address_line1: 'Hauptstraße 88',
      address_line2: null,
      city: 'Gothenburg',
      postal_code: '41103',
      country: 'SE',
      onboarding_status: 'PENDING_REVIEW',
      risk_rating: 'HIGH',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF5253',
      created_at: daysAgo(81),
      updated_at: daysAgo(71),
    },
    {
      id: 90,
      first_name: 'Henrik',
      last_name: 'Lefebvre',
      email: 'henrik.lefebvre@example.com',
      phone: '+351 630 893923',
      date_of_birth: '1999-01-12',
      nationality: 'CZ',
      country_of_residence: 'PT',
      address_line1: 'Calle Mayor 99',
      address_line2: null,
      city: 'Lisbon',
      postal_code: '1100',
      country: 'PT',
      onboarding_status: 'PENDING_REVIEW',
      risk_rating: 'HIGH',
      is_pep: true,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(161),
      updated_at: daysAgo(78),
    },
    {
      id: 91,
      first_name: 'Amara',
      last_name: 'Lopez',
      email: 'amara.lopez@example.com',
      phone: '+375 707 268926',
      date_of_birth: '1992-04-19',
      nationality: 'NO',
      country_of_residence: 'BY',
      address_line1: 'Mannerheimintie 75',
      address_line2: null,
      city: 'Minsk',
      postal_code: '220000',
      country: 'BY',
      onboarding_status: 'APPROVED',
      risk_rating: 'HIGH',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(190),
      updated_at: daysAgo(58),
    },
    {
      id: 92,
      first_name: 'Niko',
      last_name: 'Nowak',
      email: 'niko.nowak@example.com',
      phone: '+351 650 139441',
      date_of_birth: '1986-11-15',
      nationality: 'NO',
      country_of_residence: 'PT',
      address_line1: 'Karl Johans gate 118',
      address_line2: null,
      city: 'Lisbon',
      postal_code: '1100',
      country: 'PT',
      onboarding_status: 'STARTED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(201),
      updated_at: daysAgo(75),
    },
    {
      id: 93,
      first_name: 'Wei',
      last_name: 'Weber',
      email: 'wei.weber@example.com',
      phone: '+34 745 144649',
      date_of_birth: '1993-09-12',
      nationality: 'BE',
      country_of_residence: 'ES',
      address_line1: 'Rue de la Paix 72',
      address_line2: null,
      city: 'Madrid',
      postal_code: '28013',
      country: 'ES',
      onboarding_status: 'PENDING_REVIEW',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF9936',
      created_at: daysAgo(123),
      updated_at: daysAgo(30),
    },
    {
      id: 94,
      first_name: 'Ravi',
      last_name: 'Costa',
      email: 'ravi.costa@example.com',
      phone: '+43 728 116200',
      date_of_birth: '2002-03-02',
      nationality: 'SE',
      country_of_residence: 'AT',
      address_line1: 'Storgatan 174',
      address_line2: 'Apt 11',
      city: 'Vienna',
      postal_code: '1010',
      country: 'AT',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(176),
      updated_at: daysAgo(3),
    },
    {
      id: 95,
      first_name: 'Sasha',
      last_name: 'Khan',
      email: 'sasha.khan@example.com',
      phone: '+351 773 957144',
      date_of_birth: '1990-03-22',
      nationality: 'FR',
      country_of_residence: 'PT',
      address_line1: 'Marszałkowska 100',
      address_line2: null,
      city: 'Lisbon',
      postal_code: '1100',
      country: 'PT',
      onboarding_status: 'REJECTED',
      risk_rating: 'HIGH',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(121),
      updated_at: daysAgo(30),
    },
    {
      id: 96,
      first_name: 'Lena',
      last_name: 'Jensen',
      email: 'lena.jensen@example.com',
      phone: '+48 733 713036',
      date_of_birth: '1984-08-16',
      nationality: 'DK',
      country_of_residence: 'PL',
      address_line1: 'Rue de la Paix 38',
      address_line2: null,
      city: 'Warsaw',
      postal_code: '00-001',
      country: 'PL',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(192),
      updated_at: daysAgo(32),
    },
    {
      id: 97,
      first_name: 'Emma',
      last_name: 'Wójcik',
      email: 'emma.wójcik@example.com',
      phone: '+39 733 724551',
      date_of_birth: '1981-11-25',
      nationality: 'FR',
      country_of_residence: 'IT',
      address_line1: 'Mannerheimintie 171',
      address_line2: 'Apt 8',
      city: 'Rome',
      postal_code: '00184',
      country: 'IT',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(123),
      updated_at: daysAgo(38),
    },
    {
      id: 98,
      first_name: 'Lucas',
      last_name: 'Andersen',
      email: 'lucas.andersen@example.com',
      phone: '+32 733 448393',
      date_of_birth: '1980-02-02',
      nationality: 'SE',
      country_of_residence: 'BE',
      address_line1: 'Calle Mayor 22',
      address_line2: 'Apt 14',
      city: 'Brussels',
      postal_code: '1000',
      country: 'BE',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(104),
      updated_at: daysAgo(55),
    },
    {
      id: 99,
      first_name: 'Sofia',
      last_name: 'Haddad',
      email: 'sofia.haddad@example.com',
      phone: '+49 650 749426',
      date_of_birth: '1989-12-10',
      nationality: 'NL',
      country_of_residence: 'DE',
      address_line1: 'Damrak 25',
      address_line2: 'Apt 10',
      city: 'Berlin',
      postal_code: '10117',
      country: 'DE',
      onboarding_status: 'PENDING_REVIEW',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(81),
      updated_at: daysAgo(10),
    },
    {
      id: 100,
      first_name: 'Liam',
      last_name: 'Berg',
      email: 'liam.berg@example.com',
      phone: '+34 644 302847',
      date_of_birth: '1976-04-26',
      nationality: 'NL',
      country_of_residence: 'ES',
      address_line1: 'Storgatan 33',
      address_line2: null,
      city: 'Barcelona',
      postal_code: '08001',
      country: 'ES',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF3710',
      created_at: daysAgo(175),
      updated_at: daysAgo(164),
    },
    {
      id: 101,
      first_name: 'Mia',
      last_name: 'Demir',
      email: 'mia.demir@example.com',
      phone: '+963 685 910420',
      date_of_birth: '1963-08-18',
      nationality: 'FI',
      country_of_residence: 'SY',
      address_line1: 'Mannerheimintie 163',
      address_line2: 'Apt 10',
      city: 'Damascus',
      postal_code: '00963',
      country: 'SY',
      onboarding_status: 'REJECTED',
      risk_rating: 'HIGH',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF4048',
      created_at: daysAgo(161),
      updated_at: daysAgo(43),
    },
    {
      id: 102,
      first_name: 'Noah',
      last_name: 'Santos',
      email: 'noah.santos@example.com',
      phone: '+7 737 504122',
      date_of_birth: '1970-11-17',
      nationality: 'SE',
      country_of_residence: 'RU',
      address_line1: 'Karl Johans gate 159',
      address_line2: null,
      city: 'Moscow',
      postal_code: '101000',
      country: 'RU',
      onboarding_status: 'REJECTED',
      risk_rating: 'HIGH',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(81),
      updated_at: daysAgo(31),
    },
    {
      id: 103,
      first_name: 'Olivia',
      last_name: 'Müller',
      email: 'olivia.muller@example.com',
      phone: '+7 712 120284',
      date_of_birth: '1990-04-04',
      nationality: 'IE',
      country_of_residence: 'RU',
      address_line1: 'Rue de la Paix 43',
      address_line2: null,
      city: 'Moscow',
      postal_code: '101000',
      country: 'RU',
      onboarding_status: 'PENDING_REVIEW',
      risk_rating: 'HIGH',
      is_pep: true,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(156),
      updated_at: daysAgo(113),
    },
    {
      id: 104,
      first_name: 'Hugo',
      last_name: 'Kowalski',
      email: 'hugo.kowalski@example.com',
      phone: '+49 713 293809',
      date_of_birth: '1988-03-16',
      nationality: 'DE',
      country_of_residence: 'DE',
      address_line1: 'Storgatan 73',
      address_line2: null,
      city: 'Hamburg',
      postal_code: '20095',
      country: 'DE',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF1428',
      created_at: daysAgo(213),
      updated_at: daysAgo(128),
    },
    {
      id: 105,
      first_name: 'Léa',
      last_name: 'Petrov',
      email: 'lea.petrov@example.com',
      phone: '+46 710 104968',
      date_of_birth: '1991-06-14',
      nationality: 'CZ',
      country_of_residence: 'SE',
      address_line1: 'Mannerheimintie 137',
      address_line2: null,
      city: 'Gothenburg',
      postal_code: '41103',
      country: 'SE',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(76),
      updated_at: daysAgo(59),
    },
    {
      id: 106,
      first_name: 'Jonas',
      last_name: 'Fischer',
      email: 'jonas.fischer@example.com',
      phone: '+43 663 340152',
      date_of_birth: '1982-12-28',
      nationality: 'BE',
      country_of_residence: 'AT',
      address_line1: 'Damrak 132',
      address_line2: null,
      city: 'Vienna',
      postal_code: '1010',
      country: 'AT',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: true,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(148),
      updated_at: daysAgo(4),
    },
    {
      id: 107,
      first_name: 'Priya',
      last_name: 'Ivanov',
      email: 'priya.ivanov@example.com',
      phone: '+46 676 305267',
      date_of_birth: '1994-01-13',
      nationality: 'ES',
      country_of_residence: 'SE',
      address_line1: 'Nørregade 86',
      address_line2: null,
      city: 'Gothenburg',
      postal_code: '41103',
      country: 'SE',
      onboarding_status: 'PENDING_REVIEW',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(204),
      updated_at: daysAgo(92),
    },
    {
      id: 108,
      first_name: 'Mateo',
      last_name: 'Eriksson',
      email: 'mateo.eriksson@example.com',
      phone: '+7 798 417283',
      date_of_birth: '1996-01-21',
      nationality: 'DE',
      country_of_residence: 'RU',
      address_line1: 'Mannerheimintie 54',
      address_line2: null,
      city: 'Moscow',
      postal_code: '101000',
      country: 'RU',
      onboarding_status: 'REJECTED',
      risk_rating: 'HIGH',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF5992',
      created_at: daysAgo(171),
      updated_at: daysAgo(53),
    },
    {
      id: 109,
      first_name: 'Ingrid',
      last_name: 'Dubois',
      email: 'ingrid.dubois@example.com',
      phone: '+353 703 669042',
      date_of_birth: '1987-03-14',
      nationality: 'ES',
      country_of_residence: 'IE',
      address_line1: 'Hauptstraße 123',
      address_line2: 'Apt 1',
      city: 'Dublin',
      postal_code: 'D01',
      country: 'IE',
      onboarding_status: 'PENDING_REVIEW',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(185),
      updated_at: daysAgo(134),
    },
    {
      id: 110,
      first_name: 'Youssef',
      last_name: 'Sharma',
      email: 'youssef.sharma@example.com',
      phone: '+46 649 982884',
      date_of_birth: '1977-12-02',
      nationality: 'ES',
      country_of_residence: 'SE',
      address_line1: 'Storgatan 111',
      address_line2: null,
      city: 'Gothenburg',
      postal_code: '41103',
      country: 'SE',
      onboarding_status: 'STARTED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF6001',
      created_at: daysAgo(121),
      updated_at: daysAgo(57),
    },
    {
      id: 111,
      first_name: 'Anna',
      last_name: 'Mensah',
      email: 'anna.mensah@example.com',
      phone: '+31 738 670801',
      date_of_birth: '1982-05-03',
      nationality: 'BE',
      country_of_residence: 'NL',
      address_line1: 'Rue Royale 99',
      address_line2: 'Apt 34',
      city: 'Amsterdam',
      postal_code: '1011',
      country: 'NL',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(200),
      updated_at: daysAgo(173),
    },
    {
      id: 112,
      first_name: 'Marco',
      last_name: 'Marchetti',
      email: 'marco.marchetti@example.com',
      phone: '+358 730 582748',
      date_of_birth: '1991-06-24',
      nationality: 'PL',
      country_of_residence: 'FI',
      address_line1: 'Storgatan 79',
      address_line2: null,
      city: 'Helsinki',
      postal_code: '00100',
      country: 'FI',
      onboarding_status: 'PENDING_REVIEW',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF1394',
      created_at: daysAgo(101),
      updated_at: daysAgo(58),
    },
    {
      id: 113,
      first_name: 'Fatima',
      last_name: 'Kovač',
      email: 'fatima.kovac@example.com',
      phone: '+358 641 152854',
      date_of_birth: '1984-03-02',
      nationality: 'AT',
      country_of_residence: 'FI',
      address_line1: 'Marszałkowska 67',
      address_line2: null,
      city: 'Helsinki',
      postal_code: '00100',
      country: 'FI',
      onboarding_status: 'REJECTED',
      risk_rating: 'HIGH',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(106),
      updated_at: daysAgo(11),
    },
    {
      id: 114,
      first_name: 'Erik',
      last_name: 'Popescu',
      email: 'erik.popescu@example.com',
      phone: '+47 621 305428',
      date_of_birth: '1968-09-01',
      nationality: 'AT',
      country_of_residence: 'NO',
      address_line1: 'Calle Mayor 157',
      address_line2: null,
      city: 'Oslo',
      postal_code: '0150',
      country: 'NO',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(65),
      updated_at: daysAgo(31),
    },
    {
      id: 115,
      first_name: 'Chloé',
      last_name: 'García',
      email: 'chloe.garcía@example.com',
      phone: '+48 777 306653',
      date_of_birth: '1963-06-04',
      nationality: 'CZ',
      country_of_residence: 'PL',
      address_line1: 'Hauptstraße 51',
      address_line2: null,
      city: 'Warsaw',
      postal_code: '00-001',
      country: 'PL',
      onboarding_status: 'PENDING_REVIEW',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(200),
      updated_at: daysAgo(153),
    },
    {
      id: 116,
      first_name: 'Viktor',
      last_name: 'Lindqvist',
      email: 'viktor.lindqvist@example.com',
      phone: '+420 784 112064',
      date_of_birth: '1991-10-17',
      nationality: 'CZ',
      country_of_residence: 'CZ',
      address_line1: 'Marszałkowska 32',
      address_line2: 'Apt 23',
      city: 'Prague',
      postal_code: '11000',
      country: 'CZ',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(66),
      updated_at: daysAgo(9),
    },
    {
      id: 117,
      first_name: 'Aisha',
      last_name: 'Ahmadi',
      email: 'aisha.ahmadi@example.com',
      phone: '+31 728 284531',
      date_of_birth: '1974-02-09',
      nationality: 'AT',
      country_of_residence: 'NL',
      address_line1: 'Calle Mayor 135',
      address_line2: null,
      city: 'Amsterdam',
      postal_code: '1011',
      country: 'NL',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF5209',
      created_at: daysAgo(139),
      updated_at: daysAgo(82),
    },
    {
      id: 118,
      first_name: 'Daniel',
      last_name: 'Olsen',
      email: 'daniel.olsen@example.com',
      phone: '+46 765 419113',
      date_of_birth: '1987-08-28',
      nationality: 'FI',
      country_of_residence: 'SE',
      address_line1: 'Hauptstraße 168',
      address_line2: 'Apt 23',
      city: 'Stockholm',
      postal_code: '11129',
      country: 'SE',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: true,
      is_sanctioned: false,
      referral_code: 'REF5005',
      created_at: daysAgo(90),
      updated_at: daysAgo(45),
    },
    {
      id: 119,
      first_name: 'Elena',
      last_name: 'Moreau',
      email: 'elena.moreau@example.com',
      phone: '+45 792 901366',
      date_of_birth: '1995-12-02',
      nationality: 'BE',
      country_of_residence: 'DK',
      address_line1: 'Storgatan 145',
      address_line2: null,
      city: 'Copenhagen',
      postal_code: '1050',
      country: 'DK',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(123),
      updated_at: daysAgo(94),
    },
    {
      id: 120,
      first_name: 'Tomas',
      last_name: 'Johansson',
      email: 'tomas.johansson@example.com',
      phone: '+93 727 722748',
      date_of_birth: '1989-03-19',
      nationality: 'FI',
      country_of_residence: 'AF',
      address_line1: 'Mannerheimintie 18',
      address_line2: null,
      city: 'Kabul',
      postal_code: '1001',
      country: 'AF',
      onboarding_status: 'PENDING_REVIEW',
      risk_rating: 'HIGH',
      is_pep: false,
      is_sanctioned: true,
      referral_code: null,
      created_at: daysAgo(197),
      updated_at: daysAgo(123),
    },
    {
      id: 121,
      first_name: 'Nadia',
      last_name: 'Schneider',
      email: 'nadia.schneider@example.com',
      phone: '+95 797 381195',
      date_of_birth: '1966-02-20',
      nationality: 'IE',
      country_of_residence: 'MM',
      address_line1: 'Damrak 64',
      address_line2: null,
      city: 'Yangon',
      postal_code: '11181',
      country: 'MM',
      onboarding_status: 'REJECTED',
      risk_rating: 'HIGH',
      is_pep: true,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(117),
      updated_at: daysAgo(73),
    },
    {
      id: 122,
      first_name: 'Pablo',
      last_name: 'Novak',
      email: 'pablo.novak@example.com',
      phone: '+358 734 214726',
      date_of_birth: '1985-10-12',
      nationality: 'FR',
      country_of_residence: 'FI',
      address_line1: 'Karl Johans gate 67',
      address_line2: null,
      city: 'Helsinki',
      postal_code: '00100',
      country: 'FI',
      onboarding_status: 'PENDING_REVIEW',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(204),
      updated_at: daysAgo(136),
    },
    {
      id: 123,
      first_name: 'Greta',
      last_name: 'Romano',
      email: 'greta.romano@example.com',
      phone: '+33 679 114301',
      date_of_birth: '1995-09-19',
      nationality: 'FI',
      country_of_residence: 'FR',
      address_line1: 'Via Roma 46',
      address_line2: null,
      city: 'Marseille',
      postal_code: '13001',
      country: 'FR',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(155),
      updated_at: daysAgo(122),
    },
    {
      id: 124,
      first_name: 'Kemal',
      last_name: 'Vargas',
      email: 'kemal.vargas@example.com',
      phone: '+33 669 177352',
      date_of_birth: '1978-02-02',
      nationality: 'PL',
      country_of_residence: 'FR',
      address_line1: 'Nørregade 16',
      address_line2: 'Apt 36',
      city: 'Lyon',
      postal_code: '69001',
      country: 'FR',
      onboarding_status: 'REJECTED',
      risk_rating: 'HIGH',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(64),
      updated_at: daysAgo(5),
    },
    {
      id: 125,
      first_name: 'Sara',
      last_name: 'Hassan',
      email: 'sara.hassan@example.com',
      phone: '+98 719 744175',
      date_of_birth: '1985-11-11',
      nationality: 'FI',
      country_of_residence: 'IR',
      address_line1: 'Via Roma 178',
      address_line2: null,
      city: 'Tehran',
      postal_code: '11369',
      country: 'IR',
      onboarding_status: 'PENDING_REVIEW',
      risk_rating: 'HIGH',
      is_pep: true,
      is_sanctioned: true,
      referral_code: 'REF6575',
      created_at: daysAgo(111),
      updated_at: daysAgo(101),
    },
    {
      id: 126,
      first_name: 'Andrei',
      last_name: 'Rossi',
      email: 'andrei.rossi@example.com',
      phone: '+33 610 643030',
      date_of_birth: '1968-12-20',
      nationality: 'PL',
      country_of_residence: 'FR',
      address_line1: 'Via Roma 121',
      address_line2: 'Apt 20',
      city: 'Lyon',
      postal_code: '69001',
      country: 'FR',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF2093',
      created_at: daysAgo(215),
      updated_at: daysAgo(83),
    },
    {
      id: 127,
      first_name: 'Maja',
      last_name: 'Ferretti',
      email: 'maja.ferretti@example.com',
      phone: '+95 620 791807',
      date_of_birth: '1997-08-26',
      nationality: 'FR',
      country_of_residence: 'MM',
      address_line1: 'Rue de la Paix 61',
      address_line2: null,
      city: 'Yangon',
      postal_code: '11181',
      country: 'MM',
      onboarding_status: 'PENDING_REVIEW',
      risk_rating: 'HIGH',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(168),
      updated_at: daysAgo(77),
    },
    {
      id: 128,
      first_name: 'Stefan',
      last_name: 'Bianchi',
      email: 'stefan.bianchi@example.com',
      phone: '+33 656 106003',
      date_of_birth: '1998-07-06',
      nationality: 'DE',
      country_of_residence: 'FR',
      address_line1: 'Hauptstraße 155',
      address_line2: null,
      city: 'Lyon',
      postal_code: '69001',
      country: 'FR',
      onboarding_status: 'PENDING_REVIEW',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(175),
      updated_at: daysAgo(71),
    },
    {
      id: 129,
      first_name: 'Camille',
      last_name: 'Sørensen',
      email: 'camille.sorensen@example.com',
      phone: '+963 627 213944',
      date_of_birth: '1971-04-06',
      nationality: 'NL',
      country_of_residence: 'SY',
      address_line1: 'Nørregade 32',
      address_line2: null,
      city: 'Damascus',
      postal_code: '00963',
      country: 'SY',
      onboarding_status: 'PENDING_REVIEW',
      risk_rating: 'HIGH',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(145),
      updated_at: daysAgo(42),
    },
    {
      id: 130,
      first_name: 'Dimitri',
      last_name: 'Lefebvre',
      email: 'dimitri.lefebvre@example.com',
      phone: '+420 695 327104',
      date_of_birth: '1973-08-12',
      nationality: 'AT',
      country_of_residence: 'CZ',
      address_line1: 'Marszałkowska 160',
      address_line2: null,
      city: 'Prague',
      postal_code: '11000',
      country: 'CZ',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(90),
      updated_at: daysAgo(65),
    },
    {
      id: 131,
      first_name: 'Zofia',
      last_name: 'Lopez',
      email: 'zofia.lopez@example.com',
      phone: '+358 778 464528',
      date_of_birth: '1998-04-06',
      nationality: 'FI',
      country_of_residence: 'FI',
      address_line1: 'Damrak 12',
      address_line2: null,
      city: 'Helsinki',
      postal_code: '00100',
      country: 'FI',
      onboarding_status: 'PENDING_REVIEW',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF8211',
      created_at: daysAgo(172),
      updated_at: daysAgo(36),
    },
    {
      id: 132,
      first_name: 'Omar',
      last_name: 'Nowak',
      email: 'omar.nowak@example.com',
      phone: '+420 767 817184',
      date_of_birth: '1995-02-02',
      nationality: 'PT',
      country_of_residence: 'CZ',
      address_line1: 'Nørregade 178',
      address_line2: null,
      city: 'Prague',
      postal_code: '11000',
      country: 'CZ',
      onboarding_status: 'REJECTED',
      risk_rating: 'HIGH',
      is_pep: false,
      is_sanctioned: true,
      referral_code: null,
      created_at: daysAgo(150),
      updated_at: daysAgo(33),
    },
    {
      id: 133,
      first_name: 'Linnea',
      last_name: 'Weber',
      email: 'linnea.weber@example.com',
      phone: '+43 677 530436',
      date_of_birth: '1965-01-21',
      nationality: 'PL',
      country_of_residence: 'AT',
      address_line1: 'Rue Royale 10',
      address_line2: null,
      city: 'Vienna',
      postal_code: '1010',
      country: 'AT',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(77),
      updated_at: daysAgo(38),
    },
    {
      id: 134,
      first_name: 'Rafael',
      last_name: 'Costa',
      email: 'rafael.costa@example.com',
      phone: '+33 712 206592',
      date_of_birth: '1993-04-13',
      nationality: 'AT',
      country_of_residence: 'FR',
      address_line1: 'Hauptstraße 65',
      address_line2: null,
      city: 'Paris',
      postal_code: '75001',
      country: 'FR',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(206),
      updated_at: daysAgo(178),
    },
    {
      id: 135,
      first_name: 'Yara',
      last_name: 'Khan',
      email: 'yara.khan@example.com',
      phone: '+358 625 306993',
      date_of_birth: '1974-01-19',
      nationality: 'IT',
      country_of_residence: 'FI',
      address_line1: 'Rue Royale 81',
      address_line2: null,
      city: 'Helsinki',
      postal_code: '00100',
      country: 'FI',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(215),
      updated_at: daysAgo(168),
    },
    {
      id: 136,
      first_name: 'Janusz',
      last_name: 'Jensen',
      email: 'janusz.jensen@example.com',
      phone: '+43 705 567667',
      date_of_birth: '1969-01-13',
      nationality: 'AT',
      country_of_residence: 'AT',
      address_line1: 'Marszałkowska 179',
      address_line2: null,
      city: 'Vienna',
      postal_code: '1010',
      country: 'AT',
      onboarding_status: 'PENDING_REVIEW',
      risk_rating: 'HIGH',
      is_pep: false,
      is_sanctioned: true,
      referral_code: 'REF6375',
      created_at: daysAgo(105),
      updated_at: daysAgo(16),
    },
    {
      id: 137,
      first_name: 'Beatriz',
      last_name: 'Wójcik',
      email: 'beatriz.wójcik@example.com',
      phone: '+31 726 251888',
      date_of_birth: '2003-05-09',
      nationality: 'DE',
      country_of_residence: 'NL',
      address_line1: 'Rue Royale 161',
      address_line2: null,
      city: 'Amsterdam',
      postal_code: '1011',
      country: 'NL',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(151),
      updated_at: daysAgo(104),
    },
    {
      id: 138,
      first_name: 'Henrik',
      last_name: 'Andersen',
      email: 'henrik.andersen@example.com',
      phone: '+49 615 595831',
      date_of_birth: '1993-05-26',
      nationality: 'ES',
      country_of_residence: 'DE',
      address_line1: 'Marszałkowska 161',
      address_line2: null,
      city: 'Berlin',
      postal_code: '10117',
      country: 'DE',
      onboarding_status: 'STARTED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(122),
      updated_at: daysAgo(89),
    },
    {
      id: 139,
      first_name: 'Amara',
      last_name: 'Haddad',
      email: 'amara.haddad@example.com',
      phone: '+45 649 309334',
      date_of_birth: '1998-05-11',
      nationality: 'DE',
      country_of_residence: 'DK',
      address_line1: 'Mannerheimintie 48',
      address_line2: null,
      city: 'Copenhagen',
      postal_code: '1050',
      country: 'DK',
      onboarding_status: 'STARTED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(187),
      updated_at: daysAgo(70),
    },
    {
      id: 140,
      first_name: 'Niko',
      last_name: 'Berg',
      email: 'niko.berg@example.com',
      phone: '+34 727 650760',
      date_of_birth: '1998-09-22',
      nationality: 'DE',
      country_of_residence: 'ES',
      address_line1: 'Karl Johans gate 92',
      address_line2: null,
      city: 'Barcelona',
      postal_code: '08001',
      country: 'ES',
      onboarding_status: 'PENDING_REVIEW',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF7759',
      created_at: daysAgo(110),
      updated_at: daysAgo(60),
    },
    {
      id: 141,
      first_name: 'Wei',
      last_name: 'Demir',
      email: 'wei.demir@example.com',
      phone: '+49 715 952485',
      date_of_birth: '1981-06-25',
      nationality: 'PL',
      country_of_residence: 'DE',
      address_line1: 'Calle Mayor 93',
      address_line2: null,
      city: 'Hamburg',
      postal_code: '20095',
      country: 'DE',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF1710',
      created_at: daysAgo(116),
      updated_at: daysAgo(9),
    },
    {
      id: 142,
      first_name: 'Ravi',
      last_name: 'Santos',
      email: 'ravi.santos@example.com',
      phone: '+32 760 175992',
      date_of_birth: '1982-12-02',
      nationality: 'ES',
      country_of_residence: 'BE',
      address_line1: 'Storgatan 42',
      address_line2: null,
      city: 'Brussels',
      postal_code: '1000',
      country: 'BE',
      onboarding_status: 'STARTED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF8544',
      created_at: daysAgo(169),
      updated_at: daysAgo(85),
    },
    {
      id: 143,
      first_name: 'Sasha',
      last_name: 'Müller',
      email: 'sasha.muller@example.com',
      phone: '+351 640 888774',
      date_of_birth: '1992-01-14',
      nationality: 'BE',
      country_of_residence: 'PT',
      address_line1: 'Storgatan 34',
      address_line2: null,
      city: 'Lisbon',
      postal_code: '1100',
      country: 'PT',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF4708',
      created_at: daysAgo(121),
      updated_at: daysAgo(44),
    },
    {
      id: 144,
      first_name: 'Lena',
      last_name: 'Kowalski',
      email: 'lena.kowalski@example.com',
      phone: '+420 631 833017',
      date_of_birth: '1998-10-01',
      nationality: 'FR',
      country_of_residence: 'CZ',
      address_line1: 'Rue Royale 151',
      address_line2: 'Apt 5',
      city: 'Prague',
      postal_code: '11000',
      country: 'CZ',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(164),
      updated_at: daysAgo(116),
    },
    {
      id: 145,
      first_name: 'Emma',
      last_name: 'Petrov',
      email: 'emma.petrov@example.com',
      phone: '+46 645 702443',
      date_of_birth: '1969-11-04',
      nationality: 'NL',
      country_of_residence: 'SE',
      address_line1: 'Mannerheimintie 99',
      address_line2: null,
      city: 'Stockholm',
      postal_code: '11129',
      country: 'SE',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(137),
      updated_at: daysAgo(86),
    },
    {
      id: 146,
      first_name: 'Lucas',
      last_name: 'Fischer',
      email: 'lucas.fischer@example.com',
      phone: '+46 763 317261',
      date_of_birth: '1975-11-06',
      nationality: 'CZ',
      country_of_residence: 'SE',
      address_line1: 'Mannerheimintie 45',
      address_line2: 'Apt 31',
      city: 'Stockholm',
      postal_code: '11129',
      country: 'SE',
      onboarding_status: 'PENDING_REVIEW',
      risk_rating: 'HIGH',
      is_pep: false,
      is_sanctioned: true,
      referral_code: null,
      created_at: daysAgo(187),
      updated_at: daysAgo(53),
    },
    {
      id: 147,
      first_name: 'Sofia',
      last_name: 'Ivanov',
      email: 'sofia.ivanov@example.com',
      phone: '+46 793 208969',
      date_of_birth: '1976-11-22',
      nationality: 'IE',
      country_of_residence: 'SE',
      address_line1: 'Damrak 21',
      address_line2: null,
      city: 'Stockholm',
      postal_code: '11129',
      country: 'SE',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(75),
      updated_at: daysAgo(59),
    },
    {
      id: 148,
      first_name: 'Liam',
      last_name: 'Eriksson',
      email: 'liam.eriksson@example.com',
      phone: '+45 715 214937',
      date_of_birth: '1975-09-11',
      nationality: 'SE',
      country_of_residence: 'DK',
      address_line1: 'Karl Johans gate 45',
      address_line2: 'Apt 4',
      city: 'Copenhagen',
      postal_code: '1050',
      country: 'DK',
      onboarding_status: 'APPROVED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(71),
      updated_at: daysAgo(6),
    },
    {
      id: 149,
      first_name: 'Mia',
      last_name: 'Dubois',
      email: 'mia.dubois@example.com',
      phone: '+49 601 999738',
      date_of_birth: '1992-08-19',
      nationality: 'PT',
      country_of_residence: 'DE',
      address_line1: 'Storgatan 9',
      address_line2: null,
      city: 'Hamburg',
      postal_code: '20095',
      country: 'DE',
      onboarding_status: 'APPROVED',
      risk_rating: 'MEDIUM',
      is_pep: false,
      is_sanctioned: false,
      referral_code: null,
      created_at: daysAgo(108),
      updated_at: daysAgo(81),
    },
    {
      id: 150,
      first_name: 'Noah',
      last_name: 'Sharma',
      email: 'noah.sharma@example.com',
      phone: '+420 734 564128',
      date_of_birth: '1992-07-23',
      nationality: 'CZ',
      country_of_residence: 'CZ',
      address_line1: 'Rue de la Paix 28',
      address_line2: null,
      city: 'Prague',
      postal_code: '11000',
      country: 'CZ',
      onboarding_status: 'STARTED',
      risk_rating: 'LOW',
      is_pep: false,
      is_sanctioned: false,
      referral_code: 'REF4534',
      created_at: daysAgo(94),
      updated_at: daysAgo(10),
    },
  ];

  constructor(datasource: DataSource) {
    super(datasource, 'customers', CustomersCollection.schema);
  }
}
