import type { DataSource, FieldSchema, RecordData } from '@forestadmin/datasource-toolkit';

import BaseFintechCollection from './base';
import { daysAgo } from '../dates';

export default class KycCasesCollection extends BaseFintechCollection {
  private static schema: Record<string, FieldSchema> = {
    id: {
      type: 'Column',
      columnType: 'Number',
      isPrimaryKey: true,
    },
    customer_id: {
      type: 'Column',
      columnType: 'Number',
    },
    status: {
      type: 'Column',
      columnType: 'Enum',
      enumValues: ['OPEN', 'IN_REVIEW', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'ESCALATED'],
    },
    opened_at: {
      type: 'Column',
      columnType: 'Date',
    },
    resolved_at: {
      type: 'Column',
      columnType: 'Date',
    },
    rejection_reason: {
      type: 'Column',
      columnType: 'String',
    },
    escalation_reason: {
      type: 'Column',
      columnType: 'String',
    },
    notes: {
      type: 'Column',
      columnType: 'String',
    },
  };

  protected override records: RecordData[] = [
    {
      id: 1,
      customer_id: 1,
      status: 'REJECTED',
      opened_at: daysAgo(41),
      resolved_at: daysAgo(9),
      rejection_reason: 'Sanctions concern',
      escalation_reason: null,
      notes: 'Second review scheduled.',
    },
    {
      id: 2,
      customer_id: 2,
      status: 'APPROVED',
      opened_at: daysAgo(200),
      resolved_at: daysAgo(106),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Awaiting proof of address.',
    },
    {
      id: 3,
      customer_id: 3,
      status: 'IN_REVIEW',
      opened_at: daysAgo(198),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Customer responsive.',
    },
    {
      id: 4,
      customer_id: 4,
      status: 'IN_REVIEW',
      opened_at: daysAgo(66),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Customer responsive.',
    },
    {
      id: 5,
      customer_id: 4,
      status: 'PENDING_APPROVAL',
      opened_at: daysAgo(126),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Second review scheduled.',
    },
    {
      id: 6,
      customer_id: 5,
      status: 'REJECTED',
      opened_at: daysAgo(123),
      resolved_at: daysAgo(54),
      rejection_reason: 'Document mismatch',
      escalation_reason: null,
      notes: 'Awaiting proof of address.',
    },
    {
      id: 7,
      customer_id: 6,
      status: 'APPROVED',
      opened_at: daysAgo(44),
      resolved_at: daysAgo(20),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Customer responsive.',
    },
    {
      id: 8,
      customer_id: 6,
      status: 'APPROVED',
      opened_at: daysAgo(37),
      resolved_at: daysAgo(20),
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 9,
      customer_id: 7,
      status: 'APPROVED',
      opened_at: daysAgo(180),
      resolved_at: daysAgo(26),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Source of funds requested.',
    },
    {
      id: 10,
      customer_id: 8,
      status: 'REJECTED',
      opened_at: daysAgo(51),
      resolved_at: daysAgo(4),
      rejection_reason: 'Sanctions concern',
      escalation_reason: null,
      notes: 'Customer responsive.',
    },
    {
      id: 11,
      customer_id: 9,
      status: 'APPROVED',
      opened_at: daysAgo(31),
      resolved_at: daysAgo(12),
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 12,
      customer_id: 10,
      status: 'IN_REVIEW',
      opened_at: daysAgo(178),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Source of funds requested.',
    },
    {
      id: 13,
      customer_id: 11,
      status: 'REJECTED',
      opened_at: daysAgo(51),
      resolved_at: daysAgo(36),
      rejection_reason: 'Failed liveness check',
      escalation_reason: null,
      notes: 'Awaiting proof of address.',
    },
    {
      id: 14,
      customer_id: 12,
      status: 'APPROVED',
      opened_at: daysAgo(181),
      resolved_at: daysAgo(138),
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 15,
      customer_id: 13,
      status: 'APPROVED',
      opened_at: daysAgo(161),
      resolved_at: daysAgo(51),
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 16,
      customer_id: 14,
      status: 'APPROVED',
      opened_at: daysAgo(201),
      resolved_at: daysAgo(69),
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 17,
      customer_id: 15,
      status: 'APPROVED',
      opened_at: daysAgo(168),
      resolved_at: daysAgo(28),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Awaiting proof of address.',
    },
    {
      id: 18,
      customer_id: 16,
      status: 'APPROVED',
      opened_at: daysAgo(200),
      resolved_at: daysAgo(100),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Source of funds requested.',
    },
    {
      id: 19,
      customer_id: 17,
      status: 'APPROVED',
      opened_at: daysAgo(110),
      resolved_at: daysAgo(56),
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 20,
      customer_id: 18,
      status: 'OPEN',
      opened_at: daysAgo(105),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Customer responsive.',
    },
    {
      id: 21,
      customer_id: 19,
      status: 'IN_REVIEW',
      opened_at: daysAgo(127),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 22,
      customer_id: 20,
      status: 'IN_REVIEW',
      opened_at: daysAgo(165),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Source of funds requested.',
    },
    {
      id: 23,
      customer_id: 21,
      status: 'IN_REVIEW',
      opened_at: daysAgo(194),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 24,
      customer_id: 22,
      status: 'OPEN',
      opened_at: daysAgo(37),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Customer responsive.',
    },
    {
      id: 25,
      customer_id: 23,
      status: 'IN_REVIEW',
      opened_at: daysAgo(201),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 26,
      customer_id: 24,
      status: 'APPROVED',
      opened_at: daysAgo(127),
      resolved_at: daysAgo(38),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Source of funds requested.',
    },
    {
      id: 27,
      customer_id: 25,
      status: 'IN_REVIEW',
      opened_at: daysAgo(44),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Source of funds requested.',
    },
    {
      id: 28,
      customer_id: 25,
      status: 'IN_REVIEW',
      opened_at: daysAgo(159),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 29,
      customer_id: 26,
      status: 'IN_REVIEW',
      opened_at: daysAgo(63),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Awaiting proof of address.',
    },
    {
      id: 30,
      customer_id: 27,
      status: 'APPROVED',
      opened_at: daysAgo(186),
      resolved_at: daysAgo(66),
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 31,
      customer_id: 27,
      status: 'IN_REVIEW',
      opened_at: daysAgo(170),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Awaiting proof of address.',
    },
    {
      id: 32,
      customer_id: 28,
      status: 'IN_REVIEW',
      opened_at: daysAgo(127),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 33,
      customer_id: 29,
      status: 'APPROVED',
      opened_at: daysAgo(132),
      resolved_at: daysAgo(107),
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 34,
      customer_id: 30,
      status: 'IN_REVIEW',
      opened_at: daysAgo(129),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Second review scheduled.',
    },
    {
      id: 35,
      customer_id: 31,
      status: 'PENDING_APPROVAL',
      opened_at: daysAgo(128),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 36,
      customer_id: 32,
      status: 'APPROVED',
      opened_at: daysAgo(143),
      resolved_at: daysAgo(93),
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 37,
      customer_id: 33,
      status: 'IN_REVIEW',
      opened_at: daysAgo(97),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Second review scheduled.',
    },
    {
      id: 38,
      customer_id: 34,
      status: 'ESCALATED',
      opened_at: daysAgo(206),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: 'PEP match requires senior review',
      notes: 'Second review scheduled.',
    },
    {
      id: 39,
      customer_id: 34,
      status: 'PENDING_APPROVAL',
      opened_at: daysAgo(88),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 40,
      customer_id: 35,
      status: 'REJECTED',
      opened_at: daysAgo(119),
      resolved_at: daysAgo(12),
      rejection_reason: 'Failed liveness check',
      escalation_reason: null,
      notes: 'Second review scheduled.',
    },
    {
      id: 41,
      customer_id: 35,
      status: 'REJECTED',
      opened_at: daysAgo(82),
      resolved_at: daysAgo(56),
      rejection_reason: 'Failed liveness check',
      escalation_reason: null,
      notes: null,
    },
    {
      id: 42,
      customer_id: 36,
      status: 'IN_REVIEW',
      opened_at: daysAgo(55),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 43,
      customer_id: 37,
      status: 'IN_REVIEW',
      opened_at: daysAgo(151),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 44,
      customer_id: 38,
      status: 'APPROVED',
      opened_at: daysAgo(121),
      resolved_at: daysAgo(64),
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 45,
      customer_id: 39,
      status: 'APPROVED',
      opened_at: daysAgo(208),
      resolved_at: daysAgo(56),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Source of funds requested.',
    },
    {
      id: 46,
      customer_id: 40,
      status: 'APPROVED',
      opened_at: daysAgo(126),
      resolved_at: daysAgo(72),
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 47,
      customer_id: 41,
      status: 'PENDING_APPROVAL',
      opened_at: daysAgo(173),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Source of funds requested.',
    },
    {
      id: 48,
      customer_id: 42,
      status: 'IN_REVIEW',
      opened_at: daysAgo(158),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Second review scheduled.',
    },
    {
      id: 49,
      customer_id: 43,
      status: 'PENDING_APPROVAL',
      opened_at: daysAgo(105),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Source of funds requested.',
    },
    {
      id: 50,
      customer_id: 44,
      status: 'APPROVED',
      opened_at: daysAgo(72),
      resolved_at: daysAgo(35),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Awaiting proof of address.',
    },
    {
      id: 51,
      customer_id: 45,
      status: 'IN_REVIEW',
      opened_at: daysAgo(171),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 52,
      customer_id: 46,
      status: 'APPROVED',
      opened_at: daysAgo(161),
      resolved_at: daysAgo(83),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Customer responsive.',
    },
    {
      id: 53,
      customer_id: 47,
      status: 'APPROVED',
      opened_at: daysAgo(34),
      resolved_at: daysAgo(6),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Source of funds requested.',
    },
    {
      id: 54,
      customer_id: 48,
      status: 'IN_REVIEW',
      opened_at: daysAgo(105),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Customer responsive.',
    },
    {
      id: 55,
      customer_id: 49,
      status: 'IN_REVIEW',
      opened_at: daysAgo(53),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 56,
      customer_id: 50,
      status: 'IN_REVIEW',
      opened_at: daysAgo(177),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Second review scheduled.',
    },
    {
      id: 57,
      customer_id: 51,
      status: 'REJECTED',
      opened_at: daysAgo(46),
      resolved_at: daysAgo(29),
      rejection_reason: 'Document mismatch',
      escalation_reason: null,
      notes: null,
    },
    {
      id: 58,
      customer_id: 52,
      status: 'APPROVED',
      opened_at: daysAgo(190),
      resolved_at: daysAgo(49),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Customer responsive.',
    },
    {
      id: 59,
      customer_id: 53,
      status: 'IN_REVIEW',
      opened_at: daysAgo(172),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 60,
      customer_id: 53,
      status: 'APPROVED',
      opened_at: daysAgo(133),
      resolved_at: daysAgo(116),
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 61,
      customer_id: 54,
      status: 'APPROVED',
      opened_at: daysAgo(79),
      resolved_at: daysAgo(39),
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 62,
      customer_id: 55,
      status: 'APPROVED',
      opened_at: daysAgo(162),
      resolved_at: daysAgo(47),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Second review scheduled.',
    },
    {
      id: 63,
      customer_id: 55,
      status: 'APPROVED',
      opened_at: daysAgo(46),
      resolved_at: daysAgo(27),
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 64,
      customer_id: 56,
      status: 'IN_REVIEW',
      opened_at: daysAgo(43),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 65,
      customer_id: 57,
      status: 'APPROVED',
      opened_at: daysAgo(179),
      resolved_at: daysAgo(9),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Awaiting proof of address.',
    },
    {
      id: 66,
      customer_id: 58,
      status: 'APPROVED',
      opened_at: daysAgo(168),
      resolved_at: daysAgo(85),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Second review scheduled.',
    },
    {
      id: 67,
      customer_id: 58,
      status: 'APPROVED',
      opened_at: daysAgo(202),
      resolved_at: daysAgo(13),
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 68,
      customer_id: 59,
      status: 'IN_REVIEW',
      opened_at: daysAgo(88),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Source of funds requested.',
    },
    {
      id: 69,
      customer_id: 60,
      status: 'OPEN',
      opened_at: daysAgo(31),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 70,
      customer_id: 61,
      status: 'APPROVED',
      opened_at: daysAgo(178),
      resolved_at: daysAgo(114),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Second review scheduled.',
    },
    {
      id: 71,
      customer_id: 62,
      status: 'IN_REVIEW',
      opened_at: daysAgo(89),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Customer responsive.',
    },
    {
      id: 72,
      customer_id: 63,
      status: 'ESCALATED',
      opened_at: daysAgo(195),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: 'PEP match requires senior review',
      notes: null,
    },
    {
      id: 73,
      customer_id: 64,
      status: 'APPROVED',
      opened_at: daysAgo(194),
      resolved_at: daysAgo(179),
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 74,
      customer_id: 65,
      status: 'OPEN',
      opened_at: daysAgo(38),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 75,
      customer_id: 66,
      status: 'REJECTED',
      opened_at: daysAgo(93),
      resolved_at: daysAgo(31),
      rejection_reason: 'Failed liveness check',
      escalation_reason: null,
      notes: 'Customer responsive.',
    },
    {
      id: 76,
      customer_id: 67,
      status: 'APPROVED',
      opened_at: daysAgo(146),
      resolved_at: daysAgo(98),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Customer responsive.',
    },
    {
      id: 77,
      customer_id: 68,
      status: 'APPROVED',
      opened_at: daysAgo(140),
      resolved_at: daysAgo(60),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Awaiting proof of address.',
    },
    {
      id: 78,
      customer_id: 68,
      status: 'APPROVED',
      opened_at: daysAgo(77),
      resolved_at: daysAgo(5),
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 79,
      customer_id: 69,
      status: 'APPROVED',
      opened_at: daysAgo(136),
      resolved_at: daysAgo(56),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Customer responsive.',
    },
    {
      id: 80,
      customer_id: 70,
      status: 'APPROVED',
      opened_at: daysAgo(160),
      resolved_at: daysAgo(44),
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 81,
      customer_id: 71,
      status: 'APPROVED',
      opened_at: daysAgo(193),
      resolved_at: daysAgo(77),
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 82,
      customer_id: 72,
      status: 'IN_REVIEW',
      opened_at: daysAgo(195),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Source of funds requested.',
    },
    {
      id: 83,
      customer_id: 73,
      status: 'APPROVED',
      opened_at: daysAgo(99),
      resolved_at: daysAgo(1),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Source of funds requested.',
    },
    {
      id: 84,
      customer_id: 74,
      status: 'APPROVED',
      opened_at: daysAgo(106),
      resolved_at: daysAgo(18),
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 85,
      customer_id: 75,
      status: 'IN_REVIEW',
      opened_at: daysAgo(155),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 86,
      customer_id: 76,
      status: 'IN_REVIEW',
      opened_at: daysAgo(167),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 87,
      customer_id: 77,
      status: 'APPROVED',
      opened_at: daysAgo(62),
      resolved_at: daysAgo(33),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Second review scheduled.',
    },
    {
      id: 88,
      customer_id: 78,
      status: 'APPROVED',
      opened_at: daysAgo(193),
      resolved_at: daysAgo(31),
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 89,
      customer_id: 79,
      status: 'IN_REVIEW',
      opened_at: daysAgo(56),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 90,
      customer_id: 79,
      status: 'APPROVED',
      opened_at: daysAgo(80),
      resolved_at: daysAgo(4),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Second review scheduled.',
    },
    {
      id: 91,
      customer_id: 80,
      status: 'APPROVED',
      opened_at: daysAgo(206),
      resolved_at: daysAgo(59),
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 92,
      customer_id: 81,
      status: 'IN_REVIEW',
      opened_at: daysAgo(159),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Customer responsive.',
    },
    {
      id: 93,
      customer_id: 82,
      status: 'IN_REVIEW',
      opened_at: daysAgo(83),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 94,
      customer_id: 82,
      status: 'APPROVED',
      opened_at: daysAgo(158),
      resolved_at: daysAgo(47),
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 95,
      customer_id: 83,
      status: 'APPROVED',
      opened_at: daysAgo(139),
      resolved_at: daysAgo(111),
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 96,
      customer_id: 84,
      status: 'IN_REVIEW',
      opened_at: daysAgo(101),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 97,
      customer_id: 84,
      status: 'IN_REVIEW',
      opened_at: daysAgo(206),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 98,
      customer_id: 85,
      status: 'IN_REVIEW',
      opened_at: daysAgo(122),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Customer responsive.',
    },
    {
      id: 99,
      customer_id: 86,
      status: 'IN_REVIEW',
      opened_at: daysAgo(99),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 100,
      customer_id: 87,
      status: 'APPROVED',
      opened_at: daysAgo(154),
      resolved_at: daysAgo(87),
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 101,
      customer_id: 87,
      status: 'APPROVED',
      opened_at: daysAgo(193),
      resolved_at: daysAgo(182),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Awaiting proof of address.',
    },
    {
      id: 102,
      customer_id: 88,
      status: 'APPROVED',
      opened_at: daysAgo(196),
      resolved_at: daysAgo(147),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Second review scheduled.',
    },
    {
      id: 103,
      customer_id: 89,
      status: 'IN_REVIEW',
      opened_at: daysAgo(56),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Awaiting proof of address.',
    },
    {
      id: 104,
      customer_id: 90,
      status: 'IN_REVIEW',
      opened_at: daysAgo(168),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Source of funds requested.',
    },
    {
      id: 105,
      customer_id: 91,
      status: 'APPROVED',
      opened_at: daysAgo(98),
      resolved_at: daysAgo(71),
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 106,
      customer_id: 92,
      status: 'OPEN',
      opened_at: daysAgo(112),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 107,
      customer_id: 93,
      status: 'IN_REVIEW',
      opened_at: daysAgo(165),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Second review scheduled.',
    },
    {
      id: 108,
      customer_id: 94,
      status: 'IN_REVIEW',
      opened_at: daysAgo(133),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 109,
      customer_id: 95,
      status: 'REJECTED',
      opened_at: daysAgo(189),
      resolved_at: daysAgo(44),
      rejection_reason: 'Failed liveness check',
      escalation_reason: null,
      notes: null,
    },
    {
      id: 110,
      customer_id: 96,
      status: 'APPROVED',
      opened_at: daysAgo(209),
      resolved_at: daysAgo(40),
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 111,
      customer_id: 97,
      status: 'APPROVED',
      opened_at: daysAgo(162),
      resolved_at: daysAgo(39),
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 112,
      customer_id: 98,
      status: 'IN_REVIEW',
      opened_at: daysAgo(138),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Second review scheduled.',
    },
    {
      id: 113,
      customer_id: 98,
      status: 'APPROVED',
      opened_at: daysAgo(142),
      resolved_at: daysAgo(50),
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 114,
      customer_id: 99,
      status: 'PENDING_APPROVAL',
      opened_at: daysAgo(104),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 115,
      customer_id: 100,
      status: 'APPROVED',
      opened_at: daysAgo(158),
      resolved_at: daysAgo(90),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Awaiting proof of address.',
    },
    {
      id: 116,
      customer_id: 101,
      status: 'REJECTED',
      opened_at: daysAgo(171),
      resolved_at: daysAgo(68),
      rejection_reason: 'Failed liveness check',
      escalation_reason: null,
      notes: null,
    },
    {
      id: 117,
      customer_id: 102,
      status: 'REJECTED',
      opened_at: daysAgo(123),
      resolved_at: daysAgo(95),
      rejection_reason: 'Document mismatch',
      escalation_reason: null,
      notes: null,
    },
    {
      id: 118,
      customer_id: 103,
      status: 'ESCALATED',
      opened_at: daysAgo(76),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: 'Adverse media hit',
      notes: null,
    },
    {
      id: 119,
      customer_id: 104,
      status: 'APPROVED',
      opened_at: daysAgo(153),
      resolved_at: daysAgo(82),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Source of funds requested.',
    },
    {
      id: 120,
      customer_id: 104,
      status: 'APPROVED',
      opened_at: daysAgo(210),
      resolved_at: daysAgo(92),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Awaiting proof of address.',
    },
    {
      id: 121,
      customer_id: 105,
      status: 'APPROVED',
      opened_at: daysAgo(40),
      resolved_at: daysAgo(18),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Awaiting proof of address.',
    },
    {
      id: 122,
      customer_id: 106,
      status: 'IN_REVIEW',
      opened_at: daysAgo(111),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 123,
      customer_id: 107,
      status: 'IN_REVIEW',
      opened_at: daysAgo(149),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 124,
      customer_id: 108,
      status: 'REJECTED',
      opened_at: daysAgo(75),
      resolved_at: daysAgo(23),
      rejection_reason: 'Sanctions concern',
      escalation_reason: null,
      notes: null,
    },
    {
      id: 125,
      customer_id: 109,
      status: 'IN_REVIEW',
      opened_at: daysAgo(154),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 126,
      customer_id: 110,
      status: 'IN_REVIEW',
      opened_at: daysAgo(60),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Source of funds requested.',
    },
    {
      id: 127,
      customer_id: 111,
      status: 'APPROVED',
      opened_at: daysAgo(50),
      resolved_at: daysAgo(31),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Source of funds requested.',
    },
    {
      id: 128,
      customer_id: 112,
      status: 'IN_REVIEW',
      opened_at: daysAgo(104),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 129,
      customer_id: 113,
      status: 'REJECTED',
      opened_at: daysAgo(207),
      resolved_at: daysAgo(55),
      rejection_reason: 'Sanctions concern',
      escalation_reason: null,
      notes: null,
    },
    {
      id: 130,
      customer_id: 114,
      status: 'APPROVED',
      opened_at: daysAgo(154),
      resolved_at: daysAgo(41),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Second review scheduled.',
    },
    {
      id: 131,
      customer_id: 115,
      status: 'IN_REVIEW',
      opened_at: daysAgo(34),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 132,
      customer_id: 116,
      status: 'APPROVED',
      opened_at: daysAgo(113),
      resolved_at: daysAgo(76),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Second review scheduled.',
    },
    {
      id: 133,
      customer_id: 117,
      status: 'APPROVED',
      opened_at: daysAgo(161),
      resolved_at: daysAgo(59),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Second review scheduled.',
    },
    {
      id: 134,
      customer_id: 118,
      status: 'PENDING_APPROVAL',
      opened_at: daysAgo(185),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Awaiting proof of address.',
    },
    {
      id: 135,
      customer_id: 119,
      status: 'IN_REVIEW',
      opened_at: daysAgo(161),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 136,
      customer_id: 120,
      status: 'REJECTED',
      opened_at: daysAgo(88),
      resolved_at: daysAgo(47),
      rejection_reason: 'Failed liveness check',
      escalation_reason: null,
      notes: 'Second review scheduled.',
    },
    {
      id: 137,
      customer_id: 120,
      status: 'ESCALATED',
      opened_at: daysAgo(178),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: 'High-risk jurisdiction',
      notes: 'Awaiting proof of address.',
    },
    {
      id: 138,
      customer_id: 121,
      status: 'IN_REVIEW',
      opened_at: daysAgo(81),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Customer responsive.',
    },
    {
      id: 139,
      customer_id: 122,
      status: 'OPEN',
      opened_at: daysAgo(107),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 140,
      customer_id: 122,
      status: 'OPEN',
      opened_at: daysAgo(124),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 141,
      customer_id: 123,
      status: 'IN_REVIEW',
      opened_at: daysAgo(190),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 142,
      customer_id: 123,
      status: 'IN_REVIEW',
      opened_at: daysAgo(203),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Source of funds requested.',
    },
    {
      id: 143,
      customer_id: 124,
      status: 'REJECTED',
      opened_at: daysAgo(38),
      resolved_at: daysAgo(22),
      rejection_reason: 'Document mismatch',
      escalation_reason: null,
      notes: null,
    },
    {
      id: 144,
      customer_id: 125,
      status: 'ESCALATED',
      opened_at: daysAgo(127),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: 'High-risk jurisdiction',
      notes: 'Source of funds requested.',
    },
    {
      id: 145,
      customer_id: 126,
      status: 'APPROVED',
      opened_at: daysAgo(34),
      resolved_at: daysAgo(13),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Second review scheduled.',
    },
    {
      id: 146,
      customer_id: 127,
      status: 'ESCALATED',
      opened_at: daysAgo(184),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: 'PEP match requires senior review',
      notes: null,
    },
    {
      id: 147,
      customer_id: 127,
      status: 'IN_REVIEW',
      opened_at: daysAgo(105),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 148,
      customer_id: 128,
      status: 'IN_REVIEW',
      opened_at: daysAgo(189),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Source of funds requested.',
    },
    {
      id: 149,
      customer_id: 128,
      status: 'PENDING_APPROVAL',
      opened_at: daysAgo(110),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Awaiting proof of address.',
    },
    {
      id: 150,
      customer_id: 129,
      status: 'PENDING_APPROVAL',
      opened_at: daysAgo(103),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Awaiting proof of address.',
    },
    {
      id: 151,
      customer_id: 130,
      status: 'IN_REVIEW',
      opened_at: daysAgo(34),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Customer responsive.',
    },
    {
      id: 152,
      customer_id: 131,
      status: 'IN_REVIEW',
      opened_at: daysAgo(167),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 153,
      customer_id: 132,
      status: 'ESCALATED',
      opened_at: daysAgo(192),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: 'Adverse media hit',
      notes: null,
    },
    {
      id: 154,
      customer_id: 133,
      status: 'APPROVED',
      opened_at: daysAgo(127),
      resolved_at: daysAgo(26),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Awaiting proof of address.',
    },
    {
      id: 155,
      customer_id: 133,
      status: 'IN_REVIEW',
      opened_at: daysAgo(98),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 156,
      customer_id: 134,
      status: 'APPROVED',
      opened_at: daysAgo(111),
      resolved_at: daysAgo(62),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Awaiting proof of address.',
    },
    {
      id: 157,
      customer_id: 134,
      status: 'APPROVED',
      opened_at: daysAgo(134),
      resolved_at: daysAgo(62),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Second review scheduled.',
    },
    {
      id: 158,
      customer_id: 135,
      status: 'IN_REVIEW',
      opened_at: daysAgo(122),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Source of funds requested.',
    },
    {
      id: 159,
      customer_id: 136,
      status: 'ESCALATED',
      opened_at: daysAgo(71),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: 'PEP match requires senior review',
      notes: 'Customer responsive.',
    },
    {
      id: 160,
      customer_id: 137,
      status: 'APPROVED',
      opened_at: daysAgo(41),
      resolved_at: daysAgo(19),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Awaiting proof of address.',
    },
    {
      id: 161,
      customer_id: 138,
      status: 'OPEN',
      opened_at: daysAgo(199),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 162,
      customer_id: 139,
      status: 'PENDING_APPROVAL',
      opened_at: daysAgo(164),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 163,
      customer_id: 140,
      status: 'IN_REVIEW',
      opened_at: daysAgo(199),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Customer responsive.',
    },
    {
      id: 164,
      customer_id: 141,
      status: 'APPROVED',
      opened_at: daysAgo(153),
      resolved_at: daysAgo(72),
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 165,
      customer_id: 142,
      status: 'IN_REVIEW',
      opened_at: daysAgo(78),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 166,
      customer_id: 143,
      status: 'IN_REVIEW',
      opened_at: daysAgo(75),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 167,
      customer_id: 143,
      status: 'APPROVED',
      opened_at: daysAgo(91),
      resolved_at: daysAgo(73),
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Customer responsive.',
    },
    {
      id: 168,
      customer_id: 144,
      status: 'IN_REVIEW',
      opened_at: daysAgo(40),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Second review scheduled.',
    },
    {
      id: 169,
      customer_id: 145,
      status: 'IN_REVIEW',
      opened_at: daysAgo(82),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Awaiting proof of address.',
    },
    {
      id: 170,
      customer_id: 146,
      status: 'REJECTED',
      opened_at: daysAgo(52),
      resolved_at: daysAgo(9),
      rejection_reason: 'Document mismatch',
      escalation_reason: null,
      notes: null,
    },
    {
      id: 171,
      customer_id: 147,
      status: 'APPROVED',
      opened_at: daysAgo(94),
      resolved_at: daysAgo(84),
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 172,
      customer_id: 148,
      status: 'IN_REVIEW',
      opened_at: daysAgo(47),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Second review scheduled.',
    },
    {
      id: 173,
      customer_id: 149,
      status: 'APPROVED',
      opened_at: daysAgo(66),
      resolved_at: daysAgo(17),
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
    {
      id: 174,
      customer_id: 150,
      status: 'OPEN',
      opened_at: daysAgo(67),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: 'Source of funds requested.',
    },
    {
      id: 175,
      customer_id: 150,
      status: 'IN_REVIEW',
      opened_at: daysAgo(87),
      resolved_at: null,
      rejection_reason: null,
      escalation_reason: null,
      notes: null,
    },
  ];

  constructor(datasource: DataSource) {
    super(datasource, 'kyc_cases', KycCasesCollection.schema);
  }
}
