import type { DataSource, FieldSchema, RecordData } from '@forestadmin/datasource-toolkit';

import BaseFintechCollection from './base';
import { dayOnlyAgo, daysAgo } from '../dates';

export default class RefundRequestsCollection extends BaseFintechCollection {
  private static schema: Record<string, FieldSchema> = {
    id: {
      type: 'Column',
      columnType: 'Number',
      isPrimaryKey: true,
    },
    reference: {
      type: 'Column',
      columnType: 'String',
    },
    customer_id: {
      type: 'Column',
      columnType: 'Number',
    },
    transaction_id: {
      type: 'Column',
      columnType: 'String',
    },
    transaction_date: {
      type: 'Column',
      columnType: 'Dateonly',
    },
    requested_at: {
      type: 'Column',
      columnType: 'Date',
    },
    amount: {
      type: 'Column',
      columnType: 'Number',
    },
    currency: {
      type: 'Column',
      columnType: 'String',
    },
    reason: {
      type: 'Column',
      columnType: 'String',
    },
    reason_detail: {
      type: 'Column',
      columnType: 'String',
    },
    status: {
      type: 'Column',
      columnType: 'String',
    },
    reviewed_at: {
      type: 'Column',
      columnType: 'Date',
    },
    reviewed_by: {
      type: 'Column',
      columnType: 'String',
    },
    resolution_notes: {
      type: 'Column',
      columnType: 'String',
    },
    escalated_to: {
      type: 'Column',
      columnType: 'String',
    },
    created_at: {
      type: 'Column',
      columnType: 'Date',
    },
  };

  protected override records: RecordData[] = [
    {
      id: 1,
      reference: 'RR-2026-00001',
      customer_id: 118,
      transaction_id: 'TXN-86201',
      transaction_date: dayOnlyAgo(15),
      requested_at: daysAgo(12),
      amount: 713.79,
      currency: 'EUR',
      reason: 'DUPLICATE_CHARGE',
      reason_detail: null,
      status: 'DECLINED',
      reviewed_at: daysAgo(9),
      reviewed_by: 'm.rossi@neobank.eu',
      resolution_notes: 'Refunded to source.',
      escalated_to: null,
      created_at: daysAgo(11),
    },
    {
      id: 2,
      reference: 'RR-2026-00002',
      customer_id: 11,
      transaction_id: 'TXN-38289',
      transaction_date: dayOnlyAgo(75),
      requested_at: daysAgo(73),
      amount: 930.9,
      currency: 'EUR',
      reason: 'ITEM_NOT_RECEIVED',
      reason_detail: 'Parcel never arrived.',
      status: 'ESCALATED',
      reviewed_at: daysAgo(60),
      reviewed_by: 'a.kowalski@neobank.eu',
      resolution_notes: 'Approved as goodwill.',
      escalated_to: 'chargebacks',
      created_at: daysAgo(74),
    },
    {
      id: 3,
      reference: 'RR-2026-00003',
      customer_id: 38,
      transaction_id: 'TXN-42652',
      transaction_date: dayOnlyAgo(31),
      requested_at: daysAgo(26),
      amount: 974.11,
      currency: 'EUR',
      reason: 'ITEM_NOT_RECEIVED',
      reason_detail: 'Charged twice for one order.',
      status: 'PENDING',
      reviewed_at: null,
      reviewed_by: null,
      resolution_notes: null,
      escalated_to: null,
      created_at: daysAgo(28),
    },
    {
      id: 4,
      reference: 'RR-2026-00004',
      customer_id: 89,
      transaction_id: 'TXN-42310',
      transaction_date: dayOnlyAgo(82),
      requested_at: daysAgo(78),
      amount: 777.97,
      currency: 'EUR',
      reason: 'SERVICE_NOT_RENDERED',
      reason_detail: 'Subscription not delivered.',
      status: 'PENDING',
      reviewed_at: null,
      reviewed_by: null,
      resolution_notes: null,
      escalated_to: null,
      created_at: daysAgo(80),
    },
    {
      id: 5,
      reference: 'RR-2026-00005',
      customer_id: 127,
      transaction_id: 'TXN-14966',
      transaction_date: dayOnlyAgo(88),
      requested_at: daysAgo(86),
      amount: 736.77,
      currency: 'EUR',
      reason: 'CANCELLED_ORDER',
      reason_detail: 'Card used without consent.',
      status: 'PENDING',
      reviewed_at: null,
      reviewed_by: null,
      resolution_notes: null,
      escalated_to: null,
      created_at: daysAgo(85),
    },
    {
      id: 6,
      reference: 'RR-2026-00006',
      customer_id: 144,
      transaction_id: 'TXN-36897',
      transaction_date: dayOnlyAgo(27),
      requested_at: daysAgo(24),
      amount: 612.32,
      currency: 'EUR',
      reason: 'CANCELLED_ORDER',
      reason_detail: null,
      status: 'ESCALATED',
      reviewed_at: daysAgo(8),
      reviewed_by: 'compliance@neobank.eu',
      resolution_notes: 'Approved as goodwill.',
      escalated_to: 'chargebacks',
      created_at: daysAgo(24),
    },
    {
      id: 7,
      reference: 'RR-2026-00007',
      customer_id: 77,
      transaction_id: 'TXN-64649',
      transaction_date: dayOnlyAgo(17),
      requested_at: daysAgo(16),
      amount: 74.35,
      currency: 'EUR',
      reason: 'UNAUTHORIZED',
      reason_detail: null,
      status: 'DECLINED',
      reviewed_at: daysAgo(1),
      reviewed_by: 'm.rossi@neobank.eu',
      resolution_notes: 'Escalated to chargeback.',
      escalated_to: null,
      created_at: daysAgo(16),
    },
    {
      id: 8,
      reference: 'RR-2026-00008',
      customer_id: 66,
      transaction_id: 'TXN-24151',
      transaction_date: dayOnlyAgo(58),
      requested_at: daysAgo(57),
      amount: 699.55,
      currency: 'EUR',
      reason: 'CANCELLED_ORDER',
      reason_detail: null,
      status: 'DECLINED',
      reviewed_at: daysAgo(39),
      reviewed_by: 'm.rossi@neobank.eu',
      resolution_notes: 'Declined — merchant evidence.',
      escalated_to: null,
      created_at: daysAgo(56),
    },
    {
      id: 9,
      reference: 'RR-2026-00009',
      customer_id: 131,
      transaction_id: 'TXN-42706',
      transaction_date: dayOnlyAgo(38),
      requested_at: daysAgo(33),
      amount: 185.65,
      currency: 'EUR',
      reason: 'CANCELLED_ORDER',
      reason_detail: 'Subscription not delivered.',
      status: 'PENDING',
      reviewed_at: null,
      reviewed_by: null,
      resolution_notes: null,
      escalated_to: null,
      created_at: daysAgo(37),
    },
    {
      id: 10,
      reference: 'RR-2026-00010',
      customer_id: 38,
      transaction_id: 'TXN-81685',
      transaction_date: dayOnlyAgo(23),
      requested_at: daysAgo(18),
      amount: 392.93,
      currency: 'EUR',
      reason: 'DUPLICATE_CHARGE',
      reason_detail: 'Charged twice for one order.',
      status: 'PENDING',
      reviewed_at: null,
      reviewed_by: null,
      resolution_notes: null,
      escalated_to: null,
      created_at: daysAgo(22),
    },
    {
      id: 11,
      reference: 'RR-2026-00011',
      customer_id: 96,
      transaction_id: 'TXN-66557',
      transaction_date: dayOnlyAgo(73),
      requested_at: daysAgo(71),
      amount: 163.54,
      currency: 'EUR',
      reason: 'ITEM_NOT_RECEIVED',
      reason_detail: null,
      status: 'APPROVED',
      reviewed_at: daysAgo(47),
      reviewed_by: 's.bauer@neobank.eu',
      resolution_notes: 'Declined — merchant evidence.',
      escalated_to: null,
      created_at: daysAgo(71),
    },
    {
      id: 12,
      reference: 'RR-2026-00012',
      customer_id: 31,
      transaction_id: 'TXN-46604',
      transaction_date: dayOnlyAgo(83),
      requested_at: daysAgo(79),
      amount: 279.74,
      currency: 'EUR',
      reason: 'DUPLICATE_CHARGE',
      reason_detail: 'Charged twice for one order.',
      status: 'APPROVED',
      reviewed_at: daysAgo(60),
      reviewed_by: 's.bauer@neobank.eu',
      resolution_notes: 'Escalated to chargeback.',
      escalated_to: null,
      created_at: daysAgo(80),
    },
    {
      id: 13,
      reference: 'RR-2026-00013',
      customer_id: 150,
      transaction_id: 'TXN-51704',
      transaction_date: dayOnlyAgo(59),
      requested_at: daysAgo(57),
      amount: 59.27,
      currency: 'EUR',
      reason: 'ITEM_NOT_RECEIVED',
      reason_detail: 'Card used without consent.',
      status: 'DECLINED',
      reviewed_at: daysAgo(27),
      reviewed_by: 's.bauer@neobank.eu',
      resolution_notes: 'Approved as goodwill.',
      escalated_to: null,
      created_at: daysAgo(57),
    },
    {
      id: 14,
      reference: 'RR-2026-00014',
      customer_id: 146,
      transaction_id: 'TXN-71976',
      transaction_date: dayOnlyAgo(64),
      requested_at: daysAgo(60),
      amount: 219.67,
      currency: 'EUR',
      reason: 'SERVICE_NOT_RENDERED',
      reason_detail: 'Subscription not delivered.',
      status: 'DECLINED',
      reviewed_at: daysAgo(12),
      reviewed_by: 'a.kowalski@neobank.eu',
      resolution_notes: 'Escalated to chargeback.',
      escalated_to: null,
      created_at: daysAgo(62),
    },
    {
      id: 15,
      reference: 'RR-2026-00015',
      customer_id: 13,
      transaction_id: 'TXN-12469',
      transaction_date: dayOnlyAgo(65),
      requested_at: daysAgo(62),
      amount: 141.6,
      currency: 'EUR',
      reason: 'ITEM_NOT_RECEIVED',
      reason_detail: null,
      status: 'DECLINED',
      reviewed_at: daysAgo(16),
      reviewed_by: 's.bauer@neobank.eu',
      resolution_notes: 'Escalated to chargeback.',
      escalated_to: null,
      created_at: daysAgo(65),
    },
    {
      id: 16,
      reference: 'RR-2026-00016',
      customer_id: 20,
      transaction_id: 'TXN-77337',
      transaction_date: dayOnlyAgo(14),
      requested_at: daysAgo(9),
      amount: 233.84,
      currency: 'EUR',
      reason: 'ITEM_NOT_RECEIVED',
      reason_detail: 'Subscription not delivered.',
      status: 'PENDING',
      reviewed_at: null,
      reviewed_by: null,
      resolution_notes: null,
      escalated_to: null,
      created_at: daysAgo(12),
    },
    {
      id: 17,
      reference: 'RR-2026-00017',
      customer_id: 20,
      transaction_id: 'TXN-41313',
      transaction_date: dayOnlyAgo(15),
      requested_at: daysAgo(13),
      amount: 265.36,
      currency: 'EUR',
      reason: 'UNAUTHORIZED',
      reason_detail: null,
      status: 'APPROVED',
      reviewed_at: daysAgo(3),
      reviewed_by: 's.bauer@neobank.eu',
      resolution_notes: 'Approved as goodwill.',
      escalated_to: null,
      created_at: daysAgo(14),
    },
    {
      id: 18,
      reference: 'RR-2026-00018',
      customer_id: 142,
      transaction_id: 'TXN-49822',
      transaction_date: dayOnlyAgo(23),
      requested_at: daysAgo(18),
      amount: 571.67,
      currency: 'EUR',
      reason: 'CANCELLED_ORDER',
      reason_detail: null,
      status: 'DECLINED',
      reviewed_at: daysAgo(5),
      reviewed_by: 's.bauer@neobank.eu',
      resolution_notes: 'Declined — merchant evidence.',
      escalated_to: null,
      created_at: daysAgo(19),
    },
    {
      id: 19,
      reference: 'RR-2026-00019',
      customer_id: 145,
      transaction_id: 'TXN-22189',
      transaction_date: dayOnlyAgo(48),
      requested_at: daysAgo(47),
      amount: 367.3,
      currency: 'EUR',
      reason: 'DUPLICATE_CHARGE',
      reason_detail: 'Card used without consent.',
      status: 'PENDING',
      reviewed_at: null,
      reviewed_by: null,
      resolution_notes: null,
      escalated_to: null,
      created_at: daysAgo(46),
    },
    {
      id: 20,
      reference: 'RR-2026-00020',
      customer_id: 104,
      transaction_id: 'TXN-22704',
      transaction_date: dayOnlyAgo(14),
      requested_at: daysAgo(13),
      amount: 337.92,
      currency: 'EUR',
      reason: 'ITEM_NOT_RECEIVED',
      reason_detail: null,
      status: 'PENDING',
      reviewed_at: null,
      reviewed_by: null,
      resolution_notes: null,
      escalated_to: null,
      created_at: daysAgo(10),
    },
    {
      id: 21,
      reference: 'RR-2026-00021',
      customer_id: 121,
      transaction_id: 'TXN-51665',
      transaction_date: dayOnlyAgo(84),
      requested_at: daysAgo(80),
      amount: 1089.3,
      currency: 'EUR',
      reason: 'CANCELLED_ORDER',
      reason_detail: 'Card used without consent.',
      status: 'PENDING',
      reviewed_at: null,
      reviewed_by: null,
      resolution_notes: null,
      escalated_to: null,
      created_at: daysAgo(80),
    },
    {
      id: 22,
      reference: 'RR-2026-00022',
      customer_id: 14,
      transaction_id: 'TXN-37559',
      transaction_date: dayOnlyAgo(53),
      requested_at: daysAgo(50),
      amount: 161.93,
      currency: 'EUR',
      reason: 'UNAUTHORIZED',
      reason_detail: null,
      status: 'ESCALATED',
      reviewed_at: daysAgo(13),
      reviewed_by: 'm.rossi@neobank.eu',
      resolution_notes: 'Approved as goodwill.',
      escalated_to: 'chargebacks',
      created_at: daysAgo(49),
    },
    {
      id: 23,
      reference: 'RR-2026-00023',
      customer_id: 82,
      transaction_id: 'TXN-13040',
      transaction_date: dayOnlyAgo(49),
      requested_at: daysAgo(45),
      amount: 383.91,
      currency: 'EUR',
      reason: 'DUPLICATE_CHARGE',
      reason_detail: null,
      status: 'PENDING',
      reviewed_at: null,
      reviewed_by: null,
      resolution_notes: null,
      escalated_to: null,
      created_at: daysAgo(47),
    },
    {
      id: 24,
      reference: 'RR-2026-00024',
      customer_id: 142,
      transaction_id: 'TXN-42853',
      transaction_date: dayOnlyAgo(62),
      requested_at: daysAgo(59),
      amount: 506.68,
      currency: 'EUR',
      reason: 'DUPLICATE_CHARGE',
      reason_detail: 'Subscription not delivered.',
      status: 'APPROVED',
      reviewed_at: daysAgo(18),
      reviewed_by: 'compliance@neobank.eu',
      resolution_notes: 'Declined — merchant evidence.',
      escalated_to: null,
      created_at: daysAgo(58),
    },
    {
      id: 25,
      reference: 'RR-2026-00025',
      customer_id: 8,
      transaction_id: 'TXN-53109',
      transaction_date: dayOnlyAgo(89),
      requested_at: daysAgo(84),
      amount: 1159.03,
      currency: 'EUR',
      reason: 'ITEM_NOT_RECEIVED',
      reason_detail: null,
      status: 'APPROVED',
      reviewed_at: daysAgo(22),
      reviewed_by: 'm.rossi@neobank.eu',
      resolution_notes: 'Refunded to source.',
      escalated_to: null,
      created_at: daysAgo(89),
    },
    {
      id: 26,
      reference: 'RR-2026-00026',
      customer_id: 150,
      transaction_id: 'TXN-97638',
      transaction_date: dayOnlyAgo(81),
      requested_at: daysAgo(79),
      amount: 99.09,
      currency: 'EUR',
      reason: 'CANCELLED_ORDER',
      reason_detail: null,
      status: 'APPROVED',
      reviewed_at: daysAgo(62),
      reviewed_by: 'compliance@neobank.eu',
      resolution_notes: 'Escalated to chargeback.',
      escalated_to: null,
      created_at: daysAgo(77),
    },
    {
      id: 27,
      reference: 'RR-2026-00027',
      customer_id: 10,
      transaction_id: 'TXN-32856',
      transaction_date: dayOnlyAgo(17),
      requested_at: daysAgo(12),
      amount: 496.41,
      currency: 'EUR',
      reason: 'UNAUTHORIZED',
      reason_detail: null,
      status: 'ESCALATED',
      reviewed_at: daysAgo(13),
      reviewed_by: 'a.kowalski@neobank.eu',
      resolution_notes: 'Approved as goodwill.',
      escalated_to: 'chargebacks',
      created_at: daysAgo(14),
    },
    {
      id: 28,
      reference: 'RR-2026-00028',
      customer_id: 114,
      transaction_id: 'TXN-15550',
      transaction_date: dayOnlyAgo(27),
      requested_at: daysAgo(22),
      amount: 480.18,
      currency: 'EUR',
      reason: 'SERVICE_NOT_RENDERED',
      reason_detail: null,
      status: 'PENDING',
      reviewed_at: null,
      reviewed_by: null,
      resolution_notes: null,
      escalated_to: null,
      created_at: daysAgo(23),
    },
    {
      id: 29,
      reference: 'RR-2026-00029',
      customer_id: 123,
      transaction_id: 'TXN-61498',
      transaction_date: dayOnlyAgo(37),
      requested_at: daysAgo(35),
      amount: 1187.46,
      currency: 'EUR',
      reason: 'UNAUTHORIZED',
      reason_detail: null,
      status: 'ESCALATED',
      reviewed_at: daysAgo(5),
      reviewed_by: 'compliance@neobank.eu',
      resolution_notes: 'Refunded to source.',
      escalated_to: 'chargebacks',
      created_at: daysAgo(37),
    },
    {
      id: 30,
      reference: 'RR-2026-00030',
      customer_id: 63,
      transaction_id: 'TXN-74590',
      transaction_date: dayOnlyAgo(38),
      requested_at: daysAgo(37),
      amount: 199.9,
      currency: 'EUR',
      reason: 'ITEM_NOT_RECEIVED',
      reason_detail: 'Parcel never arrived.',
      status: 'PENDING',
      reviewed_at: null,
      reviewed_by: null,
      resolution_notes: null,
      escalated_to: null,
      created_at: daysAgo(37),
    },
    {
      id: 31,
      reference: 'RR-2026-00031',
      customer_id: 92,
      transaction_id: 'TXN-36291',
      transaction_date: dayOnlyAgo(44),
      requested_at: daysAgo(41),
      amount: 427.66,
      currency: 'EUR',
      reason: 'SERVICE_NOT_RENDERED',
      reason_detail: null,
      status: 'APPROVED',
      reviewed_at: daysAgo(4),
      reviewed_by: 'a.kowalski@neobank.eu',
      resolution_notes: 'Refunded to source.',
      escalated_to: null,
      created_at: daysAgo(42),
    },
    {
      id: 32,
      reference: 'RR-2026-00032',
      customer_id: 120,
      transaction_id: 'TXN-13254',
      transaction_date: dayOnlyAgo(12),
      requested_at: daysAgo(8),
      amount: 952.9,
      currency: 'EUR',
      reason: 'SERVICE_NOT_RENDERED',
      reason_detail: null,
      status: 'DECLINED',
      reviewed_at: daysAgo(6),
      reviewed_by: 'a.kowalski@neobank.eu',
      resolution_notes: 'Declined — merchant evidence.',
      escalated_to: null,
      created_at: daysAgo(12),
    },
    {
      id: 33,
      reference: 'RR-2026-00033',
      customer_id: 126,
      transaction_id: 'TXN-66731',
      transaction_date: dayOnlyAgo(80),
      requested_at: daysAgo(76),
      amount: 1068.85,
      currency: 'EUR',
      reason: 'SERVICE_NOT_RENDERED',
      reason_detail: null,
      status: 'APPROVED',
      reviewed_at: daysAgo(37),
      reviewed_by: 's.bauer@neobank.eu',
      resolution_notes: 'Escalated to chargeback.',
      escalated_to: null,
      created_at: daysAgo(78),
    },
    {
      id: 34,
      reference: 'RR-2026-00034',
      customer_id: 46,
      transaction_id: 'TXN-43881',
      transaction_date: dayOnlyAgo(19),
      requested_at: daysAgo(15),
      amount: 465.96,
      currency: 'EUR',
      reason: 'SERVICE_NOT_RENDERED',
      reason_detail: 'Card used without consent.',
      status: 'APPROVED',
      reviewed_at: daysAgo(9),
      reviewed_by: 'm.rossi@neobank.eu',
      resolution_notes: 'Declined — merchant evidence.',
      escalated_to: null,
      created_at: daysAgo(19),
    },
    {
      id: 35,
      reference: 'RR-2026-00035',
      customer_id: 127,
      transaction_id: 'TXN-66575',
      transaction_date: dayOnlyAgo(47),
      requested_at: daysAgo(46),
      amount: 475.32,
      currency: 'EUR',
      reason: 'CANCELLED_ORDER',
      reason_detail: null,
      status: 'APPROVED',
      reviewed_at: daysAgo(11),
      reviewed_by: 'compliance@neobank.eu',
      resolution_notes: 'Escalated to chargeback.',
      escalated_to: null,
      created_at: daysAgo(46),
    },
    {
      id: 36,
      reference: 'RR-2026-00036',
      customer_id: 130,
      transaction_id: 'TXN-79423',
      transaction_date: dayOnlyAgo(71),
      requested_at: daysAgo(66),
      amount: 234.12,
      currency: 'EUR',
      reason: 'DUPLICATE_CHARGE',
      reason_detail: null,
      status: 'DECLINED',
      reviewed_at: daysAgo(40),
      reviewed_by: 's.bauer@neobank.eu',
      resolution_notes: 'Approved as goodwill.',
      escalated_to: null,
      created_at: daysAgo(70),
    },
    {
      id: 37,
      reference: 'RR-2026-00037',
      customer_id: 53,
      transaction_id: 'TXN-92600',
      transaction_date: dayOnlyAgo(19),
      requested_at: daysAgo(14),
      amount: 679.78,
      currency: 'EUR',
      reason: 'DUPLICATE_CHARGE',
      reason_detail: 'Subscription not delivered.',
      status: 'DECLINED',
      reviewed_at: daysAgo(5),
      reviewed_by: 's.bauer@neobank.eu',
      resolution_notes: 'Escalated to chargeback.',
      escalated_to: null,
      created_at: daysAgo(18),
    },
    {
      id: 38,
      reference: 'RR-2026-00038',
      customer_id: 63,
      transaction_id: 'TXN-81415',
      transaction_date: dayOnlyAgo(31),
      requested_at: daysAgo(26),
      amount: 229.04,
      currency: 'EUR',
      reason: 'ITEM_NOT_RECEIVED',
      reason_detail: null,
      status: 'APPROVED',
      reviewed_at: daysAgo(22),
      reviewed_by: 'a.kowalski@neobank.eu',
      resolution_notes: 'Declined — merchant evidence.',
      escalated_to: null,
      created_at: daysAgo(31),
    },
    {
      id: 39,
      reference: 'RR-2026-00039',
      customer_id: 109,
      transaction_id: 'TXN-50787',
      transaction_date: dayOnlyAgo(54),
      requested_at: daysAgo(51),
      amount: 239.32,
      currency: 'EUR',
      reason: 'CANCELLED_ORDER',
      reason_detail: 'Subscription not delivered.',
      status: 'PENDING',
      reviewed_at: null,
      reviewed_by: null,
      resolution_notes: null,
      escalated_to: null,
      created_at: daysAgo(51),
    },
    {
      id: 40,
      reference: 'RR-2026-00040',
      customer_id: 71,
      transaction_id: 'TXN-24846',
      transaction_date: dayOnlyAgo(27),
      requested_at: daysAgo(24),
      amount: 245.74,
      currency: 'EUR',
      reason: 'ITEM_NOT_RECEIVED',
      reason_detail: 'Charged twice for one order.',
      status: 'DECLINED',
      reviewed_at: daysAgo(9),
      reviewed_by: 's.bauer@neobank.eu',
      resolution_notes: 'Declined — merchant evidence.',
      escalated_to: null,
      created_at: daysAgo(24),
    },
    {
      id: 41,
      reference: 'RR-2026-00041',
      customer_id: 100,
      transaction_id: 'TXN-54004',
      transaction_date: dayOnlyAgo(50),
      requested_at: daysAgo(49),
      amount: 473.06,
      currency: 'EUR',
      reason: 'SERVICE_NOT_RENDERED',
      reason_detail: 'Card used without consent.',
      status: 'PENDING',
      reviewed_at: null,
      reviewed_by: null,
      resolution_notes: null,
      escalated_to: null,
      created_at: daysAgo(47),
    },
    {
      id: 42,
      reference: 'RR-2026-00042',
      customer_id: 39,
      transaction_id: 'TXN-99643',
      transaction_date: dayOnlyAgo(79),
      requested_at: daysAgo(76),
      amount: 1031.44,
      currency: 'EUR',
      reason: 'SERVICE_NOT_RENDERED',
      reason_detail: null,
      status: 'APPROVED',
      reviewed_at: daysAgo(21),
      reviewed_by: 'm.rossi@neobank.eu',
      resolution_notes: 'Declined — merchant evidence.',
      escalated_to: null,
      created_at: daysAgo(78),
    },
    {
      id: 43,
      reference: 'RR-2026-00043',
      customer_id: 8,
      transaction_id: 'TXN-91411',
      transaction_date: dayOnlyAgo(17),
      requested_at: daysAgo(13),
      amount: 254.24,
      currency: 'EUR',
      reason: 'ITEM_NOT_RECEIVED',
      reason_detail: 'Parcel never arrived.',
      status: 'APPROVED',
      reviewed_at: daysAgo(10),
      reviewed_by: 'a.kowalski@neobank.eu',
      resolution_notes: 'Approved as goodwill.',
      escalated_to: null,
      created_at: daysAgo(13),
    },
    {
      id: 44,
      reference: 'RR-2026-00044',
      customer_id: 87,
      transaction_id: 'TXN-72053',
      transaction_date: dayOnlyAgo(54),
      requested_at: daysAgo(53),
      amount: 290.24,
      currency: 'EUR',
      reason: 'DUPLICATE_CHARGE',
      reason_detail: 'Subscription not delivered.',
      status: 'PENDING',
      reviewed_at: null,
      reviewed_by: null,
      resolution_notes: null,
      escalated_to: null,
      created_at: daysAgo(52),
    },
    {
      id: 45,
      reference: 'RR-2026-00045',
      customer_id: 38,
      transaction_id: 'TXN-79395',
      transaction_date: dayOnlyAgo(57),
      requested_at: daysAgo(54),
      amount: 318.72,
      currency: 'EUR',
      reason: 'SERVICE_NOT_RENDERED',
      reason_detail: 'Charged twice for one order.',
      status: 'APPROVED',
      reviewed_at: daysAgo(29),
      reviewed_by: 'compliance@neobank.eu',
      resolution_notes: 'Refunded to source.',
      escalated_to: null,
      created_at: daysAgo(53),
    },
    {
      id: 46,
      reference: 'RR-2026-00046',
      customer_id: 92,
      transaction_id: 'TXN-89661',
      transaction_date: dayOnlyAgo(32),
      requested_at: daysAgo(28),
      amount: 583.42,
      currency: 'EUR',
      reason: 'CANCELLED_ORDER',
      reason_detail: 'Card used without consent.',
      status: 'APPROVED',
      reviewed_at: daysAgo(25),
      reviewed_by: 's.bauer@neobank.eu',
      resolution_notes: 'Escalated to chargeback.',
      escalated_to: null,
      created_at: daysAgo(32),
    },
    {
      id: 47,
      reference: 'RR-2026-00047',
      customer_id: 53,
      transaction_id: 'TXN-37778',
      transaction_date: dayOnlyAgo(55),
      requested_at: daysAgo(50),
      amount: 771.27,
      currency: 'EUR',
      reason: 'CANCELLED_ORDER',
      reason_detail: 'Subscription not delivered.',
      status: 'PENDING',
      reviewed_at: null,
      reviewed_by: null,
      resolution_notes: null,
      escalated_to: null,
      created_at: daysAgo(51),
    },
    {
      id: 48,
      reference: 'RR-2026-00048',
      customer_id: 122,
      transaction_id: 'TXN-68267',
      transaction_date: dayOnlyAgo(36),
      requested_at: daysAgo(33),
      amount: 319.81,
      currency: 'EUR',
      reason: 'DUPLICATE_CHARGE',
      reason_detail: 'Parcel never arrived.',
      status: 'APPROVED',
      reviewed_at: daysAgo(13),
      reviewed_by: 'compliance@neobank.eu',
      resolution_notes: 'Escalated to chargeback.',
      escalated_to: null,
      created_at: daysAgo(36),
    },
    {
      id: 49,
      reference: 'RR-2026-00049',
      customer_id: 4,
      transaction_id: 'TXN-88656',
      transaction_date: dayOnlyAgo(16),
      requested_at: daysAgo(12),
      amount: 1074.68,
      currency: 'EUR',
      reason: 'SERVICE_NOT_RENDERED',
      reason_detail: null,
      status: 'PENDING',
      reviewed_at: null,
      reviewed_by: null,
      resolution_notes: null,
      escalated_to: null,
      created_at: daysAgo(12),
    },
    {
      id: 50,
      reference: 'RR-2026-00050',
      customer_id: 6,
      transaction_id: 'TXN-80756',
      transaction_date: dayOnlyAgo(19),
      requested_at: daysAgo(18),
      amount: 488.27,
      currency: 'EUR',
      reason: 'SERVICE_NOT_RENDERED',
      reason_detail: null,
      status: 'DECLINED',
      reviewed_at: daysAgo(8),
      reviewed_by: 'a.kowalski@neobank.eu',
      resolution_notes: 'Approved as goodwill.',
      escalated_to: null,
      created_at: daysAgo(15),
    },
    {
      id: 51,
      reference: 'RR-2026-00051',
      customer_id: 32,
      transaction_id: 'TXN-74361',
      transaction_date: dayOnlyAgo(14),
      requested_at: daysAgo(10),
      amount: 119.99,
      currency: 'EUR',
      reason: 'UNAUTHORIZED',
      reason_detail: null,
      status: 'DECLINED',
      reviewed_at: daysAgo(3),
      reviewed_by: 'a.kowalski@neobank.eu',
      resolution_notes: 'Declined — merchant evidence.',
      escalated_to: null,
      created_at: daysAgo(14),
    },
    {
      id: 52,
      reference: 'RR-2026-00052',
      customer_id: 113,
      transaction_id: 'TXN-10338',
      transaction_date: dayOnlyAgo(74),
      requested_at: daysAgo(71),
      amount: 114.92,
      currency: 'EUR',
      reason: 'CANCELLED_ORDER',
      reason_detail: null,
      status: 'DECLINED',
      reviewed_at: daysAgo(64),
      reviewed_by: 'a.kowalski@neobank.eu',
      resolution_notes: 'Declined — merchant evidence.',
      escalated_to: null,
      created_at: daysAgo(72),
    },
    {
      id: 53,
      reference: 'RR-2026-00053',
      customer_id: 60,
      transaction_id: 'TXN-73744',
      transaction_date: dayOnlyAgo(17),
      requested_at: daysAgo(15),
      amount: 450.57,
      currency: 'EUR',
      reason: 'SERVICE_NOT_RENDERED',
      reason_detail: 'Subscription not delivered.',
      status: 'DECLINED',
      reviewed_at: daysAgo(8),
      reviewed_by: 's.bauer@neobank.eu',
      resolution_notes: 'Escalated to chargeback.',
      escalated_to: null,
      created_at: daysAgo(17),
    },
    {
      id: 54,
      reference: 'RR-2026-00054',
      customer_id: 140,
      transaction_id: 'TXN-72023',
      transaction_date: dayOnlyAgo(18),
      requested_at: daysAgo(13),
      amount: 1128.51,
      currency: 'EUR',
      reason: 'CANCELLED_ORDER',
      reason_detail: 'Card used without consent.',
      status: 'ESCALATED',
      reviewed_at: daysAgo(1),
      reviewed_by: 'compliance@neobank.eu',
      resolution_notes: 'Declined — merchant evidence.',
      escalated_to: 'chargebacks',
      created_at: daysAgo(16),
    },
    {
      id: 55,
      reference: 'RR-2026-00055',
      customer_id: 75,
      transaction_id: 'TXN-70213',
      transaction_date: dayOnlyAgo(30),
      requested_at: daysAgo(26),
      amount: 53.8,
      currency: 'EUR',
      reason: 'UNAUTHORIZED',
      reason_detail: 'Card used without consent.',
      status: 'DECLINED',
      reviewed_at: daysAgo(26),
      reviewed_by: 'a.kowalski@neobank.eu',
      resolution_notes: 'Refunded to source.',
      escalated_to: null,
      created_at: daysAgo(27),
    },
  ];

  constructor(datasource: DataSource) {
    super(datasource, 'refund_requests', RefundRequestsCollection.schema);
  }
}
